#!/usr/bin/env python3
"""Generates the typed Python SDK `kentos.cad` from the product command
catalog (docs/adr/0131; TODOS.md PY-10, PY-11, PY-16).

Reads apps/web/src/contracts/generated/commandCatalog.json, which the Rust
contracts write (`KENTOS_WRITE_CATALOG=1 cargo test -p kentos-contracts`),
and writes under python/kentos/cad/:

- types.py: every type of every command's input, output and plan, as the
  catalog's JSON Schemas give them: str enums (with a Literal of their
  names), dataclasses, tagged unions (a base class and one class per
  variant), each with its JSON codec (`to_json`, `from_json`);
- one module per command namespace, a wrapper per command under the
  command's own name (`cad.polygon.create` → `kentos.cad.polygon.create`,
  `project.checkpoint.create` → `kentos.cad.project.checkpoint.create`);
- _index.py: every wrapper by command id.

`--check` compares instead of writing and fails on a difference (CI).
Standard library only.
"""

from __future__ import annotations

import argparse
import ast
import json
import keyword
import re
import sys
import textwrap
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "apps/web/src/contracts/generated/commandCatalog.json"
OUT = ROOT / "python/kentos/cad"
HEADER = (
    "# Generated by scripts/python/sdk.py from the command catalog\n"
    "# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run\n"
    "# `python3 scripts/python/sdk.py` after the catalog changes.\n"
)


class Fail(Exception):
    pass


# ---------------------------------------------------------------- names


def snake(name: str) -> str:
    """`layerId` → `layer_id`; a Python keyword gets a trailing underscore."""
    s = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", name).replace("-", "_").lower()
    return s + "_" if keyword.iskeyword(s) else s


def pascal(value: str) -> str:
    """`vertexAdd` → `VertexAdd`, `plex-mono` → `PlexMono`."""
    parts = re.split(r"[^A-Za-z0-9]+", value)
    out = []
    for p in parts:
        for w in re.findall(r"[A-Z]?[a-z0-9]+|[A-Z]+(?![a-z])", p):
            out.append(w[:1].upper() + w[1:])
    return "".join(out)


def member(value: str) -> str:
    """An enum member's name: `vertexAdd` → `VERTEX_ADD`, `m2` → `M2`."""
    s = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", value)
    s = re.sub(r"[^A-Za-z0-9]+", "_", s).strip("_").upper()
    if not s or s[0].isdigit():
        s = "V_" + s
    return s


def ref_name(ref: str) -> str:
    prefix = "#/$defs/"
    if not ref.startswith(prefix):
        raise Fail(f"unknown reference {ref}")
    return ref[len(prefix):]


def doc_text(text: str | None) -> str:
    return (text or "").strip().replace("\\", "\\\\").replace('"""', '\\"\\"\\"')


def docstring(text: str, indent: str) -> str:
    """A docstring at `indent`; empty text gives none."""
    text = text.rstrip()
    if not text:
        return ""
    lines = text.split("\n")
    body = "\n".join((indent + line) if line.strip() else "" for line in lines[1:])
    if len(lines) == 1:
        return f'{indent}"""{lines[0]}"""\n'
    return f'{indent}"""{lines[0]}\n{body}\n{indent}"""\n'


def q(text: str) -> str:
    """A double-quoted Python string literal."""
    return json.dumps(text, ensure_ascii=False)


def wrap(text: str, width: int = 84) -> str:
    """Long prose (a command's Turkish summary) in lines of `width`."""
    return "\n".join(
        textwrap.fill(p, width=width, break_long_words=False, break_on_hyphens=False) for p in text.split("\n")
    )


def indent_lines(text: str, indent: str) -> str:
    return "\n".join((indent + line) if line.strip() else "" for line in text.split("\n"))


# ---------------------------------------------------------------- types


@dataclass
class Prim:
    py: str  # str, float, int, bool


@dataclass
class AnyT:
    pass


@dataclass
class Ref:
    name: str


@dataclass
class ListT:
    item: object


@dataclass
class MapT:
    value: object


@dataclass
class Nullable:
    inner: object


@dataclass
class Field:
    wire: str
    py: str
    type: object
    required: bool
    description: str
    default: object = None  # the schema's default (JSON), or None
    has_default: bool = False


@dataclass
class Struct:
    name: str
    description: str
    fields: list[Field]
    # When the struct is itself a union's variant: (union, tag, value).
    variant_of: tuple[str, str, str] | None = None


@dataclass
class Enum:
    name: str
    description: str
    members: list[tuple[str, str]]  # (value, description)


@dataclass
class Variant:
    value: str
    cls: str
    description: str
    base_struct: str | None  # a variant that is a struct with the tag added
    fields: list[Field] = field(default_factory=list)


@dataclass
class Union:
    name: str
    description: str
    tag: str
    variants: list[Variant]


class Model:
    """Every named type of the catalog, classified."""

    def __init__(self, schemas: dict[str, dict]):
        self.schemas = schemas
        self.enums: dict[str, Enum] = {}
        self.structs: dict[str, Struct] = {}
        self.unions: dict[str, Union] = {}
        # A value of one of a few JSON kinds (a project variable's: none, true/false, a number, text): name → (description, hint).
        self.aliases: dict[str, tuple[str, str]] = {}
        for name in sorted(schemas):
            self.classify(name, schemas[name])
        self.mark_variants()

    def kind(self, name: str) -> str:
        if name == "Vec2":
            return "vec2"
        if name in self.enums:
            return "enum"
        if name in self.unions:
            return "union"
        if name in self.structs:
            return "struct"
        if name in self.aliases:
            return "alias"
        raise Fail(f"unknown type {name}")

    def classify(self, name: str, s: dict) -> None:
        # Any of a few JSON kinds, none of them made of others: the value as it is.
        scalar = {"null": "None", "boolean": "bool", "number": "float", "integer": "int", "string": "str"}
        if "anyOf" in s and all(set(a) <= {"type", "format", "description"} and a.get("type") in scalar for a in s["anyOf"]):
            kinds = [scalar[a["type"]] for a in s["anyOf"]]
            hint = " | ".join([k for k in kinds if k != "None"] + (["None"] if "None" in kinds else []))
            self.aliases[name] = (s.get("description", ""), hint)
            return
        if s.get("type") == "string" and "enum" in s:
            self.enums[name] = Enum(name, s.get("description", ""), [(v, "") for v in s["enum"]])
            return
        if "oneOf" in s:
            alts = s["oneOf"]
            if all(is_string_choice(a) for a in alts):
                members: list[tuple[str, str]] = []
                for a in alts:
                    if "const" in a:
                        members.append((a["const"], a.get("description", "")))
                    else:
                        members.extend((v, a.get("description", "")) for v in a["enum"])
                self.enums[name] = Enum(name, s.get("description", ""), members)
                return
            tag = union_tag(alts)
            if tag is None:
                raise Fail(f"{name}: a oneOf that is neither an enum nor a tagged union")
            variants = []
            for a in alts:
                value = a["properties"][tag]["const"]
                cls = pascal(value) + name
                if "$ref" in a:
                    extra = [k for k in a["properties"] if k != tag]
                    if extra:
                        raise Fail(f"{name}.{value}: a variant adds {extra} to its struct")
                    variants.append(Variant(value, cls, a.get("description", ""), ref_name(a["$ref"])))
                else:
                    props = {k: v for k, v in a.get("properties", {}).items() if k != tag}
                    required = [r for r in a.get("required", []) if r != tag]
                    fields = self.fields_of(f"{name}.{value}", props, required)
                    variants.append(Variant(value, cls, a.get("description", ""), None, fields))
            self.unions[name] = Union(name, s.get("description", ""), tag, variants)
            return
        if s.get("type") == "object":
            fields = self.fields_of(name, s.get("properties", {}), s.get("required", []))
            self.structs[name] = Struct(name, s.get("description", ""), fields)
            return
        raise Fail(f"{name}: unsupported schema {json.dumps(s)[:200]}")

    def fields_of(self, where: str, props: dict, required: list[str]) -> list[Field]:
        out = []
        order = list(required) + sorted(k for k in props if k not in required)
        for wire in order:
            p = props[wire]
            f = Field(
                wire=wire,
                py=snake(wire),
                type=parse_type(p, f"{where}.{wire}"),
                required=wire in required,
                description=p.get("description", "") if isinstance(p, dict) else "",
            )
            if isinstance(p, dict) and "default" in p:
                f.default = p["default"]
                f.has_default = True
            out.append(f)
        names = [f.py for f in out]
        if len(set(names)) != len(names):
            raise Fail(f"{where}: two fields with one Python name {names}")
        return out

    def mark_variants(self) -> None:
        """A variant made of a struct and a tag: when the variant's own name
        is the struct's (Entity/point → PointEntity) the struct itself is the
        variant; otherwise a subclass adds the tag (Entity/polyline →
        PolylineEntity over PathEntity)."""
        used_directly = struct_refs_outside_unions(self.schemas)
        for u in self.unions.values():
            for v in u.variants:
                if v.base_struct is None:
                    continue
                if v.base_struct not in self.structs:
                    raise Fail(f"{u.name}.{v.value}: {v.base_struct} is not a struct")
                if v.cls == v.base_struct:
                    if v.base_struct in used_directly:
                        raise Fail(f"{v.base_struct} is a variant of {u.name} and used alone too")
                    self.structs[v.base_struct].variant_of = (u.name, u.tag, v.value)
                elif v.cls in self.schemas:
                    raise Fail(f"{u.name}.{v.value}: the name {v.cls} is taken")


def is_string_choice(a: dict) -> bool:
    return a.get("type") == "string" and ("const" in a or "enum" in a) and "properties" not in a


def union_tag(alts: list[dict]) -> str | None:
    if not all(a.get("type") == "object" and "properties" in a for a in alts):
        return None
    common = set.intersection(*(set(a["properties"]) for a in alts))
    for name in sorted(common):
        if all("const" in a["properties"][name] for a in alts):
            values = [a["properties"][name]["const"] for a in alts]
            if len(set(values)) == len(values):
                return name
    return None


def struct_refs_outside_unions(schemas: dict[str, dict]) -> set[str]:
    """The names referenced anywhere but as a whole union variant."""
    found: set[str] = set()

    def walk(node, in_variant: bool) -> None:
        if isinstance(node, dict):
            if "$ref" in node and not in_variant:
                found.add(ref_name(node["$ref"]))
            for k, v in node.items():
                if k == "oneOf" and isinstance(v, list):
                    for alt in v:
                        if isinstance(alt, dict) and "$ref" in alt and "properties" in alt:
                            walk({k2: v2 for k2, v2 in alt.items() if k2 != "$ref"}, False)
                        else:
                            walk(alt, False)
                elif k != "$ref":
                    walk(v, False)
        elif isinstance(node, list):
            for v in node:
                walk(v, False)

    for s in schemas.values():
        walk(s, False)
    return found


def parse_type(s, where: str):
    # Any JSON: a schema that says nothing of its type (only what it is for, a renderer's JSON).
    if s is True or (isinstance(s, dict) and set(s) <= {"description", "title"}):
        return AnyT()
    if not isinstance(s, dict):
        raise Fail(f"{where}: unsupported schema {s!r}")
    if "$ref" in s:
        return Ref(ref_name(s["$ref"]))
    if "anyOf" in s:
        alts = s["anyOf"]
        rest = [a for a in alts if a != {"type": "null"}]
        if len(alts) == 2 and len(rest) == 1:
            return Nullable(parse_type(rest[0], where))
        raise Fail(f"{where}: unsupported anyOf")
    if "oneOf" in s or "allOf" in s:
        raise Fail(f"{where}: an inline union; name it in the contracts")
    t = s.get("type")
    if isinstance(t, list):
        rest = [x for x in t if x != "null"]
        if "null" in t and len(rest) == 1:
            return Nullable(parse_type({**s, "type": rest[0]}, where))
        raise Fail(f"{where}: unsupported type list {t}")
    if t == "string":
        if "enum" in s:
            raise Fail(f"{where}: an inline enum; name it in the contracts")
        return Prim("str")
    if t == "number":
        return Prim("float")
    if t == "integer":
        return Prim("int")
    if t == "boolean":
        return Prim("bool")
    if t == "array":
        return ListT(parse_type(s.get("items", True), where + "[]"))
    if t == "object":
        if s.get("properties"):
            raise Fail(f"{where}: an inline object; name it in the contracts")
        return MapT(parse_type(s.get("additionalProperties", True), where + "{}"))
    raise Fail(f"{where}: unsupported schema {json.dumps(s)[:200]}")


# ---------------------------------------------------------------- expressions


class Emit:
    """Type hints and codec expressions of a parsed type."""

    def __init__(self, model: Model):
        self.m = model

    def hint(self, t, loose: bool = False) -> str:
        """The annotation; `loose` for a wrapper's parameter (a sequence, a
        point as a pair, an enum as its name)."""
        if isinstance(t, Prim):
            return t.py
        if isinstance(t, AnyT):
            return "Any"
        if isinstance(t, Ref):
            k = self.m.kind(t.name)
            if k == "enum":
                return f"{t.name} | {t.name}Name"
            if k == "vec2" and loose:
                return "Vec2Like"
            return t.name
        if isinstance(t, ListT):
            inner = self.hint(t.item, loose)
            return f"Sequence[{inner}]" if loose else f"list[{inner}]"
        if isinstance(t, MapT):
            inner = self.hint(t.value, loose)
            return f"Mapping[str, {inner}]" if loose else f"dict[str, {inner}]"
        if isinstance(t, Nullable):
            return f"{self.hint(t.inner, loose)} | None"
        raise Fail(repr(t))

    def enc(self, t, v: str, depth: int = 0) -> str:
        """The expression that writes `v` as JSON."""
        e = f"e{depth}"
        if isinstance(t, Prim):
            return f"float({v})" if t.py == "float" else v
        if isinstance(t, AnyT):
            return v
        if isinstance(t, Ref):
            k = self.m.kind(t.name)
            if k == "enum":
                return f"_enum_out({v})"
            if k == "vec2":
                return f"_vec2_out({v})"
            if k == "alias":
                return v
            return f"{v}.to_json()"
        if isinstance(t, ListT):
            inner = self.enc(t.item, e, depth + 1)
            return f"list({v})" if inner == e else f"[{inner} for {e} in {v}]"
        if isinstance(t, MapT):
            inner = self.enc(t.value, e, depth + 1)
            return f"dict({v})" if inner == e else f"{{k{depth}: {inner} for k{depth}, {e} in {v}.items()}}"
        if isinstance(t, Nullable):
            inner = self.enc(t.inner, v, depth)
            return v if inner == v else f"None if {v} is None else {inner}"
        raise Fail(repr(t))

    def dec(self, t, v: str, depth: int = 0) -> str:
        """The expression that reads `v` from JSON."""
        e = f"e{depth}"
        if isinstance(t, Prim):
            return f"float({v})" if t.py == "float" else v
        if isinstance(t, AnyT):
            return v
        if isinstance(t, Ref):
            k = self.m.kind(t.name)
            if k == "enum":
                return f"_enum_in({t.name}, {v})"
            if k == "alias":
                return v
            return f"{t.name}.from_json({v})"
        if isinstance(t, ListT):
            inner = self.dec(t.item, e, depth + 1)
            return f"list({v})" if inner == e else f"[{inner} for {e} in {v}]"
        if isinstance(t, MapT):
            inner = self.dec(t.value, e, depth + 1)
            return f"dict({v})" if inner == e else f"{{k{depth}: {inner} for k{depth}, {e} in {v}.items()}}"
        if isinstance(t, Nullable):
            inner = self.dec(t.inner, v, depth)
            return v if inner == v else f"None if {v} is None else {inner}"
        raise Fail(repr(t))

    def default_literal(self, f: Field) -> str:
        """The Python default of a field whose schema gives one."""
        d = f.default
        t = f.type.inner if isinstance(f.type, Nullable) else f.type
        if isinstance(t, Ref) and self.m.kind(t.name) == "enum" and isinstance(d, str):
            return f"{t.name}.{member(d)}"
        if isinstance(d, bool) or d is None or isinstance(d, (int, float, str)):
            if isinstance(t, Prim) and t.py == "float" and isinstance(d, int) and not isinstance(d, bool):
                return repr(float(d))
            return q(d) if isinstance(d, str) else repr(d)
        if d == [] or d == {}:
            return "list" if d == [] else "dict"  # a factory
        raise Fail(f"{f.wire}: unsupported default {d!r}")


def is_factory(literal: str) -> bool:
    return literal in ("list", "dict")


# ---------------------------------------------------------------- types.py


def field_decl(em: Emit, f: Field) -> str:
    hint = em.hint(f.type)
    if f.required:
        return f"{f.py}: {hint}"
    if f.has_default:
        lit = em.default_literal(f)
        if is_factory(lit):
            return f"{f.py}: {hint} = field(default_factory={lit})"
        return f"{f.py}: {hint} = {lit}"
    return f"{f.py}: {hint} | Unset = UNSET"


def encode_lines(em: Emit, fields: list[Field], indent: str) -> list[str]:
    out = []
    for f in fields:
        value = f"self.{f.py}"
        if f.required or f.has_default:
            out.append(f'{indent}out["{f.wire}"] = {em.enc(f.type, value)}')
            continue
        out.append(f"{indent}if {value} is not UNSET:")
        out.append(f'{indent}    out["{f.wire}"] = {em.enc(f.type, value)}')
    return out


def decode_arg(em: Emit, f: Field) -> str:
    got = f'data["{f.wire}"]'
    expr = em.dec(f.type, got)
    if f.required:
        return f"{f.py}={expr}"
    if f.has_default:
        lit = em.default_literal(f)
        fallback = f"{lit}()" if is_factory(lit) else lit
        return f'{f.py}={expr} if "{f.wire}" in data else {fallback}'
    # Left out reads as UNSET and null as None, so a value read and written
    # again is the same JSON (for `cad.entities.set`, null means "remove").
    if expr == got:
        return f'{f.py}=data.get("{f.wire}", UNSET)'
    if isinstance(f.type, Nullable):
        inner = em.dec(f.type.inner, got)
        return f'{f.py}=UNSET if "{f.wire}" not in data else None if {got} is None else {inner}'
    return f'{f.py}={expr} if "{f.wire}" in data else UNSET'


def attributes_doc(fields: list[Field]) -> str:
    rows = [f for f in fields if f.description]
    if not rows:
        return ""
    out = ["", "Attributes:"]
    for f in rows:
        text = doc_text(f.description).split("\n")
        out.append(f"    {f.py}: {text[0]}")
        out.extend(f"        {line}" if line.strip() else "" for line in text[1:])
    return "\n".join(out)


def emit_struct(em: Emit, name: str, description: str, fields: list[Field], bases: str,
                tag: tuple[str, str] | None, self_typed: bool = False) -> str:
    doc = doc_text(description) + attributes_doc(fields)
    lines = ["@dataclass(kw_only=True, slots=True)", f"class {name}({bases}):"]
    body = docstring(doc, "    ")
    if body:
        lines.append(body.rstrip("\n"))
    if tag:
        lines.append(f'    TAG_VALUE: ClassVar[str] = "{tag[1]}"')
    for f in fields:
        lines.append(f"    {field_decl(em, f)}")
    if not fields and not body and not tag:
        lines.append("    pass")
    lines.append("")
    lines.append("    def to_json(self) -> dict[str, Any]:")
    if tag:
        lines.append(f'        out: dict[str, Any] = {{"{tag[0]}": "{tag[1]}"}}')
    else:
        lines.append("        out: dict[str, Any] = {}")
    lines.extend(encode_lines(em, fields, "        "))
    lines.append("        return out")
    lines.append("")
    lines.append("    @classmethod")
    if self_typed:
        # Its variants (PolylineEntity over PathEntity) read as themselves.
        lines.append(f"    def from_json(cls: type[_{name}T], data: Mapping[str, Any]) -> _{name}T:")
    else:
        lines.append(f"    def from_json(cls, data: Mapping[str, Any]) -> {name}:")
    if fields:
        lines.append("        return cls(")
        for f in fields:
            lines.append(f"            {decode_arg(em, f)},")
        lines.append("        )")
    else:
        lines.append("        return cls()")
    return "\n".join(lines) + "\n"


def emit_enum(e: Enum) -> str:
    doc = doc_text(e.description)
    rows = [f"- ``{v}``: {doc_text(d).splitlines()[0]}" if d else f"- ``{v}``" for v, d in e.members]
    if any(d for _, d in e.members):
        doc = (doc + "\n\n" if doc else "") + "\n".join(rows)
    lines = [f"class {e.name}(_StrEnum):"]
    body = docstring(doc, "    ")
    if body:
        lines.append(body.rstrip("\n"))
    names = set()
    for value, _ in e.members:
        n = member(value)
        if n in names:
            raise Fail(f"{e.name}: two members named {n}")
        names.add(n)
        lines.append(f"    {n} = {q(value)}")
    lines.append("")
    lines.append("")
    literal = ", ".join(q(v) for v, _ in e.members)
    lines.append(f"{e.name}Name = Literal[{literal}]")
    lines.append(f'"""The names of :class:`{e.name}`, for a plain string."""')
    return "\n".join(lines) + "\n"


def common_fields(em: Emit, model: Model, u: Union) -> list[tuple[str, str]]:
    """The fields every variant of `u` has, with one type: a type checker
    then reads `entity.layer_id` on any Entity."""
    shared: dict[str, str] | None = None
    for v in u.variants:
        fields = model.structs[v.base_struct].fields if v.base_struct else v.fields
        mine = {f.py: field_hint(em, f) for f in fields}
        shared = mine if shared is None else {k: t for k, t in shared.items() if mine.get(k) == t}
    return sorted((shared or {}).items())


def field_hint(em: Emit, f: Field) -> str:
    hint = em.hint(f.type)
    return hint if f.required or f.has_default else f"{hint} | Unset"


def emit_union_base(u: Union, common: list[tuple[str, str]]) -> str:
    doc = doc_text(u.description)
    variants = "\n".join(f"- :class:`{v.cls}` (``{u.tag}: {v.value}``)" for v in u.variants)
    doc = (doc + "\n\n" if doc else "") + "One of:\n\n" + variants
    lines = [f"class {u.name}(_Union):", docstring(doc, "    ").rstrip("\n")]
    lines.append("    __slots__ = ()")
    lines.append(f'    TAG: ClassVar[str] = "{u.tag}"')
    if common:
        lines.append("")
        lines.append("    if TYPE_CHECKING:")
        lines.append("        # Every variant has these.")
        lines.extend(f"        {name}: {hint}" for name, hint in common)
    if u.tag.isidentifier() and not keyword.iskeyword(u.tag):
        lines.append("")
        lines.append("    @property")
        lines.append(f"    def {snake(u.tag)}(self) -> str:")
        lines.append(f'        """The name of the variant (``{u.tag}`` on the wire)."""')
        lines.append("        return self.TAG_VALUE")
    lines.append("")
    lines.append("    @classmethod")
    lines.append(f"    def from_json(cls, data: Mapping[str, Any]) -> {u.name}:")
    lines.append(f'        return _variant(_{snake(u.name).upper()}, "{u.name}", "{u.tag}", data).from_json(data)')
    return "\n".join(lines) + "\n"


def emit_types(model: Model) -> str:
    em = Emit(model)
    parts = [HEADER, TYPES_PRELUDE]
    # Enums first, then the plain values' names, then union bases, then structs, then the variants.
    for name in sorted(model.enums):
        parts.append("\n\n" + emit_enum(model.enums[name]))
    for name in sorted(model.aliases):
        description, hint = model.aliases[name]
        doc = f"#: {description}\n" if description else ""
        parts.append(f"\n\n{doc}{name} = Union[{', '.join(h.strip() for h in hint.split('|'))}]\n")
    for name in sorted(model.unions):
        u = model.unions[name]
        parts.append("\n\n" + emit_union_base(u, common_fields(em, model, u)))
    derived = sorted({v.base_struct for u in model.unions.values() for v in u.variants
                      if v.base_struct and v.cls != v.base_struct})
    for name in derived:
        parts.append(f'\n\n_{name}T = TypeVar("_{name}T", bound="{name}")\n')
    for name in sorted(model.structs):
        if name == "Vec2":
            parts.append("\n\n" + VEC2)
            continue
        s = model.structs[name]
        bases = s.variant_of[0] if s.variant_of else "_Model"
        tag = (s.variant_of[1], s.variant_of[2]) if s.variant_of else None
        parts.append("\n\n" + emit_struct(em, name, s.description, s.fields, bases, tag, name in derived))
    for name in sorted(model.unions):
        u = model.unions[name]
        for v in u.variants:
            if v.base_struct and v.cls == v.base_struct:
                continue
            if v.base_struct:
                parts.append("\n\n" + emit_struct_variant(u, v, model.structs[v.base_struct]))
            else:
                parts.append("\n\n" + emit_struct(em, v.cls, v.description, v.fields, u.name, (u.tag, v.value)))
    for name in sorted(model.unions):
        u = model.unions[name]
        rows = ", ".join(f'"{v.value}": {v.cls}' for v in u.variants)
        parts.append(f"\n\n_{snake(u.name).upper()}: dict[str, type[{u.name}]] = {{{rows}}}\n")
    names = type_names(model)
    parts.append("\n\n__all__ = [\n" + "".join(f'    "{n}",\n' for n in names) + "]\n")
    return "".join(parts)


def emit_struct_variant(u: Union, v: Variant, base: Struct) -> str:
    doc = doc_text(v.description) or f"{u.name} ``{v.value}``: a :class:`{base.name}`."
    lines = [
        "@dataclass(kw_only=True, slots=True)",
        f"class {v.cls}({base.name}, {u.name}):",
        docstring(doc, "    ").rstrip("\n"),
        f'    TAG_VALUE: ClassVar[str] = "{v.value}"',
        "",
        "    def to_json(self) -> dict[str, Any]:",
        f'        return {{"{u.tag}": "{v.value}", **{base.name}.to_json(self)}}',
    ]
    return "\n".join(lines) + "\n"


TYPES_PRELUDE = '''"""Every type of the command catalog: the inputs, outputs and plans of
every product command and what they are made of.

Each class writes its JSON with ``to_json()`` and reads it with
``from_json()``, in the catalog's own wire form (camelCase names); what is
read and written again is the same JSON. An optional field left out is
:data:`UNSET` (falsy) and is not sent; ``None`` is null, which for most
fields means the same, and for a few (``color``, ``symbol``, ``label`` of
``cad.entities.set``) means "remove it".
Coordinates are x east (Y), y north (X), in the project's units (m).
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, ClassVar, Literal, NamedTuple, TypeVar, Union

from ._runtime import (
    UNSET,
    Unset,
    _enum_in,
    _StrEnum,
    _enum_out,
    _Model,
    _Union,
    _variant,
    _vec2_out,
)

Vec2Like = Union["Vec2", "tuple[float, float]", "Sequence[float]"]
"""A point: :class:`Vec2`, or a pair ``(x, y)``: x east (Y), y north (X)."""
'''

VEC2 = '''class Vec2(NamedTuple):
    """A point in world units: x = east (Y, sağa), y = north (X, yukarı)."""

    x: float
    y: float

    @classmethod
    def of(cls, value: Vec2Like) -> Vec2:
        """A point from a :class:`Vec2`, a pair ``(x, y)`` or anything with ``x`` and ``y``."""
        if isinstance(value, Vec2):
            return value
        if hasattr(value, "x") and hasattr(value, "y"):
            return cls(float(value.x), float(value.y))
        x, y = value
        return cls(float(x), float(y))

    def to_json(self) -> dict[str, float]:
        return {"x": float(self.x), "y": float(self.y)}

    @classmethod
    def from_json(cls, data: Mapping[str, Any]) -> Vec2:
        return cls(float(data["x"]), float(data["y"]))
'''


# ---------------------------------------------------------------- wrappers


@dataclass
class Command:
    id: str
    version: int
    title: str
    summary: str
    local: bool
    scope: str  # document, project, tenant
    input: str
    output: str
    plan: str | None
    path: list[str]  # the module path under kentos.cad
    attr: str  # the wrapper's name in its module


def commands_of(catalog: dict) -> list[Command]:
    out = []
    for c in catalog["commands"]:
        parts = c["id"].split(".")
        if parts[0] == "cad":
            parts = parts[1:]
        if len(parts) < 2:
            raise Fail(f"{c['id']}: no namespace under kentos.cad")
        local = any(h in ("web", "desktop") for h in c["hosts"])
        if local:
            scope = "document"
        elif "cloudProject" in c["requires"]:
            scope = "project"
        else:
            scope = "tenant"
        attr = parts[-1] + "_" if keyword.iskeyword(parts[-1]) else parts[-1]
        out.append(
            Command(
                id=c["id"],
                version=c["version"],
                title=c["title"],
                summary=c["summary"],
                local=local,
                scope=scope,
                input=c["input"]["title"],
                output=c["output"]["title"],
                plan=c["plan"]["title"] if "plan" in c else None,
                path=parts[:-1],
                attr=attr,
            )
        )
    return out


def param_decl(em: Emit, f: Field) -> str:
    hint = em.hint(f.type, loose=True)
    if f.required:
        return f"{f.py}: {hint}"
    if f.has_default:
        lit = em.default_literal(f)
        if is_factory(lit):
            return f"{f.py}: {hint} | Unset = UNSET"
        return f"{f.py}: {hint} = {lit}"
    return f"{f.py}: {hint} | Unset = UNSET"


def convert(em: Emit, t, v: str) -> str:
    """A loose parameter as the dataclass field takes it."""
    if isinstance(t, Nullable):
        inner = convert(em, t.inner, v)
        return v if inner == v else f"_opt({v}, lambda x: {convert(em, t.inner, 'x')})"
    if isinstance(t, Ref) and em.m.kind(t.name) == "vec2":
        return f"Vec2.of({v})"
    if isinstance(t, ListT):
        inner = convert(em, t.item, "p")
        return f"list({v})" if inner == "p" else f"[{inner} for p in {v}]"
    if isinstance(t, MapT):
        return f"dict({v})"
    return v


def build_arg(em: Emit, f: Field) -> str:
    """A wrapper's parameter as its input's field: a point from a pair, a
    list from any sequence; UNSET and None go through as they are."""
    t = f.type.inner if isinstance(f.type, Nullable) else f.type
    if f.required and not isinstance(f.type, Nullable):
        return f"{f.py}={convert(em, t, f.py)}"
    conv = convert(em, t, "x")
    if conv == "x":
        return f"{f.py}={f.py}"
    if f.has_default and is_factory(em.default_literal(f)):
        return f"{f.py}={em.default_literal(f)}() if {f.py} is UNSET else _opt({f.py}, lambda x: {conv})"
    return f"{f.py}=_opt({f.py}, lambda x: {conv})"


def args_doc(fields: list[Field], first: tuple[str, str]) -> str:
    out = ["Args:", f"    {first[0]}: {first[1]}"]
    for f in fields:
        text = doc_text(f.description).split("\n") if f.description else [""]
        out.append(f"    {f.py}: {text[0]}".rstrip())
        out.extend(f"        {line}" if line.strip() else "" for line in text[1:])
    return "\n".join(out)


def emit_command(em: Emit, c: Command) -> str:
    s = em.m.structs.get(c.input)
    if s is None:
        raise Fail(f"{c.id}: its input {c.input} is not a struct")
    fields = s.fields
    cls = "_" + "".join(pascal(p) for p in c.path + [c.attr.rstrip("_")])
    if c.local:
        first = ("doc", "Document", "The drawing it works on.")
    elif c.scope == "project":
        first = ("target", "ProjectRef", "The cloud project (``Connection.project``).")
    else:
        first = ("target", "TenantRef", "The organisation or personal space (``Connection.tenant``).")
    if any(f.py == first[0] for f in fields):
        raise Fail(f"{c.id}: an input field is named {first[0]}")
    params = ["self", f"{first[0]}: {first[1]}", "/", "*"] + [param_decl(em, f) for f in fields]
    if not c.local:
        params += ["expected_versions: Mapping[str, str] | None = None", "idempotency_key: str | None = None"]
    sig = ",\n        ".join(params)
    build = "".join(f"\n            {build_arg(em, f)}," for f in fields)
    make = f"{c.input}({build}\n        )" if fields else f"{c.input}()"
    head = wrap(doc_text(f"{c.title}: {c.summary}"))
    arg_doc = args_doc(fields, (first[0], first[2]))
    if not c.local:
        arg_doc += (
            "\n    expected_versions: The versions the change rests on (``@project``,"
            "\n        ``@file``, an object's id), as the server's envelope carries them."
            "\n    idempotency_key: The same key answers a retry with the same result;"
            "\n        a new one is made when none is given."
        )
    lines = []
    base = f"LocalCommand[{c.input}, {c.output}, {c.plan}]" if c.local else f"ServerCommand[{c.input}, {c.output}]"
    lines.append(f"class {cls}({base}):")
    lines.append(docstring(wrap(f"``{c.id}`` v{c.version}. {doc_text(c.title)}: {doc_text(c.summary)}"), "    ").rstrip("\n"))
    lines.append("    __slots__ = ()")
    lines.append(f'    id = "{c.id}"')
    lines.append(f"    version = {c.version}")
    lines.append(f"    title = {q(c.title)}")
    lines.append(f'    scope = "{c.scope}"')
    lines.append(f"    input_type = {c.input}")
    lines.append(f"    output_type = {c.output}")
    if c.local:
        lines.append(f"    plan_type = {c.plan}")
    call_doc = f"{head}\n\n{arg_doc}\n\nReturns:\n    {c.output}"
    if c.local:
        call_doc += (
            "\n\nRaises:\n    CommandFailed, NeedsInput, RevisionConflict: the command's refusal;"
            "\n        nothing was written. Warnings go to :mod:`warnings` as CommandWarning."
        )
    else:
        call_doc += "\n\nRaises:\n    ServerError: the server's refusal (its code, message and field)."
    target = first[0]
    lines.append("")
    lines.append(f"    def __call__(\n        {sig},\n    ) -> {c.output}:")
    lines.append(docstring(call_doc, "        ").rstrip("\n"))
    if c.local:
        lines.append(f"        return self.execute_input({target}, {make})")
    else:
        lines.append(
            f"        return self.execute_input(\n            {target},\n            {make},\n"
            "            expected_versions=expected_versions,\n            idempotency_key=idempotency_key,\n        )"
        )
    if c.local:
        lines.append("")
        lines.append(f"    def plan(\n        {sig},\n    ) -> {c.plan}:")
        lines.append(docstring(
            "What it would write, with nothing written; the plan's ``revision``, given as\n"
            "``expected_revision``, writes exactly this plan or nothing.", "        ").rstrip("\n"))
        lines.append(f"        return self.plan_input({target}, {make})")
        lines.append("")
        lines.append(f"    def validate(\n        {sig},\n    ) -> list[CommandNote]:")
        lines.append(docstring(
            "Checks the input against the drawing, writing nothing; its warnings.\n"
            "A refusal raises as for the call.", "        ").rstrip("\n"))
        lines.append(f"        return self.validate_input({target}, {make})")
    lines.append("")
    lines.append("")
    lines.append(f"{c.attr} = {cls}()")
    lines.append(f'"""{doc_text(c.title)} (``{c.id}``)."""')
    return "\n".join(lines) + "\n"


def module_of(path: list[str]) -> Path:
    """The file of a namespace: a leaf is a module; one with children a package."""
    return OUT.joinpath(*path).with_suffix(".py")


def emit_modules(model: Model, commands: list[Command]) -> dict[Path, str]:
    em = Emit(model)
    by_ns: dict[tuple[str, ...], list[Command]] = {}
    for c in commands:
        by_ns.setdefault(tuple(c.path), []).append(c)
    # Every namespace with children becomes a package.
    parents = {ns[:i] for ns in by_ns for i in range(1, len(ns))}
    files: dict[Path, str] = {}
    for ns in sorted(set(by_ns) | parents):
        cmds = sorted(by_ns.get(ns, []), key=lambda c: c.attr)
        children = sorted({other[len(ns)] for other in set(by_ns) | parents if len(other) > len(ns) and other[: len(ns)] == ns})
        if ns in parents:
            path = OUT.joinpath(*ns) / "__init__.py"
        else:
            path = module_of(list(ns))
        depth = len(ns) + (1 if ns in parents else 0)
        dots = "." * depth
        used: set[str] = set()
        for c in cmds:
            used.update([c.input, c.output] + ([c.plan] if c.plan else []))
        needs_vec2 = any(
            "Vec2." in build_arg(em, f)
            for c in cmds
            for f in model.structs[c.input].fields
        )
        type_names = sorted(used | ({"Vec2", "Vec2Like"} if needs_vec2 else set()) | referenced_hints(em, model, cmds))
        title = ".".join(["kentos", "cad", *ns])
        lines = [HEADER.rstrip("\n")]
        lines.append(f'"""``{title}``: {", ".join("``" + c.id + "``" for c in cmds) or "its namespaces"}."""')
        lines.append("")
        lines.append("from __future__ import annotations")
        lines.append("")
        if cmds:
            lines.append("from collections.abc import Mapping, Sequence  # noqa: F401")
            lines.append("from typing import TYPE_CHECKING, Any  # noqa: F401")
            lines.append("")
            rt = ["UNSET", "CommandNote", "Unset", "_opt"]
            rt.append("LocalCommand" if any(c.local for c in cmds) else "")
            rt.append("ServerCommand" if any(not c.local for c in cmds) else "")
            rt_names = ", ".join(sorted(n for n in rt if n))
            lines.append(f"from {dots}_runtime import {rt_names}  # noqa: F401")
            lines.append(f"from {dots}types import (  # noqa: F401")
            lines.extend(f"    {n}," for n in type_names)
            lines.append(")")
            lines.append("")
            lines.append("if TYPE_CHECKING:")
            if any(c.local for c in cmds):
                lines.append(f"    from {dots}document import Document")
            if any(not c.local for c in cmds):
                lines.append(f"    from {dots}connection import ProjectRef, TenantRef")
        if children:
            lines.append("")
            for ch in children:
                lines.append(f"from . import {ch}")
        for c in cmds:
            lines.append("")
            lines.append("")
            lines.append(emit_command(em, c).rstrip("\n"))
        names = [c.attr for c in cmds] + children
        lines.append("")
        lines.append("")
        lines.append("__all__ = [" + ", ".join(f'"{n}"' for n in sorted(names)) + "]")
        files[path] = "\n".join(lines) + "\n"
    top = sorted({c.path[0] for c in commands})
    index = [HEADER.rstrip("\n"), '"""Every wrapper by its command\'s id (TODOS.md PY-16)."""', "",
             "from __future__ import annotations", "", "from typing import Any", "",
             "from . import " + ", ".join(top), "", "COMMANDS: dict[str, Any] = {"]
    for c in sorted(commands, key=lambda c: c.id):
        index.append(f'    "{c.id}": {".".join(c.path + [c.attr])},')
    index.append("}")
    index.append('"""The command id → its wrapper (``kentos.cad.polygon.create`` …)."""')
    index.append("")
    index.append("NAMESPACES = (" + ", ".join(f'"{n}"' for n in top) + ",)")
    files[OUT / "_index.py"] = "\n".join(index) + "\n"
    return files


def referenced_hints(em: Emit, model: Model, cmds: list[Command]) -> set[str]:
    """The type names the wrappers' parameter hints mention."""
    names: set[str] = set()

    def walk(t) -> None:
        if isinstance(t, Ref):
            k = model.kind(t.name)
            if k == "enum":
                names.update({t.name, t.name + "Name"})
            elif k == "vec2":
                names.update({"Vec2", "Vec2Like"})
            else:
                names.add(t.name)
        elif isinstance(t, (ListT,)):
            walk(t.item)
        elif isinstance(t, MapT):
            walk(t.value)
        elif isinstance(t, Nullable):
            walk(t.inner)

    for c in cmds:
        for f in model.structs[c.input].fields:
            walk(f.type)
            if f.has_default:
                lit = em.default_literal(f)
                if "." in lit:
                    names.add(lit.split(".")[0])
    return names


# ---------------------------------------------------------------- main


def load() -> tuple[dict, dict[str, dict]]:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    schemas: dict[str, dict] = {}

    def put(name: str, body: dict) -> None:
        if name in schemas and schemas[name] != body:
            raise Fail(f"{name}: two different schemas under one name")
        schemas[name] = body

    for c in catalog["commands"]:
        for side in ("input", "output", "plan"):
            s = c.get(side)
            if s is None:
                continue
            for name, d in s.get("$defs", {}).items():
                put(name, d)
            put(s["title"], {k: v for k, v in s.items() if k not in ("$schema", "$defs", "title")})
    return catalog, inline_texts(schemas)


def inline_texts(schemas: dict[str, dict]) -> dict[str, dict]:
    """A named text that is no choice (a block's id: a UUID, docs/adr/0144)
    is a plain `str` in Python: each reference to it becomes the text itself."""
    texts = {n: s for n, s in schemas.items() if s.get("type") == "string" and "enum" not in s}

    def walk(node):
        if isinstance(node, dict):
            ref = node.get("$ref")
            if isinstance(ref, str) and ref_name(ref) in texts:
                rest = {k: walk(v) for k, v in node.items() if k != "$ref"}
                return {**texts[ref_name(ref)], **rest}
            return {k: walk(v) for k, v in node.items()}
        if isinstance(node, list):
            return [walk(v) for v in node]
        return node

    return {n: walk(s) for n, s in schemas.items() if n not in texts}


def exports_of(path: Path) -> list[str]:
    """A hand-written module's literal `__all__`."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "__all__" for t in node.targets):
            return list(ast.literal_eval(node.value))
    raise Fail(f"{path.name}: no literal __all__")


def type_names(model: Model) -> list[str]:
    return sorted(
        list(model.enums)
        + [f"{n}Name" for n in model.enums]
        + list(model.unions)
        + list(model.structs)
        + list(model.aliases)
        + [v.cls for u in model.unions.values() for v in u.variants if v.cls != v.base_struct]
        + ["Vec2Like"]
    )


def emit_init(model: Model, commands: list[Command]) -> str:
    spaces = sorted({c.path[0] for c in commands})
    names = ["COMMANDS", "NAMESPACES", "UNSET", "Unset", "CommandNote", "LocalCommand", "Outcome",
             "ServerCommand", "types", *spaces]
    for module in ("_api", "connection", "document", "errors"):
        names += exports_of(OUT / f"{module}.py")
    names += type_names(model)
    if len(set(names)) != len(names):
        twice = sorted({n for n in names if names.count(n) > 1})
        raise Fail(f"kentos.cad exports a name twice: {twice}")
    rows = "".join(f'    "{n}",\n' for n in sorted(names))
    return (
        HEADER
        + INIT_DOC
        + "\nfrom . import types\n"
        + "from ._api import *  # noqa: F403\n"
        + "from ._index import COMMANDS, NAMESPACES\n"
        + "from ._runtime import UNSET, CommandNote, LocalCommand, Outcome, ServerCommand, Unset\n"
        + "from .connection import *  # noqa: F403\n"
        + "from .document import *  # noqa: F403\n"
        + "from .errors import *  # noqa: F403\n"
        + "from .types import *  # noqa: F403\n\n"
        + f"from . import {', '.join(spaces)}  # noqa: E402  isort: skip\n\n"
        + f"__all__ = [\n{rows}]\n"
    )


INIT_DOC = '''"""``kentos.cad``: KentOS CAD from Python (docs/adr/0131).

- :class:`Document`: a drawing without a window, the desktop's own
  document: ``Document.new(srid=5256)``, ``Document.open("ada.kcad")``.
- The commands, each under its catalog name and typed from the catalog's
  schemas: ``polygon.create(doc, layer_id=…, pts=[(x, y), …])``, with
  ``.plan(…)`` and ``.validate(…)``; ``entities.set``, ``entities.edit`` …
  ``project.*`` run on the server through a :class:`Connection`.
- :mod:`kentos.cad.types`: every input, output and plan type; exported here too.
- :data:`COMMANDS`: every wrapper by its command id; :func:`catalog`: the
  catalog itself, with its schemas and examples.

A refusal raises (:class:`CommandFailed` …) and writes nothing; a warning
goes to :mod:`warnings` (:class:`CommandWarning`). Coordinates are x east
(Y), y north (X), in the project's units (m).
"""
'''


def generate() -> dict[Path, str]:
    catalog, schemas = load()
    model = Model(schemas)
    commands = commands_of(catalog)
    files = {OUT / "types.py": emit_types(model)}
    files.update(emit_modules(model, commands))
    files[OUT / "__init__.py"] = emit_init(model, commands)
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="compare, do not write")
    args = ap.parse_args()
    try:
        files = generate()
    except Fail as e:
        print(f"sdk.py: {e}", file=sys.stderr)
        return 2
    stale = [p for p, text in files.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
    if args.check:
        for p in stale:
            print(f"güncel değil: {p.relative_to(ROOT)}", file=sys.stderr)
        if stale:
            print("python3 scripts/python/sdk.py ile yeniden yazın.", file=sys.stderr)
        return 1 if stale else 0
    for p in stale:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(files[p], encoding="utf-8")
        print(f"yazıldı: {p.relative_to(ROOT)}")
    if not stale:
        print(f"güncel: {len(files)} dosya")
    return 0


if __name__ == "__main__":
    sys.exit(main())
