# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.project``: ``project.archive``, ``project.changes``, ``project.convert``, ``project.create``, ``project.duplicate``, ``project.favorite``, ``project.import``, ``project.invite``, ``project.purge``, ``project.rename``, ``project.restore``, ``project.share``, ``project.trash``, ``project.unarchive``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from .._runtime import CommandNote, ServerCommand, UNSET, Unset, _opt  # noqa: F401
from ..types import (  # noqa: F401
    BlockChange,
    Bounds,
    CommitResult,
    EmptyInput,
    FeatureChange,
    GrantRole,
    GrantRoleName,
    InvitationChange,
    LayerNode,
    ProjectAccessChange,
    ProjectCatalogChange,
    ProjectChanges,
    ProjectConvert,
    ProjectCreate,
    ProjectDuplicate,
    ProjectDuplicated,
    ProjectFavorite,
    ProjectImport,
    ProjectImported,
    ProjectInfo,
    ProjectInvite,
    ProjectPatch,
    ProjectPurge,
    ProjectPurged,
    ProjectRename,
    ProjectSettings,
    ProjectShare,
    ProjectStorage,
    ProjectStorageName,
    ProjectStyles,
    ProjectType,
    ProjectTypeName,
    Vec2,
    Vec2Like,
)

if TYPE_CHECKING:
    from ..connection import ProjectRef, TenantRef

from . import access
from . import checkpoint
from . import file
from . import invitation
from . import metadata


class _ProjectArchive(ServerCommand[EmptyInput, ProjectCatalogChange]):
    """``project.archive`` v1. Projeyi arşivle: Projeyi arşivler: salt okunur olur,
    Arşivlenmişler listesinde durur; açık editörlerin kaydı durur, gönderilmemiş
    değişiklikleri cihazlarında kalır. Paylaşımı değiştirilebilir, kopyası
    oluşturulabilir. project.edit ister; tersi project.unarchive'dır.
    """
    __slots__ = ()
    id = "project.archive"
    version = 1
    title = "Projeyi arşivle"
    scope = "project"
    input_type = EmptyInput
    output_type = ProjectCatalogChange

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectCatalogChange:
        """Projeyi arşivle: Projeyi arşivler: salt okunur olur, Arşivlenmişler listesinde
        durur; açık editörlerin kaydı durur, gönderilmemiş değişiklikleri cihazlarında
        kalır. Paylaşımı değiştirilebilir, kopyası oluşturulabilir. project.edit ister;
        tersi project.unarchive'dır.

        Args:
            target: The cloud project (``Connection.project``).
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectCatalogChange

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            EmptyInput(),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


archive = _ProjectArchive()
"""Projeyi arşivle (``project.archive``)."""


class _ProjectChanges(ServerCommand[ProjectChanges, CommitResult]):
    """``project.changes`` v1. Proje değişiklikleri: Bir bulut projesine nesne ekler,
    değiştirir, siler ve proje bilgisini günceller; hepsi tek işlemde yazılır ya da
    hiçbiri yazılmaz. Her değişen nesnenin ve proje bilgisinin beklenen sürümü zarfın
    expectedVersions alanındadır; biri değişmişse 409 döner, hiçbir şey yazılmaz.
    Nesneler feature.write, proje bilgisi project.edit ister. Aynı idempotency
    anahtarıyla tekrar aynı sonucu verir.
    """
    __slots__ = ()
    id = "project.changes"
    version = 1
    title = "Proje değişiklikleri"
    scope = "project"
    input_type = ProjectChanges
    output_type = CommitResult

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        features: Sequence[FeatureChange],
        blocks: Sequence[BlockChange] | Unset = UNSET,
        project: ProjectPatch | None | Unset = UNSET,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> CommitResult:
        """Proje değişiklikleri: Bir bulut projesine nesne ekler, değiştirir, siler ve proje
        bilgisini günceller; hepsi tek işlemde yazılır ya da hiçbiri yazılmaz. Her değişen
        nesnenin ve proje bilgisinin beklenen sürümü zarfın expectedVersions alanındadır;
        biri değişmişse 409 döner, hiçbir şey yazılmaz. Nesneler feature.write, proje
        bilgisi project.edit ister. Aynı idempotency anahtarıyla tekrar aynı sonucu verir.

        Args:
            target: The cloud project (``Connection.project``).
            features:
            blocks: Block definitions made, replaced or removed (docs/adr/0144 §5), in
                the same commit as the objects: an insert may place a block this
                commit makes, and a block may go with the last insert placing it.
            project:
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            CommitResult

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            ProjectChanges(
            features=list(features),
            blocks=_opt(blocks, lambda x: list(x)),
            project=project,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


changes = _ProjectChanges()
"""Proje değişiklikleri (``project.changes``)."""


class _ProjectConvert(ServerCommand[ProjectConvert, ProjectDuplicated]):
    """``project.convert`` v1. Öbür saklama biçimine dönüştür: Projenin şimdiki hâlinden
    öbür saklama biçiminde yeni bir proje açar; kaynak değişmez. Dosya projesinin en
    yeni revizyonu veritabanı projesine aktarılır (PostGIS'e aktar; nesneler kalıcı
    kimlikleriyle); veritabanı projesinin tek anlık görüntüsü dosya projesinin 1.
    revizyonu olur. Yeni proje çağıranındır. Kaynakta project.download, hedef çalışma
    alanında proje açma hakkı ister.
    """
    __slots__ = ()
    id = "project.convert"
    version = 1
    title = "Öbür saklama biçimine dönüştür"
    scope = "project"
    input_type = ProjectConvert
    output_type = ProjectDuplicated

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        to: ProjectStorage | ProjectStorageName,
        name: str | None | Unset = UNSET,
        tenant_id: str | None | Unset = UNSET,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectDuplicated:
        """Öbür saklama biçimine dönüştür: Projenin şimdiki hâlinden öbür saklama biçiminde
        yeni bir proje açar; kaynak değişmez. Dosya projesinin en yeni revizyonu veritabanı
        projesine aktarılır (PostGIS'e aktar; nesneler kalıcı kimlikleriyle); veritabanı
        projesinin tek anlık görüntüsü dosya projesinin 1. revizyonu olur. Yeni proje
        çağıranındır. Kaynakta project.download, hedef çalışma alanında proje açma hakkı
        ister.

        Args:
            target: The cloud project (``Connection.project``).
            to:
            name: The new project's name; the source's with the mode after it when absent.
            tenant_id: The workspace of the new project; the source's when absent.
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectDuplicated

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            ProjectConvert(
            to=to,
            name=name,
            tenant_id=tenant_id,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


convert = _ProjectConvert()
"""Öbür saklama biçimine dönüştür (``project.convert``)."""


class _ProjectCreate(ServerCommand[ProjectCreate, ProjectInfo]):
    """``project.create`` v1. Proje oluştur: Bir çalışma alanında (kişisel alan ya da
    kurum) boş bir bulut projesi açar: adı, ayarları, katman ağacı ve stilleriyle;
    isteğe bağlı açıklama, tür ve etiketlerle. Proje açanındır; başkaları paylaşımla
    eklenir. Çalışma alanında project.create hakkı ister (kurumda proje yöneticisi ve
    üstü); projeye bağlı bir izin istemez. Zarfın tenantId'si çalışma alanıdır,
    projectId boş kalır. Aynı idempotency anahtarıyla tekrar aynı projeyi verir.
    """
    __slots__ = ()
    id = "project.create"
    version = 1
    title = "Proje oluştur"
    scope = "tenant"
    input_type = ProjectCreate
    output_type = ProjectInfo

    def __call__(
        self,
        target: TenantRef,
        /,
        *,
        name: str,
        settings: ProjectSettings,
        origin: Vec2Like,
        layers: Sequence[LayerNode],
        active_layer: str,
        styles: ProjectStyles,
        description: str | None | Unset = UNSET,
        home_view: Bounds | None | Unset = UNSET,
        project_type: ProjectType | ProjectTypeName | None | Unset = UNSET,
        storage: ProjectStorage | ProjectStorageName | None | Unset = UNSET,
        tags: Sequence[str] | None | Unset = UNSET,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectInfo:
        """Proje oluştur: Bir çalışma alanında (kişisel alan ya da kurum) boş bir bulut projesi
        açar: adı, ayarları, katman ağacı ve stilleriyle; isteğe bağlı açıklama, tür ve
        etiketlerle. Proje açanındır; başkaları paylaşımla eklenir. Çalışma alanında
        project.create hakkı ister (kurumda proje yöneticisi ve üstü); projeye bağlı bir
        izin istemez. Zarfın tenantId'si çalışma alanıdır, projectId boş kalır. Aynı
        idempotency anahtarıyla tekrar aynı projeyi verir.

        Args:
            target: The organisation or personal space (``Connection.tenant``).
            name:
            settings:
            origin:
            layers:
            active_layer:
            styles:
            description: The catalog's description (docs/adr/0028); absent: none.
            home_view:
            project_type: Absent: the general type (`cad`).
            storage: How the project is kept, for good (docs/adr/0031); absent: object by
                object in PostGIS (`database`). A `file` project gets its content
                from its first committed revision.
            tags:
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectInfo

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            ProjectCreate(
            name=name,
            settings=settings,
            origin=Vec2.of(origin),
            layers=list(layers),
            active_layer=active_layer,
            styles=styles,
            description=description,
            home_view=home_view,
            project_type=project_type,
            storage=storage,
            tags=_opt(tags, lambda x: list(x)),
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


create = _ProjectCreate()
"""Proje oluştur (``project.create``)."""


class _ProjectDuplicate(ServerCommand[ProjectDuplicate, ProjectDuplicated]):
    """``project.duplicate`` v1. Projenin kopyasını oluştur: Projeyi yeni kimlikli yeni bir
    projeye kopyalar: ayarlar, katman ağacı, stiller, açıklama, tür, etiketler ve bütün
    nesneler; her nesne kalıcı kimliğini korur. Geçmiş (komut günlüğü, olaylar, denetim
    kayıtları), paylaşımlar, favoriler ve arşiv durumu kopyalanmaz; kopya çağıranındır
    ve yalnız onun (ve kurum politikasının) erişimindedir. Kaynakta project.download,
    kopyanın gideceği çalışma alanında project.create ister. Çöp kutusundaki proje
    kopyalanamaz.
    """
    __slots__ = ()
    id = "project.duplicate"
    version = 1
    title = "Projenin kopyasını oluştur"
    scope = "project"
    input_type = ProjectDuplicate
    output_type = ProjectDuplicated

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        name: str | None | Unset = UNSET,
        tenant_id: str | None | Unset = UNSET,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectDuplicated:
        """Projenin kopyasını oluştur: Projeyi yeni kimlikli yeni bir projeye kopyalar:
        ayarlar, katman ağacı, stiller, açıklama, tür, etiketler ve bütün nesneler; her
        nesne kalıcı kimliğini korur. Geçmiş (komut günlüğü, olaylar, denetim kayıtları),
        paylaşımlar, favoriler ve arşiv durumu kopyalanmaz; kopya çağıranındır ve yalnız
        onun (ve kurum politikasının) erişimindedir. Kaynakta project.download, kopyanın
        gideceği çalışma alanında project.create ister. Çöp kutusundaki proje kopyalanamaz.

        Args:
            target: The cloud project (``Connection.project``).
            name: The copy's name; absent: the source's with " (kopya)".
            tenant_id: The workspace the copy goes to; absent: the source's.
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectDuplicated

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            ProjectDuplicate(
            name=name,
            tenant_id=tenant_id,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


duplicate = _ProjectDuplicate()
"""Projenin kopyasını oluştur (``project.duplicate``)."""


class _ProjectFavorite(ServerCommand[ProjectFavorite, ProjectCatalogChange]):
    """``project.favorite`` v1. Favorilere ekle ya da çıkar: Projeyi çağıranın favorilerine
    ekler (favorite: true) ya da çıkarır; yalnız o kişinin listesini değiştirir, projeye
    ve başkalarına dokunmaz. project.read ister.
    """
    __slots__ = ()
    id = "project.favorite"
    version = 1
    title = "Favorilere ekle ya da çıkar"
    scope = "project"
    input_type = ProjectFavorite
    output_type = ProjectCatalogChange

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        favorite: bool,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectCatalogChange:
        """Favorilere ekle ya da çıkar: Projeyi çağıranın favorilerine ekler (favorite: true)
        ya da çıkarır; yalnız o kişinin listesini değiştirir, projeye ve başkalarına
        dokunmaz. project.read ister.

        Args:
            target: The cloud project (``Connection.project``).
            favorite: Add to the caller's favourites (true) or take it out (false).
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectCatalogChange

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            ProjectFavorite(
            favorite=favorite,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


favorite = _ProjectFavorite()
"""Favorilere ekle ya da çıkar (``project.favorite``)."""


class _ProjectImport(ServerCommand[ProjectImport, ProjectImported]):
    """``project.import`` v1. Dosyayı projeye aktar: Doğrulanmış bir .kcad yüklemesini
    (POST …/uploads, PUT …/uploads/{yükleme}) henüz kaydı olmayan bir veritabanı
    projesine tek işlemde aktarır: dosyanın ayarları, katmanları, stilleri ve her nesne
    kalıcı kimliğiyle. Sunucunun almadığı ilk nesne bütün dosyayı yerini söyleyerek
    reddeder; o zaman hiçbir şey yazılmaz. feature.write ve project.edit ister.
    """
    __slots__ = ()
    id = "project.import"
    version = 1
    title = "Dosyayı projeye aktar"
    scope = "project"
    input_type = ProjectImport
    output_type = ProjectImported

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        upload_id: str,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectImported:
        """Dosyayı projeye aktar: Doğrulanmış bir .kcad yüklemesini (POST …/uploads, PUT
        …/uploads/{yükleme}) henüz kaydı olmayan bir veritabanı projesine tek işlemde
        aktarır: dosyanın ayarları, katmanları, stilleri ve her nesne kalıcı kimliğiyle.
        Sunucunun almadığı ilk nesne bütün dosyayı yerini söyleyerek reddeder; o zaman
        hiçbir şey yazılmaz. feature.write ve project.edit ister.

        Args:
            target: The cloud project (``Connection.project``).
            upload_id:
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectImported

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            ProjectImport(
            upload_id=upload_id,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


import_ = _ProjectImport()
"""Dosyayı projeye aktar (``project.import``)."""


class _ProjectInvite(ServerCommand[ProjectInvite, InvitationChange]):
    """``project.invite`` v1. Projeye davet et: Bir e-posta adresine projeye davet
    bağlantısı açar: rol en çok düzenleyici, bitiş verilmezse 14 gün, en çok 90 gün.
    Belirteç yalnız ilk yanıtta döner; bağlantıyı davet eden iletir. Aynı adrese
    bekleyen davet yenisiyle değişir. Daveti yalnız o adresin doğrulanmış hesabı kabul
    eder; kurum dışından biri misafir olur. project.share ister.
    """
    __slots__ = ()
    id = "project.invite"
    version = 1
    title = "Projeye davet et"
    scope = "project"
    input_type = ProjectInvite
    output_type = InvitationChange

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        email: str,
        role: GrantRole | GrantRoleName,
        expires_at: str | None | Unset = UNSET,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> InvitationChange:
        """Projeye davet et: Bir e-posta adresine projeye davet bağlantısı açar: rol en çok
        düzenleyici, bitiş verilmezse 14 gün, en çok 90 gün. Belirteç yalnız ilk yanıtta
        döner; bağlantıyı davet eden iletir. Aynı adrese bekleyen davet yenisiyle değişir.
        Daveti yalnız o adresin doğrulanmış hesabı kabul eder; kurum dışından biri misafir
        olur. project.share ister.

        Args:
            target: The cloud project (``Connection.project``).
            email: The invited person's e-mail; kept in lower case.
            role: Viewer, commenter or editor: managing and sharing stay with members.
            expires_at: When it stops waiting (RFC 3339); [`INVITATION_DAYS`] from now when
                absent, at most [`INVITATION_MAX_DAYS`].
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            InvitationChange

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            ProjectInvite(
            email=email,
            role=role,
            expires_at=expires_at,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


invite = _ProjectInvite()
"""Projeye davet et (``project.invite``)."""


class _ProjectPurge(ServerCommand[ProjectPurge, ProjectPurged]):
    """``project.purge`` v1. Projeyi kalıcı olarak sil: Çöp kutusundaki projeyi nesneleri,
    paylaşımları, komut günlüğü ve olaylarıyla birlikte kalıcı olarak siler; geri
    alınamaz, denetim kaydı kalır. Açık onay ister: confirmName projenin şimdiki adıyla
    aynı olmalıdır. Önce çöp kutusuna taşınmamış proje silinmez. project.delete ister.
    Önceden indirilmiş kopyalar ve sunucu yedekleri bu komutla silinmez.
    """
    __slots__ = ()
    id = "project.purge"
    version = 1
    title = "Projeyi kalıcı olarak sil"
    scope = "project"
    input_type = ProjectPurge
    output_type = ProjectPurged

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        confirm_name: str,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectPurged:
        """Projeyi kalıcı olarak sil: Çöp kutusundaki projeyi nesneleri, paylaşımları, komut
        günlüğü ve olaylarıyla birlikte kalıcı olarak siler; geri alınamaz, denetim kaydı
        kalır. Açık onay ister: confirmName projenin şimdiki adıyla aynı olmalıdır. Önce çöp
        kutusuna taşınmamış proje silinmez. project.delete ister. Önceden indirilmiş
        kopyalar ve sunucu yedekleri bu komutla silinmez.

        Args:
            target: The cloud project (``Connection.project``).
            confirm_name: The project's name now, exactly: the caller names what goes.
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectPurged

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            ProjectPurge(
            confirm_name=confirm_name,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


purge = _ProjectPurge()
"""Projeyi kalıcı olarak sil (``project.purge``)."""


class _ProjectRename(ServerCommand[ProjectRename, ProjectCatalogChange]):
    """``project.rename`` v1. Projeyi yeniden adlandır: Projenin adını erişimi olan herkes
    için değiştirir; açık editörler yeni adı hemen görür. project.edit ister.
    Arşivlenmiş ya da çöp kutusundaki proje yeniden adlandırılamaz.
    expectedVersions["@catalog"] verilmişse ve proje bilgileri o sürümde değilse hiçbir
    şey yazılmaz (409).
    """
    __slots__ = ()
    id = "project.rename"
    version = 1
    title = "Projeyi yeniden adlandır"
    scope = "project"
    input_type = ProjectRename
    output_type = ProjectCatalogChange

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        name: str,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectCatalogChange:
        """Projeyi yeniden adlandır: Projenin adını erişimi olan herkes için değiştirir; açık
        editörler yeni adı hemen görür. project.edit ister. Arşivlenmiş ya da çöp
        kutusundaki proje yeniden adlandırılamaz. expectedVersions["@catalog"] verilmişse ve
        proje bilgileri o sürümde değilse hiçbir şey yazılmaz (409).

        Args:
            target: The cloud project (``Connection.project``).
            name: Not empty, at most 200 bytes; surrounding spaces are dropped.
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectCatalogChange

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            ProjectRename(
            name=name,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


rename = _ProjectRename()
"""Projeyi yeniden adlandır (``project.rename``)."""


class _ProjectRestore(ServerCommand[EmptyInput, ProjectCatalogChange]):
    """``project.restore`` v1. Projeyi çöp kutusundan geri yükle: Çöp kutusundaki projeyi
    her şeyiyle geri getirir: listelerde görünür ve açılır; arşivlenmişse arşivde kalır.
    project.delete ister; tersi project.trash'tir.
    """
    __slots__ = ()
    id = "project.restore"
    version = 1
    title = "Projeyi çöp kutusundan geri yükle"
    scope = "project"
    input_type = EmptyInput
    output_type = ProjectCatalogChange

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectCatalogChange:
        """Projeyi çöp kutusundan geri yükle: Çöp kutusundaki projeyi her şeyiyle geri getirir:
        listelerde görünür ve açılır; arşivlenmişse arşivde kalır. project.delete ister;
        tersi project.trash'tir.

        Args:
            target: The cloud project (``Connection.project``).
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectCatalogChange

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            EmptyInput(),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


restore = _ProjectRestore()
"""Projeyi çöp kutusundan geri yükle (``project.restore``)."""


class _ProjectShare(ServerCommand[ProjectShare, ProjectAccessChange]):
    """``project.share`` v1. Projeyi paylaş: Bir kişiye projede rol verir ya da rolünü
    değiştirir: görüntüleyici, yorumcu, düzenleyici ya da yönetici; istenirse bir bitiş
    zamanıyla. Kurum projesinde kişi kurumun üyesi olmalıdır. project.share ister;
    değişiklik denetime ve projenin olay günlüğüne yazılır.
    """
    __slots__ = ()
    id = "project.share"
    version = 1
    title = "Projeyi paylaş"
    scope = "project"
    input_type = ProjectShare
    output_type = ProjectAccessChange

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        user_id: str,
        role: GrantRole | GrantRoleName,
        expires_at: str | None | Unset = UNSET,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectAccessChange:
        """Projeyi paylaş: Bir kişiye projede rol verir ya da rolünü değiştirir: görüntüleyici,
        yorumcu, düzenleyici ya da yönetici; istenirse bir bitiş zamanıyla. Kurum projesinde
        kişi kurumun üyesi olmalıdır. project.share ister; değişiklik denetime ve projenin
        olay günlüğüne yazılır.

        Args:
            target: The cloud project (``Connection.project``).
            user_id: The account id (`UserView.id`).
            role:
            expires_at: RFC 3339; the grant ends by itself then. Absent: until revoked.
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectAccessChange

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            ProjectShare(
            user_id=user_id,
            role=role,
            expires_at=expires_at,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


share = _ProjectShare()
"""Projeyi paylaş (``project.share``)."""


class _ProjectTrash(ServerCommand[EmptyInput, ProjectCatalogChange]):
    """``project.trash`` v1. Projeyi çöp kutusuna taşı: Projeyi erişimi olan herkes için
    çöp kutusuna taşır: listelerden kalkar, açılamaz ve değiştirilemez (410); açık
    editörlerin kaydı durur. Hiçbir şey silinmez: proje sahibi ya da kurum yöneticisi
    saklama süresi dolana kadar geri yükleyebilir, sonra proje kalıcı olarak silinir.
    project.delete ister (proje sahibi; kurum politikası açıksa kurum sahibi ve
    yöneticisi); tersi project.restore'dur.
    """
    __slots__ = ()
    id = "project.trash"
    version = 1
    title = "Projeyi çöp kutusuna taşı"
    scope = "project"
    input_type = EmptyInput
    output_type = ProjectCatalogChange

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectCatalogChange:
        """Projeyi çöp kutusuna taşı: Projeyi erişimi olan herkes için çöp kutusuna taşır:
        listelerden kalkar, açılamaz ve değiştirilemez (410); açık editörlerin kaydı durur.
        Hiçbir şey silinmez: proje sahibi ya da kurum yöneticisi saklama süresi dolana kadar
        geri yükleyebilir, sonra proje kalıcı olarak silinir. project.delete ister (proje
        sahibi; kurum politikası açıksa kurum sahibi ve yöneticisi); tersi
        project.restore'dur.

        Args:
            target: The cloud project (``Connection.project``).
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectCatalogChange

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            EmptyInput(),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


trash = _ProjectTrash()
"""Projeyi çöp kutusuna taşı (``project.trash``)."""


class _ProjectUnarchive(ServerCommand[EmptyInput, ProjectCatalogChange]):
    """``project.unarchive`` v1. Projeyi arşivden çıkar: Arşivlenmiş projeyi yeniden
    düzenlenebilir yapar. Açık tutanlar projeyi yeniden açınca kaydetmeye başlar;
    cihazlarında saklanan değişiklikler geri gelir. project.edit ister; tersi
    project.archive'dır.
    """
    __slots__ = ()
    id = "project.unarchive"
    version = 1
    title = "Projeyi arşivden çıkar"
    scope = "project"
    input_type = EmptyInput
    output_type = ProjectCatalogChange

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectCatalogChange:
        """Projeyi arşivden çıkar: Arşivlenmiş projeyi yeniden düzenlenebilir yapar. Açık
        tutanlar projeyi yeniden açınca kaydetmeye başlar; cihazlarında saklanan
        değişiklikler geri gelir. project.edit ister; tersi project.archive'dır.

        Args:
            target: The cloud project (``Connection.project``).
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectCatalogChange

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            EmptyInput(),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


unarchive = _ProjectUnarchive()
"""Projeyi arşivden çıkar (``project.unarchive``)."""


__all__ = ["access", "archive", "changes", "checkpoint", "convert", "create", "duplicate", "favorite", "file", "import_", "invitation", "invite", "metadata", "purge", "rename", "restore", "share", "trash", "unarchive"]
