# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.project.access``: ``project.access.revoke``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from .._runtime import CommandNote, ServerCommand, UNSET, Unset, _opt  # noqa: F401
from ..types import (  # noqa: F401
    ProjectAccessChange,
    ProjectAccessRevoke,
)

if TYPE_CHECKING:
    from ..connection import ProjectRef, TenantRef


class _ProjectAccessRevoke(ServerCommand[ProjectAccessRevoke, ProjectAccessChange]):
    """``project.access.revoke`` v1. Proje erişimini kaldır: Bir kişinin projedeki
    paylaşımını kaldırır; açık bağlantıları kapanır ve sonraki istekleri reddedilir.
    Önceden indirilmiş kopyalar geri alınamaz. project.share ister.
    """
    __slots__ = ()
    id = "project.access.revoke"
    version = 1
    title = "Proje erişimini kaldır"
    scope = "project"
    input_type = ProjectAccessRevoke
    output_type = ProjectAccessChange

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        user_id: str,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectAccessChange:
        """Proje erişimini kaldır: Bir kişinin projedeki paylaşımını kaldırır; açık
        bağlantıları kapanır ve sonraki istekleri reddedilir. Önceden indirilmiş kopyalar
        geri alınamaz. project.share ister.

        Args:
            target: The cloud project (``Connection.project``).
            user_id:
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectAccessChange

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            ProjectAccessRevoke(
            user_id=user_id,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


revoke = _ProjectAccessRevoke()
"""Proje erişimini kaldır (``project.access.revoke``)."""


__all__ = ["revoke"]
