# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.project.checkpoint``: ``project.checkpoint.create``, ``project.checkpoint.delete``, ``project.checkpoint.restore``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from .._runtime import CommandNote, ServerCommand, UNSET, Unset, _opt  # noqa: F401
from ..types import (  # noqa: F401
    CheckpointChange,
    CheckpointCreate,
    CheckpointDelete,
    CheckpointRestore,
    ProjectDuplicated,
)

if TYPE_CHECKING:
    from ..connection import ProjectRef, TenantRef


class _ProjectCheckpointCreate(ServerCommand[CheckpointCreate, CheckpointChange]):
    """``project.checkpoint.create`` v1. Kontrol noktası oluştur: Projenin şimdiki hâline
    ad verir. Veritabanı projesinde o anın tek revizyonlu .kcad görüntüsü nesne
    deposunda saklanır; dosya projesinde bir revizyon (verilmezse en yenisi)
    adlandırılır, bir şey kopyalanmaz. feature.write ister; arşivdeki ya da çöpteki
    projede alınmaz.
    """
    __slots__ = ()
    id = "project.checkpoint.create"
    version = 1
    title = "Kontrol noktası oluştur"
    scope = "project"
    input_type = CheckpointCreate
    output_type = CheckpointChange

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        name: str,
        file_revision: str | None | Unset = UNSET,
        note: str | None | Unset = UNSET,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> CheckpointChange:
        """Kontrol noktası oluştur: Projenin şimdiki hâline ad verir. Veritabanı projesinde o
        anın tek revizyonlu .kcad görüntüsü nesne deposunda saklanır; dosya projesinde bir
        revizyon (verilmezse en yenisi) adlandırılır, bir şey kopyalanmaz. feature.write
        ister; arşivdeki ya da çöpteki projede alınmaz.

        Args:
            target: The cloud project (``Connection.project``).
            name: 1 to [`CHECKPOINT_NAME_MAX`] characters, e.g. "Belediyeye teslim".
            file_revision: A file project's revision to name (decimal text); its newest when
                absent. A database project takes none: its checkpoint is its present state.
            note: At most [`CHECKPOINT_NOTE_MAX`] characters.
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            CheckpointChange

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            CheckpointCreate(
            name=name,
            file_revision=file_revision,
            note=note,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


create = _ProjectCheckpointCreate()
"""Kontrol noktası oluştur (``project.checkpoint.create``)."""


class _ProjectCheckpointDelete(ServerCommand[CheckpointDelete, CheckpointChange]):
    """``project.checkpoint.delete`` v1. Kontrol noktasını sil: Bir kontrol noktasını
    kaldırır: veritabanı projesinde saklanan görüntüsü de gider; dosya projesinde
    adlandırdığı revizyon kalır. Kontrol noktasını oluşturan kişi (feature.write ile) ya
    da project.edit sahibi siler.
    """
    __slots__ = ()
    id = "project.checkpoint.delete"
    version = 1
    title = "Kontrol noktasını sil"
    scope = "project"
    input_type = CheckpointDelete
    output_type = CheckpointChange

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        checkpoint_id: str,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> CheckpointChange:
        """Kontrol noktasını sil: Bir kontrol noktasını kaldırır: veritabanı projesinde
        saklanan görüntüsü de gider; dosya projesinde adlandırdığı revizyon kalır. Kontrol
        noktasını oluşturan kişi (feature.write ile) ya da project.edit sahibi siler.

        Args:
            target: The cloud project (``Connection.project``).
            checkpoint_id:
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            CheckpointChange

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            CheckpointDelete(
            checkpoint_id=checkpoint_id,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


delete = _ProjectCheckpointDelete()
"""Kontrol noktasını sil (``project.checkpoint.delete``)."""


class _ProjectCheckpointRestore(ServerCommand[CheckpointRestore, ProjectDuplicated]):
    """``project.checkpoint.restore`` v1. Yeni proje olarak geri yükle: Bir kontrol
    noktasından ya da dosya projesinin bir revizyonundan yeni bir proje açar; kaynak
    proje değişmez. Dosya projesinin noktası, o revizyonla başlayan bir dosya projesi
    olur; veritabanı projesinin kontrol noktası, dosyasından içe aktarılan bir
    veritabanı projesi olur (nesneler kalıcı kimlikleriyle). Yeni proje çağıranındır;
    geçmiş ve paylaşımlar gelmez. Kaynakta project.history ve project.download, hedef
    çalışma alanında proje açma hakkı ister.
    """
    __slots__ = ()
    id = "project.checkpoint.restore"
    version = 1
    title = "Yeni proje olarak geri yükle"
    scope = "project"
    input_type = CheckpointRestore
    output_type = ProjectDuplicated

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        checkpoint_id: str | None | Unset = UNSET,
        file_revision: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        tenant_id: str | None | Unset = UNSET,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectDuplicated:
        """Yeni proje olarak geri yükle: Bir kontrol noktasından ya da dosya projesinin bir
        revizyonundan yeni bir proje açar; kaynak proje değişmez. Dosya projesinin noktası,
        o revizyonla başlayan bir dosya projesi olur; veritabanı projesinin kontrol noktası,
        dosyasından içe aktarılan bir veritabanı projesi olur (nesneler kalıcı
        kimlikleriyle). Yeni proje çağıranındır; geçmiş ve paylaşımlar gelmez. Kaynakta
        project.history ve project.download, hedef çalışma alanında proje açma hakkı ister.

        Args:
            target: The cloud project (``Connection.project``).
            checkpoint_id:
            file_revision: A file project's revision (decimal text).
            name: The new project's name; the source's with the point's name after it when absent.
            tenant_id: The workspace of the new project; the source's when absent.
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectDuplicated

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            CheckpointRestore(
            checkpoint_id=checkpoint_id,
            file_revision=file_revision,
            name=name,
            tenant_id=tenant_id,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


restore = _ProjectCheckpointRestore()
"""Yeni proje olarak geri yükle (``project.checkpoint.restore``)."""


__all__ = ["create", "delete", "restore"]
