# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.project.file``: ``project.file.commit``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from .._runtime import CommandNote, ServerCommand, UNSET, Unset, _opt  # noqa: F401
from ..types import (  # noqa: F401
    FileCommit,
    FileCommitted,
)

if TYPE_CHECKING:
    from ..connection import ProjectRef, TenantRef


class _ProjectFileCommit(ServerCommand[FileCommit, FileCommitted]):
    """``project.file.commit`` v1. Dosya revizyonunu kaydet: Dosya olarak saklanan projede
    doğrulanmış bir yüklemeyi (POST …/uploads, PUT …/uploads/{yükleme}) projenin yeni
    revizyonu yapar. expectedVersions["@file"] dosyanın dayandığı revizyondur (ilk
    kayıtta "0"); proje o arada değiştiyse hiçbir şey yazılmaz, çakışma döner. Yetki
    kayıt anında yeniden sorulur. feature.write ister; revizyonlar değişmez, eski
    revizyon silinmez.
    """
    __slots__ = ()
    id = "project.file.commit"
    version = 1
    title = "Dosya revizyonunu kaydet"
    scope = "project"
    input_type = FileCommit
    output_type = FileCommitted

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        upload_id: str,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> FileCommitted:
        """Dosya revizyonunu kaydet: Dosya olarak saklanan projede doğrulanmış bir yüklemeyi
        (POST …/uploads, PUT …/uploads/{yükleme}) projenin yeni revizyonu yapar.
        expectedVersions["@file"] dosyanın dayandığı revizyondur (ilk kayıtta "0"); proje o
        arada değiştiyse hiçbir şey yazılmaz, çakışma döner. Yetki kayıt anında yeniden
        sorulur. feature.write ister; revizyonlar değişmez, eski revizyon silinmez.

        Args:
            target: The cloud project (``Connection.project``).
            upload_id:
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            FileCommitted

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            FileCommit(
            upload_id=upload_id,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


commit = _ProjectFileCommit()
"""Dosya revizyonunu kaydet (``project.file.commit``)."""


__all__ = ["commit"]
