# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.project.invitation``: ``project.invitation.revoke``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from .._runtime import CommandNote, ServerCommand, UNSET, Unset, _opt  # noqa: F401
from ..types import (  # noqa: F401
    InvitationChange,
    InvitationRevoke,
)

if TYPE_CHECKING:
    from ..connection import ProjectRef, TenantRef


class _ProjectInvitationRevoke(ServerCommand[InvitationRevoke, InvitationChange]):
    """``project.invitation.revoke`` v1. Daveti geri al: Bekleyen bir daveti geri alır;
    bağlantısı artık çalışmaz. Kabul edilmiş davetin verdiği erişim
    project.access.revoke ile kaldırılır. project.share ister.
    """
    __slots__ = ()
    id = "project.invitation.revoke"
    version = 1
    title = "Daveti geri al"
    scope = "project"
    input_type = InvitationRevoke
    output_type = InvitationChange

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        invitation_id: str,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> InvitationChange:
        """Daveti geri al: Bekleyen bir daveti geri alır; bağlantısı artık çalışmaz. Kabul
        edilmiş davetin verdiği erişim project.access.revoke ile kaldırılır. project.share
        ister.

        Args:
            target: The cloud project (``Connection.project``).
            invitation_id:
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            InvitationChange

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            InvitationRevoke(
            invitation_id=invitation_id,
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


revoke = _ProjectInvitationRevoke()
"""Daveti geri al (``project.invitation.revoke``)."""


__all__ = ["revoke"]
