# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.project.metadata``: ``project.metadata.update``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from .._runtime import CommandNote, ServerCommand, UNSET, Unset, _opt  # noqa: F401
from ..types import (  # noqa: F401
    ProjectCatalogChange,
    ProjectMetadataUpdate,
    ProjectType,
    ProjectTypeName,
)

if TYPE_CHECKING:
    from ..connection import ProjectRef, TenantRef


class _ProjectMetadataUpdate(ServerCommand[ProjectMetadataUpdate, ProjectCatalogChange]):
    """``project.metadata.update`` v1. Proje bilgilerini değiştir: Projenin katalog
    bilgilerini değiştirir: ad, açıklama, tür ve etiketler; verilmeyen alan olduğu gibi
    kalır. Tür yalnız katalogda düzen içindir: mevzuata uygunluk ya da resmî onay
    anlamına gelmez, bir modül açmaz, saklama biçimini değiştirmez. project.edit ister;
    arşivlenmiş ya da çöp kutusundaki projede yapılamaz. expectedVersions["@catalog"]
    verilmişse ve proje bilgileri o sürümde değilse hiçbir şey yazılmaz (409).
    """
    __slots__ = ()
    id = "project.metadata.update"
    version = 1
    title = "Proje bilgilerini değiştir"
    scope = "project"
    input_type = ProjectMetadataUpdate
    output_type = ProjectCatalogChange

    def __call__(
        self,
        target: ProjectRef,
        /,
        *,
        description: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        project_type: ProjectType | ProjectTypeName | None | Unset = UNSET,
        tags: Sequence[str] | None | Unset = UNSET,
        expected_versions: Mapping[str, str] | None = None,
        idempotency_key: str | None = None,
    ) -> ProjectCatalogChange:
        """Proje bilgilerini değiştir: Projenin katalog bilgilerini değiştirir: ad, açıklama,
        tür ve etiketler; verilmeyen alan olduğu gibi kalır. Tür yalnız katalogda düzen
        içindir: mevzuata uygunluk ya da resmî onay anlamına gelmez, bir modül açmaz,
        saklama biçimini değiştirmez. project.edit ister; arşivlenmiş ya da çöp kutusundaki
        projede yapılamaz. expectedVersions["@catalog"] verilmişse ve proje bilgileri o
        sürümde değilse hiçbir şey yazılmaz (409).

        Args:
            target: The cloud project (``Connection.project``).
            description: At most 2 000 characters; surrounding spaces are dropped.
            name:
            project_type:
            tags: At most 12, each 1–32 characters; spaces inside are collapsed, and a
                tag that differs from an earlier one only by case or Turkish letters is dropped.
            expected_versions: The versions the change rests on (``@project``,
                ``@file``, an object's id), as the server's envelope carries them.
            idempotency_key: The same key answers a retry with the same result;
                a new one is made when none is given.

        Returns:
            ProjectCatalogChange

        Raises:
            ServerError: the server's refusal (its code, message and field).
        """
        return self.execute_input(
            target,
            ProjectMetadataUpdate(
            description=description,
            name=name,
            project_type=project_type,
            tags=_opt(tags, lambda x: list(x)),
        ),
            expected_versions=expected_versions,
            idempotency_key=idempotency_key,
        )


update = _ProjectMetadataUpdate()
"""Proje bilgilerini değiştir (``project.metadata.update``)."""


__all__ = ["update"]
