import { ReadableTool, TextTool } from './annotateTools';
import { PlaceTextFileTool } from './textFileTool';
import { LeaderTool } from './leaderTool';
import { BlockDefineTool, BlockInsertTool } from './blockTools';
import { DimensionTool } from './dimensionTool';
import { HatchTool } from './hatchTool';
import { ArcTool, CircleTool, SplineTool } from './curveTools';
import { RayTool, XlineTool } from './constructionTools';
import { EllipseTool } from './ellipseTool';
import { EraseTool, LineTool, PendingTool, PointTool } from './drawTools';
import { PathTool } from './pathTool';
import { DonutTool, RevCloudTool } from './markupTools';
import { RectangleTool, RegularPolygonTool, RotatedRectangleTool } from './shapeTools';
import { ChamferTool, FilletTool } from './cornerTools';
import { ExtendTool, OffsetTool, TrimTool } from './edgeTools';
import { BreakTool, DivideTool, VertexTool } from './pathEditTools';
import { ExplodeTool, JoinTool, StretchTool } from './editTools';
import { ArrayTool, MirrorTool, MoveTool, RotateTool, ScaleTool } from './modifyTools';
import { ParallelLineTool } from './parallelTool';
import { AlignTool, PolarArrayTool } from './arrangeTools';
import { LengthenTool } from './lengthenTool';
import { CleanupTool } from './cleanupTool';
import { ElevationTool } from './elevationTool';
import { MatchPropertiesTool } from './matchTool';
import { ChamferAllTool, FilletAllTool, ReverseTool, SimplifyTool } from './reshapeTools';
import { SplitTool } from './splitTool';
import { SectorTool } from './sectorTool';
import { PointsBetweenTool } from './betweenTool';
import { IntersectPointTool } from './meetingTool';
import { MeasureAngleTool } from './angleTool';
import { AreaMeasureTool, DistanceTool } from './measureTools';
import { CircleSelectTool, ContainingSelectTool, FenceSelectTool } from './selectTools';
import { StationOffsetTool } from './stationOffsetTool';
import { DimBaselineTool, DimContinueTool } from './dimChainTools';
import { QuickDimensionTool } from './quickDimensionTool';
import { PathArrayTool } from './arrayPathTool';
import { PerpendicularInTool, PerpendicularOutTool } from './perpTools';
import { AreaIntersectTool, AreaSplitTool, AreaSubtractTool, AreaUnionTool, BoundaryTool, PartsJoinTool, PartsSplitTool, ToAreaTool, ToPolylineTool } from './areaTools';
import { PanTool, SelectTool, ZoomWindowTool } from './SelectTool';
import type { ToolDescriptor } from './Tool';
import { arcCreate } from '../product/arcCreate';
import { circleCreate } from '../product/circleCreate';
import { entitiesArray } from '../product/entitiesArray';
import { blocksDefine } from '../product/blocksDefine';
import { entitiesCreate } from '../product/entitiesCreate';
import { entitiesDelete } from '../product/entitiesDelete';
import { entitiesEdit } from '../product/entitiesEdit';
import { entitiesSet } from '../product/entitiesSet';
import { entitiesTransform } from '../product/entitiesTransform';
import { lineCreate } from '../product/lineCreate';
import { pointCreate } from '../product/pointCreate';
import { polygonCreate } from '../product/polygonCreate';
import { polylineCreate } from '../product/polylineCreate';

/** Layers the map tools write to (project template; new layers otherwise). */
const LAYERS = { parcel: 'parsel', spot: 'kot' };

type Def = Omit<ToolDescriptor, 'create' | 'ready'> & Partial<Pick<ToolDescriptor, 'create'>>;


/**
 * Every tool in one declarative list. Toolbox, classic menus, the ribbon,
 * shortcuts and the command line are all generated from this — add a tool
 * here (with its group and, in a sectioned group, its section) and it
 * shows up everywhere; no menu or ribbon file lists tools one by one.
 */
const defs: Def[] = [
  // Seçim
  { id: 'select', label: 'Seç', icon: 'select', family: 'select', group: 'select', shortcut: 'Esc', aliases: ['SEC', 'SELECT'], description: 'Nesne seçer. Sürükleyerek pencere ya da kesişim seçimi yapın.', steps: ['Nesneye tıklayın; Shift+tık seçime ekler ya da çıkarır.', 'Soldan sağa sürükleyin: tamamen içeride kalanlar seçilir. Sağdan sola: dokunan her şey seçilir.', 'Seçili nesnenin kare tutamacını sürükleyin: köşe taşınır. Kenar ortasındaki baklava yeni köşe ekler.'], create: (c) => new SelectTool(c) },
  { id: 'selectFence', family: 'select', label: 'Çitle seç', icon: 'selectFence', group: 'select', aliases: ['CITLESEC', 'FENCESELECT'], description: 'Çizilen çitin kestiği nesneleri seçer.', steps: ['Çitin noktalarına tıklayın.', 'Sağ tık ya da Enter: çitin kestiği görünür nesneler seçilir; Shift basılıysa seçime eklenir.'], create: (c) => new FenceSelectTool(c) },
  { id: 'selectCircle', family: 'select', label: 'Daireyle seç', icon: 'selectCircle', group: 'select', aliases: ['DAIRESEC', 'CIRCLESELECT'], description: 'Dairenin içinde kalan nesneleri seçer; “Kesişen” ile dokunanları da.', steps: ['Dairenin merkezine tıklayın.', 'Yarıçapı gösterip tıklayın ya da yazın: içinde kalan nesneler seçilir.', '“Kesişen” daireye dokunanları da seçer; Shift basılıysa seçime eklenir.'], create: (c) => new CircleSelectTool(c) },
  { id: 'selectContaining', family: 'select', label: 'İçeren alanı seç', icon: 'selectContaining', group: 'select', aliases: ['ICEREN', 'ICERENSEC'], description: 'Tıklanan noktayı içeren kapalı alanı seçer; aynı yere yeniden tıklamak bir büyüğüne geçer (parsel, ada, mahalle).', steps: ['Alanın içine tıklayın: noktayı içeren en küçük alan seçilir.', 'Aynı yere yeniden tıklayın: onu içeren bir büyük alan seçilir.', 'Esc ya da sağ tık bitirir; Shift basılıysa seçime eklenir.'], create: (c) => new ContainingSelectTool(c) },
  { id: 'zoomWindow', label: 'Pencere yakınlaştır', icon: 'zoomWindow', group: 'select', shortcut: 'Z', aliases: ['Z', 'ZOOM', 'PENCERE', 'PENCEREBUYUT'], description: 'Çizilen dikdörtgene yakınlaştırır.', steps: ['Yakınlaşılacak alanın bir köşesine tıklayın.', 'Karşı köşeye tıklayın ya da sürükleyin.'], create: (c) => new ZoomWindowTool(c) },
  { id: 'pan', label: 'Kaydır', icon: 'pan', group: 'select', shortcut: 'Shift+H', aliases: ['PAN', 'KAYDIR'], description: 'Görünümü sürükler. Orta tuşla her araçta kullanılabilir.', steps: ['Sürükleyerek görünümü kaydırın.', 'Her araçta orta tuşla sürüklemek de kaydırır, tekerlek yakınlaştırır.'], create: (c) => new PanTool(c) },

  // Çizim
  { id: 'point', label: 'Nokta', icon: 'point', group: 'draw', section: 'point', shortcut: 'N', aliases: ['PO', 'POINT', 'NOKTA'], description: 'Tek tek nokta yerleştirir.', steps: ['Noktanın konacağı her yere tıklayın.', 'Sağ tık ya da Esc: araçtan çıkın.'], productCommand: pointCreate.id, create: (c) => new PointTool(c, { id: 'point', label: 'Nokta', askZ: false }) },
  { id: 'line', primary: true, label: 'Çizgi', icon: 'line', group: 'draw', section: 'line', shortcut: 'L', aliases: ['L', 'LINE', 'CIZGI'], description: 'Uç uca bağlı çizgi parçaları çizer.', steps: ['İlk noktaya tıklayın.', 'Sonraki noktalara tıklayın; her tık bir çizgi ekler.', 'Sağ tık: bitir. “Geri” son parçayı geri alır, “Kapat” ilk noktaya döner.'], productCommand: lineCreate.id, create: (c) => new LineTool(c) },
  { id: 'polyline', primary: true, label: 'Çoklu çizgi', icon: 'polyline', group: 'draw', section: 'line', shortcut: 'P', aliases: ['PL', 'PLINE', 'COKLUCIZGI', 'COKLUDOGRU'], description: 'Tek parça, açık çoklu çizgi çizer; Y ile yay parçası (teğet, açı, merkez, yarıçap, ikinci nokta, doğrultu), D ile düz parça, U ile son doğrultuda uzunluk.', steps: ['İlk noktaya, sonra köşelere tıklayın.', '“Yay” ile yay parçasına geçin; yay teğet devam eder ya da “Açı”, “Merkez”, “Yarıçap”, “İkinci nokta”, “Doğrultu” ile tek parça için biçimlenir. “Düz” düze döner.', 'Sağ tık: bitir. “Geri” son köşeyi siler, “Uzunluk” son doğrultuda yazılan boyda devam eder.'], productCommand: polylineCreate.id, create: (c) => new PathTool(c, { id: 'polyline', label: 'Çoklu çizgi', closed: false }) },
  { id: 'polygon', label: 'Kapalı alan', icon: 'polygon', group: 'draw', section: 'line', shortcut: 'G', aliases: ['KA', 'ALAN', 'POLYGON'], description: 'Kapalı çoklu çizgi (alan) çizer.', steps: ['Köşelere sırayla tıklayın; alan imleç yanında görünür.', 'İlk köşeye tıklayın, sağ tıklayın ya da Enter: alan kapanıp biter.'], productCommand: polygonCreate.id, create: (c) => new PathTool(c, { id: 'polygon', label: 'Kapalı alan', closed: true }) },
  { id: 'parallel', label: 'Paralel çizgi', icon: 'parallel', group: 'draw', section: 'line', shortcut: 'Y', aliases: ['PARALEL', 'PC', 'ML', 'MLINE', 'DLINE'], description: 'Ekseni çizerken sağında ve solunda verilen mesafelerde paralel hatlar çizer (yol, kaldırım, duvar); istenirse arası tek alan olur.', steps: ['“Sol” ve “Sağ” ile mesafeleri yazın ya da iki noktaya tıklayarak gösterin.', 'Eksenin noktalarına tıklayın; paralel hatlar köşelerde birleşerek canlı çizilir.', 'Sağ tık bitirir, “Kapat” ekseni kapatır. “Eksen” ekseni çizip çizmemeyi, “Alan olarak” koridoru tek alan yapmayı seçer.'], productCommand: entitiesCreate.id, create: (c) => new ParallelLineTool(c) },
  { id: 'rectangle', family: 'rectangle', label: 'Dikdörtgen', icon: 'rectangle', group: 'draw', section: 'shape', shortcut: 'R', aliases: ['REC', 'RECTANGLE', 'DIKDORTGEN', 'KUTU'], description: 'İki karşı köşeden dikdörtgen çizer; döndürme açısı, tam boyut, köşe yuvarlama ve pah seçenekleriyle.', steps: ['Bir köşeye tıklayın (önce “Köşe yuvarla” ya da “Pah” ile köşe biçimini seçebilirsiniz).', 'Karşı köşeye tıklayın.', '“Döndür” ile açı, “Boyutlar” ile uzunluk,genişlik yazıp yönü tıklayarak gösterin.'], productCommand: polygonCreate.id, create: (c) => new RectangleTool(c) },
  { id: 'rectangle3', family: 'rectangle', label: 'Döndürülmüş dikdörtgen', icon: 'rectangle3', group: 'draw', section: 'shape', shortcut: 'Alt+R', aliases: ['REC3', 'DDIKDORTGEN', 'UCNOKTADIKDORTGEN'], description: 'Önce bir kenar çizilir, sonra yana çekilerek genişlik verilir; her açıda dikdörtgen.', steps: ['Kenarın ilk noktasına tıklayın.', 'Kenarın ikinci noktasına tıklayın ya da uzunluk yazın (kenet, izleme ve orto çalışır).', 'Fareyi kenardan yana çekip tıklayın ya da genişliği yazın.'], productCommand: polygonCreate.id, create: (c) => new RotatedRectangleTool(c) },
  { id: 'regularPolygon', family: 'rectangle', label: 'Düzgün çokgen', icon: 'regularPolygon', group: 'draw', section: 'shape', shortcut: 'Shift+G', aliases: ['POL', 'POLYGON3', 'COKGEN'], description: 'Kenar sayısı verilen düzgün çokgen: merkezden (çembere içten ya da dıştan) ya da bir kenardan.', steps: ['Kenar sayısını yazın (varsayılan 6) ya da “Kenar sayısı” düğmesine basın.', 'Merkeze tıklayın; fareyle bir köşeyi (ya da “Çember: kenarlara teğet” ile bir kenar ortasını) gösterip tıklayın.', '“Kenardan” ile bir kenarın iki ucuna tıklayarak çizin; yarıçap yazılırsa alt kenar yatay olur.'], productCommand: polygonCreate.id, create: (c) => new RegularPolygonTool(c) },
  { id: 'circle', primary: true, methods: [{ label: 'Merkez, yarıçap' }, { label: '2 nokta', option: '2N', description: 'Çapın iki ucundan' }, { label: '3 nokta', option: '3N', description: 'Çember üzerindeki üç noktadan' }, { label: 'Teğet, teğet, yarıçap', option: 'TTY', description: 'İki nesneye teğet, yarıçap yazılır' }, { label: 'Teğet, teğet, teğet', option: 'TTT', description: 'Üç nesneye teğet' }], label: 'Daire', icon: 'circle', group: 'draw', section: 'curve', shortcut: 'C', aliases: ['C', 'CIRCLE', 'DAIRE'], description: 'Merkez ve yarıçap ya da çapla; 2N çaptan, 3N üç noktadan, TTY iki nesneye teğet yarıçaplı, TTT üç nesneye teğet daire.', steps: ['Merkeze tıklayın.', 'Çember üzerindeki bir noktaya tıklayın ya da yarıçapı yazın; “Çap” ile çap verilir.', 'Üstteki düğmeler: “2 nokta” çaptan, “3 nokta” üç noktadan, “Teğet-teğet-yarıçap” iki nesneye dokunan daire, “Teğet-teğet-teğet” üç nesneye (teğet olacağı yerlerin yakınından) tıklanarak.'], productCommand: circleCreate.id, create: (c) => new CircleTool(c) },
  { id: 'arc', primary: true, methods: [{ label: '3 nokta' }, { label: 'Merkez, başlangıç, bitiş', option: 'M', description: 'Önce merkez, sonra başlangıç ve bitiş ya da açı veya kiriş' }, { label: 'Devam', option: 'D', description: 'Son çizilen nesneye teğet devam eder' }], label: 'Yay', icon: 'arc', group: 'draw', section: 'curve', shortcut: 'A', aliases: ['A', 'ARC', 'YAY'], description: 'AutoCAD’in tüm yay yöntemleri: üç nokta; başlangıç-merkez-bitiş/açı/kiriş; başlangıç-bitiş-merkez/açı/yön/yarıçap; merkez-başlangıç; son nesneye teğet devam.', steps: ['Başlangıca, yay üzerindeki bir noktaya ve bitişe tıklayın (üç nokta).', 'Başlangıçtan sonra “Merkez” ya da “Bitiş” düğmesiyle yöntemi seçin; üçüncü adımda “Açı”, “Kiriş”, “Yön”, “Yarıçap” ile değer verin.', 'İlk adımda “Merkez” merkezden başlar, “Devam” son çizgi ya da yaya teğet yay çizer.'], productCommand: arcCreate.id, create: (c) => new ArcTool(c) },
  { id: 'ellipse', label: 'Elips', icon: 'ellipse', group: 'draw', section: 'curve', shortcut: 'Shift+L', aliases: ['EL', 'ELLIPSE', 'ELIPS'], description: 'Elips ya da eliptik yay: eksen uçlarından ya da merkezden; diğer yarı eksen uzunlukla ya da döndürme açısıyla.', steps: ['Bir eksenin iki ucuna tıklayın (“Merkez” ile önce merkeze).', 'Fareyle diğer yarı ekseni gösterip tıklayın ya da uzunluğunu yazın; “Döndürme” ile açı yazılır.', '“Yay” açıksa başlangıç ve bitiş açısını gösterin; eliptik yay çizilir.'], productCommand: entitiesCreate.id, create: (c) => new EllipseTool(c) },
  { id: 'spline', label: 'Eğri', icon: 'spline', group: 'draw', section: 'curve', shortcut: 'S', aliases: ['SPL', 'SPLINE', 'EGRI'], description: 'Tıklanan noktalardan geçen yumuşak eğri çizer; K ile kapatır.', steps: ['Eğrinin geçeceği noktalara sırayla tıklayın.', 'Sağ tık: bitir. “Kapat” kapalı eğri yapar.'], productCommand: entitiesCreate.id, create: (c) => new SplineTool(c) },
  { id: 'xline', family: 'construction', label: 'Yardımcı çizgi', icon: 'xline', group: 'draw', section: 'construction', shortcut: 'Shift+X', aliases: ['XL', 'XLINE', 'YARDIMCI'], description: 'İki yöne sonsuz yardımcı çizgi: bir noktadan, yatay, düşey, açılı ya da açıortay.', steps: ['Bir noktaya tıklayın, sonra geçeceği her noktaya tıklayın; her tık bir çizgi.', '“Yatay”, “Düşey”, “Açı” düğmeleriyle yön sabitlenir, tıklanan her noktadan geçer.', '“Açıortay”: açının köşesine, sonra iki koluna tıklayın.'], productCommand: entitiesCreate.id, create: (c) => new XlineTool(c) },
  { id: 'ray', family: 'construction', label: 'Işın', icon: 'ray', group: 'draw', section: 'construction', shortcut: 'Alt+X', aliases: ['RAY', 'ISIN'], description: 'Bir başlangıç noktasından tek yöne sonsuz yardımcı çizgi.', steps: ['Başlangıç noktasına tıklayın.', 'Işının geçeceği her noktaya tıklayın; sağ tık bitirir.'], productCommand: entitiesCreate.id, create: (c) => new RayTool(c) },
  { id: 'donut', rare: true, label: 'Halka', icon: 'donut', group: 'draw', section: 'curve', aliases: ['DO', 'DONUT', 'HALKA'], description: 'Dolu halka ya da (iç çap 0 ile) dolu daire koyar; her tıklama bir tane.', steps: ['“İç çap” ve “Dış çap” ile ölçüleri yazın.', 'Halkanın merkezine tıklayın; araç sonrakini bekler.'], productCommand: entitiesCreate.id, create: (c) => new DonutTool(c) },
  { id: 'sector', label: 'Daire dilimi', icon: 'sector', group: 'draw', section: 'curve', aliases: ['DILIM', 'SECTOR', 'DAIREDILIMI'], description: 'Merkezden ve iki kenardan kapalı daire dilimi (pasta dilimi) çizer; yay saat yönünün tersine süpürülür.', steps: ['Merkeze tıklayın.', 'Başlangıç noktasına tıklayın (yarıçap ve başlangıç açısı buradan gelir); ya da yarıçapı yazın, sonra başlangıç açısını yazın ya da yönünü gösterin.', 'Bitiş doğrultusunu gösterin ya da bitiş açısını yazın: dilim canlı görünür. Açılar projenin açı biriminde, doğudan saat yönünün tersine sayılır.'], productCommand: polygonCreate.id, create: (c) => new SectorTool(c) },
  { id: 'perpIn', family: 'perpendicular', label: 'Dik in', icon: 'perpIn', group: 'draw', section: 'construction', shortcut: 'I', aliases: ['DIKIN', 'DIK'], description: 'Gösterilen noktalardan bir hatta dik iner (hattın uzantısına da); yay ve dairede merkeze doğru.', steps: ['Referans hatta tıklayın.', 'Dik inilecek her noktaya tıklayın (kenet çalışır); dik boy ve dik ayak imleç yanında görünür.', 'Sağ tık bitirir; “Başka hat” yeni referans seçtirir.'], productCommand: entitiesCreate.id, create: (c) => new PerpendicularInTool(c) },
  { id: 'perpOut', family: 'perpendicular', label: 'Dik çık', icon: 'perpOut', group: 'draw', section: 'construction', shortcut: 'O', aliases: ['DIKCIK'], description: 'Hat üzerindeki bir noktadan, verilen dik boyda dik çıkar; dik ayak tıklanan uçtan ölçülür, dik boy sağa artıdır.', steps: ['Referans hatta, başlangıç sayılacak ucuna yakın tıklayın (A).', 'Hat üzerinde dik çıkılacak yere tıklayın ya da A’dan uzaklığı yazın.', 'Dik boyu fareyle gösterip tıklayın ya da yazın (sağa artı, sola eksi).'], productCommand: entitiesCreate.id, create: (c) => new PerpendicularOutTool(c) },
  { id: 'divide', label: 'Böl', icon: 'divide', group: 'draw', section: 'point', shortcut: 'Shift+D', aliases: ['DIV', 'DIVIDE', 'ME', 'MEASURE', 'BOL'], description: 'Nesne boyunca nokta koyar: eşit parçalara ya da A ile verilen aralıkla.', steps: ['Bölünecek çizgi, yay, daire ya da çoklu çizgiye tıklayın.', 'Parça sayısını yazıp Enter’a basın ya da sağ tıklayıp son değeri kullanın.', 'Metre cinsinden aralıkla bölmek için “Aralık” düğmesine basın.'], productCommand: entitiesCreate.id, create: (c) => new DivideTool(c) },
  { id: 'pointsBetween', label: 'Ara nokta', icon: 'pointsBetween', group: 'draw', section: 'point', methods: [{ label: 'Eşit aralık' }, { label: 'Uzaklıkla', option: 'U', description: 'İlk noktadan verilen uzaklıklarda' }, { label: 'Oranla', option: 'O', description: 'İki nokta arasının oranında (0 ile 1 arası)' }], aliases: ['ARANOKTA'], description: 'İki nokta arasındaki doğru üzerine nokta koyar: eşit aralıkla, ilk noktadan uzaklıkla ya da oranla.', steps: ['İki noktaya tıklayın (kenet çalışır); noktalar canlı görünür.', 'Eşit aralık: parça sayısını yazın (varsayılan 4). “Uzaklıkla”: ilk noktadan uzaklıkları virgülle yazın (5, 12.5). “Oranla”: 0 ile 1 arası oranları virgülle yazın (0.25, 0.5).', 'Yazılan değer hemen yazar; Enter son değerle yazar. Araç sonraki iki noktayı bekler.'], productCommand: entitiesCreate.id, create: (c) => new PointsBetweenTool(c) },
  { id: 'intersectPoint', label: 'Kesişim noktası', icon: 'intersectPoint', group: 'draw', section: 'point', methods: [{ label: 'İki uzaklık' }, { label: 'İki doğrultu', option: 'D', description: 'İki noktadan okunan doğrultular' }, { label: 'İki doğru', option: 'L', description: 'İki noktayla verilen iki doğru' }], aliases: ['KESISIMNOKTA', 'KESISIM'], description: 'İki bilinen noktadan ölçülen uzaklıkların, doğrultuların ya da iki doğrunun kesişimine nokta koyar.', steps: ['İki uzaklık: A noktasına tıklayın, uzaklığı yazın ya da çember üzerinde tıklayın; B için aynısı. İki kesişimden istediğinize tıklayın (Enter: A’dan B’ye bakınca sağdaki).', '“İki doğrultu”: A ve B noktalarına tıklayıp her birinden doğrultuyu yazın (projenin açı biriminde, kuzeyden saat yönünde) ya da tıklayarak gösterin.', '“İki doğru”: iki doğrunun dört noktasına tıklayın. Nokta konur, Y ve X’i iletide söylenir.'], productCommand: entitiesCreate.id, create: (c) => new IntersectPointTool(c) },

  // Açıklama
  { id: 'text', primary: true, label: 'Yazı', icon: 'text', group: 'annotate', shortcut: 'T', aliases: ['T', 'TEXT', 'YAZI'], description: 'Tek satır yazı: tıklanan yerde açılan kutuya yazılır. Yükseklik kâğıt mm olarak, açı derece ya da iki noktayla verilir; yazıya çift tıklayarak düzenleyin.', steps: ['Yazının başlayacağı yere tıklayın: orada bir yazı kutusu açılır.', 'Yazıyı yazıp Enter’a basın; Esc vazgeçer. Araç bir sonraki yazı için bekler.', '“Yükseklik” mm, “Açı” derece ya da bir çizgi boyunca iki tıkla verilir. Var olan yazıya çift tıklayarak düzenleyin.'], productCommand: entitiesCreate.id, create: (c) => new TextTool(c) },
  { id: 'leader', primary: true, label: 'Kılavuz', icon: 'leader', group: 'annotate', aliases: ['KILAVUZ', 'LEADER', 'LE', 'MLEADER', 'MLD'], description: 'Oklu not: okun ucundan köşelerden geçen çizgi, kol ve kolun ucunda not. Ok başı, not yüksekliği ve zemin seçilir.', steps: ['Okun ucuna, sonra köşelere tıklayın.', 'Enter ya da sağ tık köşeleri bitirir: notu kolun ucunda açılan kutuya yazıp Enter’a basın. Boş kutuda Enter notsuz kılavuz ekler, Esc köşelere döner.', '“Ok” ok başını (dolu, açık, nokta, yok), “Yükseklik” notun kâğıt mm yüksekliğini (Yazı ile ortak), “Zemin” notun altını doldurmayı seçer; “Geri” son köşeyi siler.'], productCommand: entitiesCreate.id, create: (c) => new LeaderTool(c) },
  { id: 'placeTextFile', label: 'Metin dosyası yerleştir', icon: 'textFile', group: 'annotate', aliases: ['METINDOSYASI', 'PLACETEXTFILE', 'MTD'], description: 'Bir UTF-8 metin dosyasının her satırını, Yazı aracının seçenekleriyle, alt alta yazı olarak yerleştirir; tek adımda.', steps: ['Metin dosyasını seçin (en çok 1 MB, 10 000 satır).', 'İlk satırın başlayacağı yere tıklayın: satırlar yazı yüksekliğinin 1,5 katı aralıkla alt alta dizilir; boş satır yerini tutar.'], productCommand: entitiesCreate.id, create: (c) => new PlaceTextFileTool(c) },
  {
    id: 'dimension',
    primary: true,
    // The annotation panel's lead: large while the panel shows labels (DESIGN.md §7.3.1).
    lead: true,
    family: 'dimension',
    // Each method starts the tool with its style's option and has its own icon; its own typed names start it too (docs/adr/0147 §7).
    methods: [
      { label: 'Hizalı', option: 'H', icon: 'dimAligned', description: 'İki nokta arası, kendi doğrultusunda', aliases: ['DIMALIGNED', 'DAL'] },
      { label: 'Doğrusal', option: 'D', icon: 'dimLinear', description: 'ΔY yatay ya da ΔX düşey', aliases: ['DIMLIN', 'DIMLINEAR', 'DLI'] },
      { label: 'Açı', option: 'A', icon: 'dimAngular', description: 'İki kenar ya da iki kol arası', aliases: ['DIMANG', 'DIMANGULAR', 'DAN'] },
      { label: 'Yarıçap', option: 'R', icon: 'dimRadius', description: 'Daire ya da yayın yarıçapı', aliases: ['DIMRAD', 'DIMRADIUS', 'DRA'] },
      { label: 'Çap', option: 'Ç', icon: 'dimDiameter', description: 'Daire ya da yayın çapı', aliases: ['DIMDIA', 'DIMDIAMETER', 'DDI'] },
      { label: 'Koordinat', option: 'O', icon: 'dimOrdinate', description: 'Noktanın Y ya da X koordinatı', aliases: ['KOORDINATOLCU', 'DIMORDINATE', 'DOR'] },
      { label: 'Yay uzunluğu', option: 'U', icon: 'dimArcLength', description: 'Yayın ya da iki noktasının arası', aliases: ['YAYUZUNLUGU', 'DIMARC', 'DAR'] },
      { label: 'Kırıklı yarıçap', option: 'I', icon: 'dimJogged', description: 'Merkezi uzak yayın yarıçapı', aliases: ['KIRIKLI', 'DIMJOGGED', 'DJO'] },
      { label: 'Semt', option: 'T', icon: 'dimAzimuth', description: 'Kenarın semti, yanında okla', aliases: ['SEMT', 'SEMTOLCU'] },
      { label: 'Eğim', option: 'E', icon: 'dimSlope', description: 'İki kot arası eğim, yüzde', aliases: ['EGIM', 'EGIMOLCU', 'SLOPE'] },
    ],
    label: 'Ölçülendirme',
    icon: 'dimension',
    group: 'annotate',
    shortcut: 'D',
    aliases: ['DIM', 'OLCU', 'DIMALIGNED', 'DAL', 'DIMLIN', 'DIMLINEAR', 'DLI', 'DIMANG', 'DIMANGULAR', 'DAN', 'DIMRAD', 'DIMRADIUS', 'DRA', 'DIMDIA', 'DIMDIAMETER', 'DDI', 'KOORDINATOLCU', 'DIMORDINATE', 'DOR', 'YAYUZUNLUGU', 'DIMARC', 'DAR', 'KIRIKLI', 'DIMJOGGED', 'DJO', 'SEMT', 'SEMTOLCU', 'EGIM', 'EGIMOLCU', 'SLOPE'],
    description: 'Ölçü ekler: hizalı, doğrusal (ΔY yatay / ΔX düşey), açı, yarıçap, çap, bir noktanın koordinatı, yay uzunluğu, kırıklı yarıçap, semt ve eğim; değer proje birimini izler.',
    steps: [
      'Türü Ölçülendirme ▾ listesinden ya da komut satırının seçeneklerinden seçin (Hizalı, Doğrusal, Açı, Yarıçap, Çap, Koordinat, Yay uzunluğu, Kırıklı yarıçap, Semt, Eğim).',
      'Hizalı ve doğrusal: iki noktaya, sonra ölçü çizgisinin yerine tıklayın; doğrusalda yön imlecin yerinden seçilir. Açı: iki kenara (ya da “Köşeden” ile köşe ve iki kola) tıklayın, yayı yerleştirin.',
      'Yarıçap ve çap: daireye ya da yaya tıklayın, doğrultuyu gösterin.',
      'Koordinat: noktaya, sonra çizginin ucuna tıklayın; imleç daha çok düşey giderse Y, yatay giderse X yazılır (Y ve X ekseni sabitler). Yay uzunluğu: yaya ya da yaylı kenara tıklayın (“Kısmi” ile yayın üstünde iki nokta), ölçü yayını yerleştirin ya da uzaklığını yazın.',
      'Kırıklı yarıçap: daireye ya da yaya, sonra çizginin başlayacağı merkeze ve yaydaki noktaya tıklayın, kırığı yerleştirin. Semt ve eğim: iki noktaya (ya da “Kenardan” ile bir kenara) tıklayın, oku yerleştirin; eğimde kot kenetlenen köşeden alınır, yoksa sorulur.',
    ],
    productCommand: entitiesCreate.id,
    create: (c) => new DimensionTool(c),
  },
  { id: 'dimContinue', family: 'dimension', label: 'Zincir ölçü', icon: 'dimContinue', group: 'annotate', aliases: ['DIMCONTINUE', 'DCO', 'ZINCIROLCU'], description: 'Son ölçünün ucundan başlayarak aynı çizgi üzerinde art arda ölçüler ekler.', steps: ['Son çizilen hizalı ya da doğrusal ölçüden devam eder; yoksa bir ölçüye tıklayın (“Ölçü seç” başka ölçü seçtirir).', 'Sonraki noktalara tıklayın: her tık bir önceki noktadan bir ölçü ekler, aynı ölçü çizgisi üzerinde.', 'Sağ tık ya da Enter bitirir.'], productCommand: entitiesCreate.id, create: (c) => new DimContinueTool(c) },
  { id: 'dimBaseline', family: 'dimension', label: 'Baz ölçü', icon: 'dimBaseline', group: 'annotate', aliases: ['DIMBASELINE', 'DBA', 'BAZOLCU'], description: 'Son ölçünün ilk noktasından ölçülen ölçüleri üst üste dizer.', steps: ['Son çizilen hizalı ya da doğrusal ölçüden devam eder; yoksa bir ölçüye tıklayın (“Ölçü seç” başka ölçü seçtirir).', 'Sonraki noktalara tıklayın: her tık ilk noktadan bir ölçü ekler; çizgiler yazı yüksekliğinin üç katı aralıkla üst üste dizilir.', 'Sağ tık ya da Enter bitirir.'], productCommand: entitiesCreate.id, create: (c) => new DimBaselineTool(c) },
  { id: 'quickDimension', family: 'dimension', label: 'Hızlı ölçü', icon: 'dimQuick', group: 'annotate', aliases: ['QDIM', 'HIZLIOLCU'], description: 'Seçili çizgilerin, çoklu çizgilerin ve alanların her kenarını tek seferde ölçer.', steps: ['Ölçülecek çizgileri, çoklu çizgileri ve alanları seçin; seçim varsa araç hemen başlar, yoksa seçip Enter’a basın.', 'Ölçülerin yerini imleçle gösterin ya da uzaklığı yazın: her düz kenara hizalı, her yaylı kenara yay uzunluğu ölçüsü; alanda dışarıda, açık çizgide imlecin tarafında, iki nesnenin ortak kenarı bir kez.', 'Hepsi tek adımda yazılır; Zemin (Z) değerleri zeminli yazar.'], productCommand: entitiesCreate.id, create: (c) => new QuickDimensionTool(c) },
  { id: 'revcloud', rare: true, label: 'Revizyon bulutu', icon: 'revcloud', group: 'annotate', aliases: ['REVCLOUD', 'BULUT'], description: 'Değişen yeri çevreleyen, dışa bombeli yaylardan kapalı bulut çizer; dikdörtgen ya da çokgen.', steps: ['Dikdörtgenin iki köşesine tıklayın (ya da “Çokgen” ile köşelere tıklayıp sağ tıklayın).', '“Yay boyu” yay uzunluğunu kâğıt milimetresi olarak ayarlar.'], productCommand: polygonCreate.id, create: (c) => new RevCloudTool(c) },
  { id: 'hatch', primary: true, label: 'Tarama', icon: 'hatch', group: 'annotate', shortcut: 'H', aliases: ['H', 'HATCH', 'TARAMA'], description: 'Tıklanan kapalı alanı desenle tarar; D ile desen değişir.', steps: ['Taranacak kapalı alanın içine tıklayın.', 'Deseni üstteki “Desen” düğmesiyle değiştirin.'], productCommand: entitiesCreate.id, create: (c) => new HatchTool(c) },
  // Blok (docs/adr/0144)
  { id: 'blockDefine', label: 'Blok oluştur', icon: 'blockDefine', group: 'block', aliases: ['BLOCK', 'BLOKOLUSTUR', 'BLOKTANIMLA'], description: 'Seçili nesnelerden, taban noktası ve adıyla bir blok tanımlar; istenirse nesnelerin yerine bloğun bir yerleştirmesini koyar.', steps: ['Nesnelere tıklayın ya da pencereyle seçin, sonra sağ tıklayın. Önceden seçiliyse bu adım atlanır.', 'Taban noktasına tıklayın ya da Y,X yazın: bloğun yerleştirmeleri bu noktadan konur.', 'Açılan pencerede adı yazın; “Seçilenleri blokla değiştir” nesnelerin yerine bloğu koyar.'], productCommand: blocksDefine.id, create: (c) => new BlockDefineTool(c) },
  { id: 'blockInsert', label: 'Blok ekle', icon: 'blockInsert', group: 'block', aliases: ['INSERT', 'BLOKEKLE', 'SEMBOLEKLE'], description: 'Çizimde tanımlı bir bloğu tıklanan ya da yazılan noktalara yerleştirir; ölçeği, dönüşü ve aynalanması seçilir.', steps: ['Yerleştirme noktasına tıklayın ya da Y,X yazın: her tık bir yerleştirmedir.', '“Blok” sıradaki bloğa geçer; “Ölçek” ve “Dönüş” (derece) yazılır, “Aynala” bloğu x ekseninde aynalar.', 'Sağ tık ya da Enter bitirir.'], productCommand: entitiesCreate.id, create: (c) => new BlockInsertTool(c) },

  // Dönüştür
  { id: 'move', primary: true, label: 'Taşı', icon: 'move', group: 'transform', section: 'move', shortcut: 'Shift+M', aliases: ['M', 'MOVE', 'TASI'], description: 'Seçili nesneleri temel noktadan hedefe taşır.', steps: ['Nesnelere tıklayın ya da pencereyle seçin, sonra sağ tıklayın. Önceden seçiliyse bu adım atlanır.', 'Temel noktaya tıklayın.', 'Hedef noktaya tıklayın.'], productCommand: entitiesTransform.id, create: (c) => new MoveTool(c, { id: 'move', label: 'Taşı', copy: false }) },
  { id: 'copy', primary: true, label: 'Kopyala', icon: 'copy', group: 'transform', section: 'move', shortcut: 'Shift+C', aliases: ['CO', 'COPY', 'KOPYALA'], description: 'Seçili nesnelerin bir ya da daha fazla kopyasını çıkarır.', steps: ['Nesneleri seçip sağ tıklayın.', 'Temel noktaya tıklayın.', 'Her tık bir kopya bırakır; sağ tıkla bitirin.'], productCommand: entitiesTransform.id, create: (c) => new MoveTool(c, { id: 'copy', label: 'Kopyala', copy: true }) },
  { id: 'rotate', primary: true, label: 'Döndür', icon: 'rotate', group: 'transform', section: 'move', shortcut: 'Shift+R', aliases: ['RO', 'ROTATE', 'DONDUR'], description: 'Seçili nesneleri bir nokta etrafında döndürür. Açı yazılabilir; K ile kopya.', steps: ['Nesneleri seçip sağ tıklayın.', 'Dönme merkezine tıklayın.', 'Açıyı fareyle gösterip tıklayın ya da derece yazın. “Kopya” açıkken asıl nesne yerinde kalır.'], productCommand: entitiesTransform.id, create: (c) => new RotateTool(c) },
  { id: 'scale', label: 'Ölçekle', icon: 'scale', group: 'transform', section: 'move', shortcut: 'Shift+S', aliases: ['SC', 'SCALE', 'OLCEKLE'], description: 'Seçili nesneleri temel noktaya göre büyütür ya da küçültür: faktör ya da referans uzunluk.', steps: ['Nesneleri seçip sağ tıklayın.', 'Temel noktaya tıklayın.', 'Faktörü yazın ya da referans uzunluğun ucuna, ardından yeni uzunluğa tıklayın.'], productCommand: entitiesTransform.id, create: (c) => new ScaleTool(c) },
  { id: 'mirror', label: 'Aynala', icon: 'mirror', group: 'transform', section: 'move', shortcut: 'Shift+I', aliases: ['MI', 'MIRROR', 'AYNALA'], description: 'Seçili nesnelerin iki noktalı eksene göre simetriğini alır; S ile kaynağı siler.', steps: ['Nesneleri seçip sağ tıklayın.', 'Simetri ekseninin iki noktasına tıklayın.', '“Kaynağı sil” açıkken asıllar yerinde çevrilir.'], productCommand: entitiesTransform.id, create: (c) => new MirrorTool(c) },
  { id: 'stretch', label: 'Esnet', icon: 'stretch', group: 'transform', section: 'move', shortcut: 'E', aliases: ['STR', 'STRETCH', 'ESNET'], description: 'Pencerenin içinde kalan köşeleri taşır; dışındakiler yerinde kalır.', steps: ['Taşınacak köşeleri içine alan pencereyi sürükleyin ya da iki köşesine tıklayın.', 'Temel noktaya tıklayın.', 'Hedefe tıklayın: pencere içindeki köşeler taşınır, dışındakiler yerinde kalır.'], productCommand: entitiesEdit.id, create: (c) => new StretchTool(c) },
  { id: 'array', family: 'array', label: 'Dizi', icon: 'array', group: 'transform', section: 'array', shortcut: 'Shift+A', aliases: ['AR', 'ARRAY', 'DIZI'], description: 'Seçili nesneleri satır ve sütun düzeninde çoğaltır.', steps: ['Nesneleri seçip sağ tıklayın.', 'Satır ve sütun sayısını yazın (ör. 2,3) ya da sağ tıklayıp son değeri kullanın.', 'Aralığı iki noktaya tıklayarak gösterin ya da dY,dX yazın.'], productCommand: entitiesArray.id, create: (c) => new ArrayTool(c) },

  { id: 'arrayPolar', family: 'array', label: 'Kutupsal dizi', icon: 'arrayPolar', group: 'transform', section: 'array', aliases: ['ARPO', 'ARRAYPOLAR', 'KDIZI', 'KUTUPSALDIZI'], description: 'Seçili nesneleri bir merkez çevresinde çoğaltır: adet, doldurma açısı, nesneler dönsün ya da dönmesin.', steps: ['Nesneleri seçip sağ tıklayın.', 'Merkeze tıklayın; kopyalar canlı görünür.', '“Adet”, “Açı” (360 tam tur, eksi saat yönünde) ve “Nesneleri döndür” ile ayarlayıp sağ tıklayın.'], productCommand: entitiesArray.id, create: (c) => new PolarArrayTool(c) },
  { id: 'arrayPath', family: 'array', label: 'Yol boyunca dizi', icon: 'arrayPath', group: 'transform', section: 'array', aliases: ['ARRAYPATH', 'YOLDIZI'], description: 'Seçili nesneleri bir çizgi, yay ya da çoklu çizgi boyunca eşit aralıkla çoğaltır; istenirse yolun doğrultusuna döndürür.', steps: ['Nesneleri seçip sağ tıklayın.', 'Yola tıklayın: çizgi, yay, daire ya da çoklu çizgi.', 'Adedi yazın, seçilen dahil (varsayılan 5) ya da “Aralık” ile aralığı yazın; “Hizala” kopyaları yolun doğrultusuna döndürür. Kopyalar canlı görünür, sağ tık uygular.'], productCommand: entitiesArray.id, create: (c) => new PathArrayTool(c) },
  { id: 'align', label: 'Hizala', icon: 'align', group: 'transform', section: 'move', aliases: ['AL', 'ALIGN', 'HIZALA'], description: 'Seçimi iki nokta çiftiyle yerine oturtur: birinci kaynak birinci hedefe taşınır, ikinci çift yönü (isterseniz ölçeği) verir.', steps: ['Nesneleri seçip sağ tıklayın.', 'Birinci kaynak noktasına, sonra birinci hedef noktasına tıklayın (yalnız taşımak için burada sağ tıklayın).', 'İkinci kaynak ve ikinci hedef noktalarına tıklayın; “Ölçekle” açıkken boy da hedefe uyar.'], productCommand: entitiesTransform.id, create: (c) => new AlignTool(c) },
  // Düzenle
  { id: 'offset', primary: true, label: 'Ötele', icon: 'offset', group: 'modify', section: 'edge', shortcut: 'Shift+O', aliases: ['O', 'OFFSET', 'OTELE'], description: 'Çizgi, çoklu çizgi, alan, daire ya da yayın paralel kopyasını çıkarır; iki yana ya da kaynağı silerek.', steps: ['Ötelenecek nesneye tıklayın.', 'Kopyanın gideceği tarafa tıklayın.', 'Mesafe için sayı yazın; “Noktadan geç” açıkken kopya tıkladığınız noktadan geçer. “İki yana” iki yanda birden kopya çıkarır, “Kaynağı sil” özgün nesneyi aynı adımda siler.'], productCommand: entitiesEdit.id, create: (c) => new OffsetTool(c) },
  { id: 'trim', primary: true, methods: [{ label: 'Tıklayarak' }, { label: 'Çit', option: 'C', description: 'Çizilen çitin kestiği her parçayı budar' }], label: 'Buda', icon: 'trim', group: 'modify', section: 'edge', shortcut: 'Shift+T', aliases: ['TR', 'TRIM', 'BUDA'], description: 'Tıklanan parçayı, onu kesen en yakın iki kenar arasında siler.', steps: ['Silinecek parçanın üzerine tıklayın; kırmızı gösterilen kısım gider.', 'Görünen diğer tüm kenarlar kesici sayılır.', '“Çit” ile çitin noktalarına tıklayın: çitin kestiği her parça budanır. Sağ tık uygular.'], productCommand: entitiesEdit.id, create: (c) => new TrimTool(c) },
  { id: 'extend', methods: [{ label: 'Tıklayarak' }, { label: 'Çit', option: 'C', description: 'Çizilen çitin kestiği her nesnenin ucunu uzatır' }], label: 'Uzat', icon: 'extend', group: 'modify', section: 'edge', shortcut: 'Shift+E', aliases: ['EX', 'EXTEND', 'UZAT'], description: 'Çizgi ya da yay ucunu ilk rastladığı kenara kadar uzatır.', steps: ['Uzatılacak ucun yakınına tıklayın.', 'Nesne ilk rastladığı kenara kadar uzar.', '“Çit” ile çitin noktalarına tıklayın: çitin kestiği her nesnenin çite yakın ucu uzar. Sağ tık uygular.'], productCommand: entitiesEdit.id, create: (c) => new ExtendTool(c) },
  { id: 'lengthen', rare: true, label: 'Uzat-kısalt', icon: 'lengthen', group: 'modify', section: 'edge', shortcut: 'Shift+U', aliases: ['LEN', 'LENGTHEN', 'UZATKISALT'], description: 'Çizgi, yay ya da açık çoklu çizginin boyunu bir ucundan değiştirir: fareyle, farkla, yüzdeyle ya da toplam uzunlukla.', steps: ['Değişecek ucun yakınına tıklayın.', 'Yeni ucu fareyle gösterin (uzatmada son parça doğrultusunda ya da çemberinde devam eder) ya da toplam uzunluğu yazın.', '“Fark”, “Yüzde”, “Toplam” kiplerinde tıklanan her uç hemen değişir.'], productCommand: entitiesEdit.id, create: (c) => new LengthenTool(c) },
  { id: 'break', label: 'Kır', icon: 'break', group: 'modify', section: 'edge', shortcut: 'B', aliases: ['BR', 'BREAK', 'KIR'], description: 'Nesnenin iki nokta arasındaki kısmını siler; Enter ile tek noktadan böler.', steps: ['Nesneye, kırılacak ilk noktadan tıklayın.', 'İkinci noktaya tıklayın: aradaki kısım silinir.', 'Tek noktadan ikiye bölmek için ikinci tık yerine sağ tıklayın.'], productCommand: entitiesEdit.id, create: (c) => new BreakTool(c) },
  { id: 'split', label: 'Parçala', icon: 'split', group: 'modify', section: 'edge', methods: [{ label: 'Kesişimlerden' }, { label: 'Eşit parçalara', option: 'E', description: 'Nesneyi verilen sayıda eşit uzunlukta parçaya ayırır' }, { label: 'Uzunluktan', option: 'U', description: 'Başından verilen uzunlukta parçalara ayırır' }], aliases: ['PARCALA', 'SPLIT', 'OBJEBOL'], description: 'Çizgileri birbirini kestikleri yerlerden, eşit parçalara ya da verilen uzunluklarda ayrı nesnelere ayırır; yaylar yay kalır.', steps: ['Üstteki “Kesişimlerden” için birbirini kesen çizgileri seçin (pencereyle de olur); kesişimler önizlenir, sağ tıklayınca ayrılır.', '“Eşit parçalara” için nesneye tıklayın, parça sayısını yazıp Enter’a basın; sağ tıklayınca ya da Enter’la bölünür.', '“Uzunluktan” için nesneye tıklayın (ölçme yakın uçtan başlar), parça uzunluğunu yazıp Enter’a basın.'], productCommand: entitiesEdit.id, create: (c) => new SplitTool(c) },
  { id: 'join', label: 'Birleştir', icon: 'join', group: 'modify', section: 'object', shortcut: 'J', aliases: ['J', 'JOIN', 'BIRLESTIR'], description: 'Uç uca gelen çizgi, yay ve çoklu çizgileri tek çoklu çizgiye; kapanırsa kapalı alana çevirir.', steps: ['Uç uca gelen çizgi, yay ve çoklu çizgileri seçin (pencereyle de olur).', 'Sağ tıklayın: tek çoklu çizgi olur; kapanıyorsa kapalı alan.'], productCommand: entitiesEdit.id, create: (c) => new JoinTool(c) },
  { id: 'explode', label: 'Patlat', icon: 'explode', group: 'modify', section: 'object', shortcut: 'X', aliases: ['X', 'EXPLODE', 'PATLAT', 'AYRISTIR'], description: 'Çoklu çizgi ve alanı çizgi ve yaylara, eğriyi çoklu çizgiye, ölçüyü çizgi ve yazıya, blok yerleştirmesini bloğun nesnelerine ayırır.', steps: ['Patlatılacak nesneleri seçin.', 'Sağ tıklayın.'], productCommand: entitiesEdit.id, create: (c) => new ExplodeTool(c) },
  { id: 'fillet', primary: true, family: 'corner', label: 'Köşe yuvarla', icon: 'fillet', group: 'modify', section: 'corner', shortcut: 'Shift+F', aliases: ['F', 'FILLET', 'YUVARLA', 'KOSEYUVARLAT'], description: 'İki çizgiyi ya da çoklu çizginin komşu iki kenarını yarıçaplı yayla (0: keskin köşe) birleştirir.', steps: ['Yuvarlanacak köşeye tıklayın: çoklu çizgi köşesi ya da iki çizginin birleştiği uç.', 'Fareyi kenar boyunca uzaklaştırın; yay canlı büyür. Tıklayınca uygulanır.', 'Tam değer için yarıçapı yazın, son değer için sağ tıklayın. Birleşmeyen iki çizgide sırayla iki çizgiye tıklayın.'], productCommand: entitiesEdit.id, create: (c) => new FilletTool(c) },
  { id: 'chamfer', family: 'corner', label: 'Pah', icon: 'chamfer', group: 'modify', section: 'corner', shortcut: 'Shift+P', aliases: ['CHA', 'CHAMFER', 'PAH'], description: 'Köşeyi iki mesafeyle keser: iki çizgi ya da çoklu çizginin komşu kenarları (imar köşe kesmesi).', steps: ['Kesilecek köşeye tıklayın: çoklu çizgi köşesi ya da iki çizginin birleştiği uç.', 'Fareyi kenar boyunca uzaklaştırın; kesim canlı gösterilir. Tıklayınca uygulanır.', 'Tam değer için d ya da d1,d2 yazın, son değer için sağ tıklayın.'], productCommand: entitiesEdit.id, create: (c) => new ChamferTool(c) },
  { id: 'filletAll', family: 'corner', label: 'Tüm köşeleri yuvarla', icon: 'filletAll', group: 'modify', section: 'corner', aliases: ['TUMKOSELERIYUVARLA', 'YUVARLAHEPSI', 'FILLETALL'], description: 'Seçili çoklu çizgi ve alanların bütün köşelerini aynı yarıçapla yuvarlar; sığmayan köşe atlanır ve söylenir.', steps: ['Çoklu çizgi ya da alanları seçin (pencereyle de olur) ve sağ tıklayın.', 'Yarıçapı yazıp Enter’a basın; yuvarlanan köşeler canlı görünür, sığmayan köşeler atlanır.', 'Sağ tıklayın ya da çizime tıklayın: hepsi tek adımda uygulanır.'], productCommand: entitiesEdit.id, create: (c) => new FilletAllTool(c) },
  { id: 'chamferAll', family: 'corner', label: 'Tüm köşelere pah', icon: 'chamferAll', group: 'modify', section: 'corner', aliases: ['TUMKOSELEREPAH', 'PAHHEPSI', 'CHAMFERALL'], description: 'Seçili çoklu çizgi ve alanların bütün köşelerini aynı mesafeyle keser; sığmayan köşe atlanır ve söylenir.', steps: ['Çoklu çizgi ya da alanları seçin (pencereyle de olur) ve sağ tıklayın.', 'Mesafeyi yazıp Enter’a basın (d ya da d1,d2); kesilen köşeler canlı görünür.', 'Sağ tıklayın ya da çizime tıklayın: hepsi tek adımda uygulanır.'], productCommand: entitiesEdit.id, create: (c) => new ChamferAllTool(c) },
  { id: 'vertex', rare: true, label: 'Köşe ekle/sil', icon: 'vertex', group: 'modify', section: 'corner', shortcut: 'V', aliases: ['KOSE', 'VERTEX'], description: 'Kenara tıklayınca köşe ekler, köşeye tıklayınca siler.', steps: ['Kenar üzerinde bir yere tıklayın: köşe eklenir.', 'Bir köşeye tıklayın: köşe silinir.', 'İmleç yanındaki + ya da × ne olacağını gösterir.'], productCommand: entitiesEdit.id, create: (c) => new VertexTool(c) },
  { id: 'erase', label: 'Sil', icon: 'erase', group: 'modify', section: 'object', shortcut: 'Delete', aliases: ['E', 'ERASE', 'SIL'], description: 'Seçili nesneleri siler; seçim yoksa tıklanan nesneyi siler.', steps: ['Silinecek nesneye tıklayın.', 'Önceden seçim yaptıysanız Del hemen siler.'], productCommand: entitiesDelete.id, create: (c) => new EraseTool(c) },
  { id: 'readable', label: 'Okunur yap', icon: 'readable', group: 'modify', section: 'object', aliases: ['OKUNURYAP', 'MAKEREADABLE', 'OKY'], description: 'Ters okunan yazıları (90°–270° dönük) kutularının ortası çevresinde yarım çevirir; kutu yerinde kalır, hiza korunur.', steps: ['Çevrilecek yazıları seçin (pencereyle de olur).', 'Sağ tıklayın: ters okunanlar okunur olur, okunanlar kalır. Önceden seçiliyse hemen çevrilir.'], productCommand: entitiesEdit.id, create: (c) => new ReadableTool(c) },
  { id: 'reverse', label: 'Yönü çevir', icon: 'reverse', group: 'modify', section: 'object', aliases: ['REVERSE', 'YONCEVIR', 'TERSCEVIR'], description: 'Çizgi, yay, çoklu çizgi, eğri ve alanın çizim yönünü tersine çevirir; biçimi ve yeri değişmez.', steps: ['Yönü çevrilecek çizgi, çoklu çizgi, eğri ya da alanları seçin.', 'Oklar yeni yönü gösterir; sağ tıklayınca çevrilir. Önceden seçiliyse hemen çevrilir.'], productCommand: entitiesEdit.id, create: (c) => new ReverseTool(c) },
  { id: 'simplify', rare: true, label: 'Sadeleştir', icon: 'simplify', group: 'modify', section: 'object', aliases: ['SADELESTIR', 'SIMPLIFY'], description: 'Çoklu çizgi ve alandan, verilen uzaklıktan daha az sapan köşeleri atar; atılan köşe sayısı ve en büyük sapma söylenir.', steps: ['Çoklu çizgi ya da alanları seçin ve sağ tıklayın.', 'Toleransı metre olarak yazıp Enter’a basın; atılacak köşeler işaretlenir.', 'Sağ tıklayın ya da çizime tıklayın: atılan köşe sayısı ve en büyük sapma söylenir.'], productCommand: entitiesEdit.id, create: (c) => new SimplifyTool(c) },
  { id: 'cleanup', rare: true, label: 'Çizimi temizle', icon: 'cleanup', group: 'modify', section: 'object', aliases: ['TEMIZLE', 'CLEANUP', 'OVERKILL'], description: 'Üst üste binen yinelenen nesneleri, sıfır uzunluklu nesneleri ve art arda tekrarlanan köşeleri bulur; önce gösterir, onayla tek adımda temizler.', steps: ['Seçim yoksa bütün çizim taranır; kapsamı daraltmak için nesneleri seçin.', 'Bulunan yinelenen ve boş nesneler ile tekrarlanan köşeler işaretlenir.', 'Enter’a basın ya da sağ tıklayın: hepsi tek adımda temizlenir.'], productCommand: entitiesEdit.id, create: (c) => new CleanupTool(c) },
  { id: 'matchProperties', label: 'Özellik kopyala', icon: 'matchProperties', group: 'modify', section: 'object', aliases: ['MA', 'MATCHPROP', 'OZELLIKKOPYALA', 'STILKOPYALA', 'BICIMBOYA'], description: 'Bir nesnenin katmanını, rengini, çizgi kalınlığını ve sembolünü tıklanan öbür nesnelere verir.', steps: ['Özellikleri alınacak kaynak nesneye tıklayın.', 'Özellikleri alacak nesnelere tıklayın ya da pencereyle seçin; her tıklama bir adımdır.', 'Katman, renk, çizgi kalınlığı ve sembol geçer; öznitelik ve etiket geçmez. Sağ tıklayarak bitirin.'], productCommand: entitiesSet.id, create: (c) => new MatchPropertiesTool(c) },
  { id: 'setElevation', label: 'Kot ver', icon: 'setElevation', group: 'modify', section: 'elevation', methods: [{ label: 'Sabit' }, { label: 'Artır', option: 'A', description: 'Her köşenin kotuna yazılan farkı ekler; kotsuz köşe kotsuz kalır' }, { label: 'Sıfırla', option: 'S', description: 'Köşelerin kotunu siler: kot yok, 0 değil' }], aliases: ['KOTVER', 'KTV', 'SETELEVATION'], description: 'Seçili çizgi, çoklu çizgi, alan ve noktaların köşelerine kot verir: hepsine aynı değer, var olana fark ya da kotu silme.', steps: ['Nesneleri seçin (önce ya da araç açıkken), sonra sağ tıklayın ya da Enter’a basın.', 'Kotu metre olarak yazıp Enter’a basın; “Artır” yazılan farkı ekler, “Sıfırla” kotları siler.', 'Tek adımda yazılır; kilitli katmandaki nesne yazılmaz.'], productCommand: entitiesEdit.id, create: (c) => new ElevationTool(c) },

  // Alan işlemleri
  { id: 'boundary', primary: true, label: 'İçine tıklayarak alan', icon: 'boundary', group: 'area', section: 'create', shortcut: 'Shift+B', aliases: ['BO', 'BPOLY', 'BOUNDARY', 'ALANOLUSTUR'], description: 'Çizgilerle çevrili bölgenin içine tıklayınca o bölge alan olur; içteki kapalı şekiller ada (delik) olur.', steps: ['Alanı oluşturulacak bölgenin içine tıklayın; oluşacak alan önceden boyanır ve alanı yazılır.', '“Adalar” içteki kapalı şekillerin delik olup olmayacağını seçer.', '“Sınır katmanı” ile yalnızca bir katmanın çizgileri sınır sayılır (ör. eşyükseltiler hariç tutulur).'], productCommand: entitiesCreate.id, create: (c) => new BoundaryTool(c) },
  { id: 'toArea', label: 'Alana çevir', icon: 'toArea', group: 'area', section: 'create', shortcut: 'Alt+G', aliases: ['REG', 'REGION', 'ALANACEVIR'], description: 'Kapalı çoklu çizgi, daire, elips ve kapalı eğriyi alana çevirir; kapalı bölge oluşturan çizgilerden alan üretir.', steps: ['Nesneleri seçin (pencereyle de olur).', 'Sağ tıklayın: kapalı nesneler alana dönüşür; çizgilerin çevrelediği her bölge yeni bir alan olur, çizgiler yerinde kalır.'], productCommand: entitiesEdit.id, create: (c) => new ToAreaTool(c) },
  { id: 'areaUnion', primary: true, label: 'Alan birleştir', icon: 'areaUnion', group: 'area', section: 'boolean', shortcut: 'Alt+B', aliases: ['UNI', 'UNION', 'ALANBIRLESTIR', 'TEVHIT'], description: 'Seçili alanları tek alanda birleştirir (tevhit): ortak sınırlar kalkar, köşe koordinatları aynen korunur.', steps: ['Birleştirilecek alanları seçin; ilk seçilen alan katmanını ve özniteliklerini verir.', 'Sağ tıklayın.'], productCommand: entitiesEdit.id, create: (c) => new AreaUnionTool(c) },
  { id: 'areaIntersect', primary: true, label: 'Alan kesiştir', icon: 'areaIntersect', group: 'area', section: 'boolean', shortcut: 'Alt+K', aliases: ['INT', 'INTERSECT', 'KESISTIR'], description: 'Seçili alanların ortak parçasını yeni bir alan olarak çıkarır; kaynaklar yerinde kalır.', steps: ['Kesiştirilecek alanları seçin.', 'Sağ tıklayın: ortak parça yeni alan olur ve alanı yazılır.', '“Kaynakları sil” açıkken seçilen alanlar silinir.'], productCommand: entitiesEdit.id, create: (c) => new AreaIntersectTool(c) },
  { id: 'areaSubtract', primary: true, label: 'Alan çıkar', icon: 'areaSubtract', group: 'area', section: 'boolean', shortcut: 'Alt+C', aliases: ['SU', 'SUBTRACT', 'CIKAR'], description: 'Alanlardan başka alanları çıkarır; tamamen içte kalan alan ada (delik) olur.', steps: ['Kesilecek alanları seçip sağ tıklayın.', 'Çıkarılacak alanları seçip sağ tıklayın.', '“Çıkarılanları sil” açıkken çıkarılan alanlar da silinir.'], productCommand: entitiesEdit.id, create: (c) => new AreaSubtractTool(c) },
  { id: 'partsJoin', label: 'Parçaları birleştir', icon: 'partsJoin', group: 'area', section: 'boolean', aliases: ['PARCABIRLESTIR', 'PARCALARIBIRLESTIR'], description: 'Seçili alanları tek, çok parçalı alan yapar: örtüşenler tek parçada birleşir, parçalar büyükten küçüğe dizilir; ilk seçilen alan yerini, kimliğini ve özniteliklerini verir.', steps: ['Birleştirilecek alanları seçin; ilk seçilen alan yerini ve özniteliklerini verir.', 'Sağ tıklayın.'], productCommand: entitiesEdit.id, create: (c) => new PartsJoinTool(c) },
  { id: 'partsSplit', label: 'Parçalara ayır', icon: 'partsSplit', group: 'area', section: 'boolean', aliases: ['PARCALARAAYIR', 'PARCAAYIR'], description: 'Çok parçalı alanı her parçası için bir alana ayırır: ilk parça alanın yerinde kalır, öbürleri öznitelikleriyle yeni alan olur.', steps: ['Ayrılacak çok parçalı alanları seçin.', 'Sağ tıklayın.'], productCommand: entitiesEdit.id, create: (c) => new PartsSplitTool(c) },
  { id: 'areaSplit', primary: true, label: 'Alan böl', icon: 'areaSplit', group: 'area', section: 'boolean', shortcut: 'Alt+L', aliases: ['SLICE', 'ALANBOL'], description: 'Alanı çizilen ya da gösterilen çizgi boyunca parçalara ayırır; parçalar ve alanları canlı görünür.', steps: ['Bölünecek alanları seçip sağ tıklayın.', 'Kesme çizgisinin noktalarına tıklayın; parçalar ve alanları canlı görünür. Sağ tık uygular.', '“Çizgiyle kes” ile var olan bir çizgiye tıklayarak kesin.'], productCommand: entitiesEdit.id, create: (c) => new AreaSplitTool(c) },
  { id: 'toPolyline', rare: true, label: 'Çizgiye çevir', icon: 'toPolyline', group: 'area', section: 'create', aliases: ['ALANCIZGI', 'CIZGIYECEVIR'], description: 'Alanı kapalı çoklu çizgiye çevirir; delikler ayrı çizgi olur.', steps: ['Çizgiye çevrilecek alanları seçin.', 'Sağ tıklayın.'], productCommand: entitiesEdit.id, create: (c) => new ToPolylineTool(c) },

  // Harita
  { id: 'parcel', primary: true, label: 'Parsel oluştur', icon: 'parcel', group: 'map', section: 'parcel', shortcut: 'Alt+P', aliases: ['PARSEL'], description: 'Köşe noktalarından parsel çizer ve numaralar; tapu alanı çizimden hesaplanmaz, tapudan girilir.', steps: ['Parsel köşelerine sırayla tıklayın.', 'İlk köşeye ya da sağ tıklayın: parsel numaralanır ve seçilir.', 'Ada, mahalle ve tapu alanını Öznitelikler panelinden girin.'], productCommand: entitiesCreate.id, create: (c) => new PathTool(c, { id: 'parcel', label: 'Parsel', closed: true, parcelLayer: LAYERS.parcel }) },
  { id: 'subdivide', label: 'İfraz', icon: 'subdivide', group: 'map', section: 'parcel', shortcut: 'Alt+I', aliases: ['IFRAZ'], description: 'Parseli verilen alan ya da doğrultuya göre böler.' },
  { id: 'stakeout', label: 'Aplikasyon', icon: 'stakeout', group: 'map', section: 'field', shortcut: 'Alt+A', aliases: ['APL'], description: 'Seçili noktalar için istasyondan semt ve mesafe hesaplar.' },
  { id: 'spot', primary: true, label: 'Kot noktası', icon: 'spot', group: 'map', section: 'field', shortcut: 'Alt+Z', aliases: ['KOT'], description: 'Kot değeri girilerek yükseklik noktası ekler.', steps: ['Kot noktasının yerine tıklayın.', 'Kot değerini yazıp Enter’a basın.'], productCommand: pointCreate.id, create: (c) => new PointTool(c, { id: 'spot', label: 'Kot noktası', askZ: true, layerId: LAYERS.spot }) },
  { id: 'measure', label: 'Mesafe ölç', icon: 'measure', group: 'map', section: 'measure', shortcut: 'Alt+M', aliases: ['DI', 'DIST', 'MESAFE', 'CETVEL'], description: 'Noktalar arası kenar uzunluğu ve semt açısını ölçer; “Sabit ilk nokta” açıkken her noktayı ilk noktadan ölçer.', steps: ['Ölçülecek noktalara sırayla tıklayın; uzunluk ve semt imleç yanında görünür.', 'Sağ tıklayın: toplam uzunluk mesaj satırına yazılır.', '“Sabit ilk nokta” açıkken her nokta ilk noktadan ölçülür: her tık iletiye “n: mesafe, semt” yazar, toplam yazılmaz.'], create: (c) => new DistanceTool(c) },
  { id: 'area', label: 'Alan hesapla', icon: 'area', group: 'map', section: 'measure', shortcut: 'Alt+H', aliases: ['AA', 'AREA', 'ALANSOR'], description: 'Tıklanan köşelerden ya da içine tıklanan bölgeden alan ve çevre hesaplar; ölçülen alan istenirse alan olarak çizilir.', steps: ['Alanın köşelerine tıklayın.', 'İlk köşeye ya da sağ tıklayın: alan ve çevre mesaj satırına yazılır.', '“İçine tıkla” açıkken çizgilerle çevrili bölgenin içine tıklamak yeter; içteki kapalı şekiller delik sayılır.', '“Alan olarak çiz” son ölçülen alanı, delikleriyle, etkin katmana kapalı alan olarak yazar (tek adım).'], productCommand: polygonCreate.id, create: (c) => new AreaMeasureTool(c) },
  { id: 'measureAngle', label: 'Açı ölç', icon: 'measureAngle', group: 'map', section: 'measure', aliases: ['ACIOLC', 'ANGLE', 'ACI'], description: 'Bir tepe noktası ve iki koldan açıyı ölçer; projenin açı biriminde ve dış açısıyla yazar.', steps: ['Açının tepe noktasına tıklayın.', 'Birinci ve ikinci kolun bir noktasına tıklayın; açı ve dış açısı canlı yazılır.', 'Sonuç iletiye gider; araç yeniden sorar. Çizime bir şey yazılmaz.'], create: (c) => new MeasureAngleTool(c) },
  { id: 'stationOffset', label: 'Dik ayak ölç', icon: 'stationOffset', group: 'map', section: 'measure', aliases: ['PRIZMA', 'DIKAYAKOLC', 'STATIONOFFSET'], description: 'Noktaların bir hatta göre dik ayağını ve dik boyunu ölçer (sağa artı); çizime yazmaz, iletiye yazar.', steps: ['Hattın başına (A), sonra sonuna (B) tıklayın.', 'Ölçülecek noktalara tıklayın: dik ayak ve dik boy imleç yanında görünür, her tık iletiye yazılır.', '“Başka hat” yeni hat seçtirir; sağ tık ya da Enter bitirir.'], create: (c) => new StationOffsetTool(c) },
];

export const TOOL_CATALOG: ToolDescriptor[] = defs.map((d) => ({
  ...d,
  ready: !!d.create,
  create: d.create ?? (() => new PendingTool(d.id, d.label)),
}));
