import { TextTool } from './annotateTools';
import { DimensionTool } from './dimensionTool';
import { HatchTool } from './hatchTool';
import { ArcTool, CircleTool, SplineTool } from './curveTools';
import { RayTool, XlineTool } from './constructionTools';
import { EllipseTool } from './ellipseTool';
import { EraseTool, LineTool, PendingTool, PointTool } from './drawTools';
import { PathTool } from './pathTool';
import { DonutTool, RevCloudTool } from './markupTools';
import { RectangleTool, RegularPolygonTool, RotatedRectangleTool } from './shapeTools';
import { ChamferTool, FilletTool } from './cornerTools';
import { ExtendTool, OffsetTool, TrimTool } from './edgeTools';
import { BreakTool, DivideTool, VertexTool } from './pathEditTools';
import { ExplodeTool, JoinTool, StretchTool } from './editTools';
import { ArrayTool, MirrorTool, MoveTool, RotateTool, ScaleTool } from './modifyTools';
import { ParallelLineTool } from './parallelTool';
import { AlignTool, PolarArrayTool } from './arrangeTools';
import { LengthenTool } from './lengthenTool';
import { PerpendicularInTool, PerpendicularOutTool } from './perpTools';
import { AreaIntersectTool, AreaSplitTool, AreaSubtractTool, AreaUnionTool, BoundaryTool, ToAreaTool, ToPolylineTool } from './areaTools';
import { PanTool, SelectTool, ZoomWindowTool } from './SelectTool';
import type { ToolDescriptor } from './Tool';

/** Layers the map tools write to (project template; new layers otherwise). */
const LAYERS = { parcel: 'parsel', spot: 'kot' };

type Def = Omit<ToolDescriptor, 'create' | 'ready'> & Partial<Pick<ToolDescriptor, 'create'>>;


/**
 * Every tool in one declarative list. Toolbox, classic menus, the ribbon,
 * shortcuts and the command line are all generated from this — add a tool
 * here (with its group and, in a sectioned group, its section) and it
 * shows up everywhere; no menu or ribbon file lists tools one by one.
 */
const defs: Def[] = [
  // Seçim
  { id: 'select', label: 'Seç', icon: 'select', group: 'select', shortcut: 'Esc', aliases: ['SEC', 'SELECT'], description: 'Nesne seçer. Sürükleyerek pencere ya da kesişim seçimi yapın.', steps: ['Nesneye tıklayın; Shift+tık seçime ekler ya da çıkarır.', 'Soldan sağa sürükleyin: tamamen içeride kalanlar seçilir. Sağdan sola: dokunan her şey seçilir.', 'Seçili nesnenin kare tutamacını sürükleyin: köşe taşınır. Kenar ortasındaki baklava yeni köşe ekler.'], create: (c) => new SelectTool(c) },
  { id: 'zoomWindow', label: 'Pencere yakınlaştır', icon: 'zoomWindow', group: 'select', shortcut: 'Z', aliases: ['Z', 'ZOOM', 'PENCERE'], description: 'Çizilen dikdörtgene yakınlaştırır.', steps: ['Yakınlaşılacak alanın bir köşesine tıklayın.', 'Karşı köşeye tıklayın ya da sürükleyin.'], create: (c) => new ZoomWindowTool(c) },
  { id: 'pan', label: 'Kaydır', icon: 'pan', group: 'select', shortcut: 'Shift+H', aliases: ['PAN', 'KAYDIR'], description: 'Görünümü sürükler. Orta tuşla her araçta kullanılabilir.', steps: ['Sürükleyerek görünümü kaydırın.', 'Her araçta orta tuşla sürüklemek de kaydırır, tekerlek yakınlaştırır.'], create: (c) => new PanTool(c) },

  // Çizim
  { id: 'point', label: 'Nokta', icon: 'point', group: 'draw', section: 'point', shortcut: 'N', aliases: ['PO', 'POINT', 'NOKTA'], description: 'Tek tek nokta yerleştirir.', steps: ['Noktanın konacağı her yere tıklayın.', 'Sağ tık ya da Esc: araçtan çıkın.'], create: (c) => new PointTool(c, { id: 'point', label: 'Nokta', askZ: false }) },
  { id: 'line', label: 'Çizgi', icon: 'line', group: 'draw', section: 'line', shortcut: 'L', aliases: ['L', 'LINE', 'CIZGI'], description: 'Uç uca bağlı çizgi parçaları çizer.', steps: ['İlk noktaya tıklayın.', 'Sonraki noktalara tıklayın; her tık bir çizgi ekler.', 'Sağ tık: bitir. “Geri” son parçayı geri alır, “Kapat” ilk noktaya döner.'], create: (c) => new LineTool(c) },
  { id: 'polyline', label: 'Çoklu çizgi', icon: 'polyline', group: 'draw', section: 'line', shortcut: 'P', aliases: ['PL', 'PLINE', 'COKLUCIZGI'], description: 'Tek parça, açık çoklu çizgi çizer; Y ile yay parçası (teğet, açı, merkez, yarıçap, ikinci nokta, doğrultu), D ile düz parça, U ile son doğrultuda uzunluk.', steps: ['İlk noktaya, sonra köşelere tıklayın.', '“Yay” ile yay parçasına geçin; yay teğet devam eder ya da “Açı”, “Merkez”, “Yarıçap”, “İkinci nokta”, “Doğrultu” ile tek parça için biçimlenir. “Düz” düze döner.', 'Sağ tık: bitir. “Geri” son köşeyi siler, “Uzunluk” son doğrultuda yazılan boyda devam eder.'], create: (c) => new PathTool(c, { id: 'polyline', label: 'Çoklu çizgi', closed: false }) },
  { id: 'polygon', label: 'Kapalı alan', icon: 'polygon', group: 'draw', section: 'line', shortcut: 'G', aliases: ['KA', 'ALAN', 'POLYGON'], description: 'Kapalı çoklu çizgi (alan) çizer.', steps: ['Köşelere sırayla tıklayın; alan imleç yanında görünür.', 'Sağ tık: alanı kapatıp bitirir.'], create: (c) => new PathTool(c, { id: 'polygon', label: 'Kapalı alan', closed: true }) },
  { id: 'parallel', label: 'Paralel çizgi', icon: 'parallel', group: 'draw', section: 'line', shortcut: 'Y', aliases: ['PARALEL', 'PC', 'ML', 'MLINE', 'DLINE'], description: 'Ekseni çizerken sağında ve solunda verilen mesafelerde paralel hatlar çizer (yol, kaldırım, duvar); istenirse arası tek alan olur.', steps: ['“Sol” ve “Sağ” ile mesafeleri yazın ya da iki noktaya tıklayarak gösterin.', 'Eksenin noktalarına tıklayın; paralel hatlar köşelerde birleşerek canlı çizilir.', 'Sağ tık bitirir, “Kapat” ekseni kapatır. “Eksen” ekseni çizip çizmemeyi, “Alan olarak” koridoru tek alan yapmayı seçer.'], create: (c) => new ParallelLineTool(c) },
  { id: 'rectangle', label: 'Dikdörtgen', icon: 'rectangle', group: 'draw', section: 'shape', shortcut: 'R', aliases: ['REC', 'RECTANGLE', 'DIKDORTGEN'], description: 'İki karşı köşeden dikdörtgen çizer; döndürme açısı, tam boyut, köşe yuvarlama ve pah seçenekleriyle.', steps: ['Bir köşeye tıklayın (önce “Köşe yuvarla” ya da “Pah” ile köşe biçimini seçebilirsiniz).', 'Karşı köşeye tıklayın.', '“Döndür” ile açı, “Boyutlar” ile uzunluk,genişlik yazıp yönü tıklayarak gösterin.'], create: (c) => new RectangleTool(c) },
  { id: 'rectangle3', label: 'Döndürülmüş dikdörtgen', icon: 'rectangle3', group: 'draw', section: 'shape', shortcut: 'Alt+R', aliases: ['REC3', 'DDIKDORTGEN', 'UCNOKTADIKDORTGEN'], description: 'Önce bir kenar çizilir, sonra yana çekilerek genişlik verilir; her açıda dikdörtgen.', steps: ['Kenarın ilk noktasına tıklayın.', 'Kenarın ikinci noktasına tıklayın ya da uzunluk yazın (kenet, izleme ve orto çalışır).', 'Fareyi kenardan yana çekip tıklayın ya da genişliği yazın.'], create: (c) => new RotatedRectangleTool(c) },
  { id: 'regularPolygon', label: 'Düzgün çokgen', icon: 'regularPolygon', group: 'draw', section: 'shape', shortcut: 'Shift+G', aliases: ['POL', 'POLYGON3', 'COKGEN'], description: 'Kenar sayısı verilen düzgün çokgen: merkezden (çembere içten ya da dıştan) ya da bir kenardan.', steps: ['Kenar sayısını yazın (varsayılan 6) ya da “Kenar sayısı” düğmesine basın.', 'Merkeze tıklayın; fareyle bir köşeyi (ya da “Çember: kenarlara teğet” ile bir kenar ortasını) gösterip tıklayın.', '“Kenardan” ile bir kenarın iki ucuna tıklayarak çizin; yarıçap yazılırsa alt kenar yatay olur.'], create: (c) => new RegularPolygonTool(c) },
  { id: 'circle', label: 'Daire', icon: 'circle', group: 'draw', section: 'curve', shortcut: 'C', aliases: ['C', 'CIRCLE', 'DAIRE'], description: 'Merkez ve yarıçap ya da çapla; 2N çaptan, 3N üç noktadan, TTY iki nesneye teğet yarıçaplı, TTT üç nesneye teğet daire.', steps: ['Merkeze tıklayın.', 'Çember üzerindeki bir noktaya tıklayın ya da yarıçapı yazın; “Çap” ile çap verilir.', 'Üstteki düğmeler: “2 nokta” çaptan, “3 nokta” üç noktadan, “Teğet-teğet-yarıçap” iki nesneye dokunan daire, “Teğet-teğet-teğet” üç nesneye (teğet olacağı yerlerin yakınından) tıklanarak.'], create: (c) => new CircleTool(c) },
  { id: 'arc', label: 'Yay', icon: 'arc', group: 'draw', section: 'curve', shortcut: 'A', aliases: ['A', 'ARC', 'YAY'], description: 'AutoCAD’in tüm yay yöntemleri: üç nokta; başlangıç-merkez-bitiş/açı/kiriş; başlangıç-bitiş-merkez/açı/yön/yarıçap; merkez-başlangıç; son nesneye teğet devam.', steps: ['Başlangıca, yay üzerindeki bir noktaya ve bitişe tıklayın (üç nokta).', 'Başlangıçtan sonra “Merkez” ya da “Bitiş” düğmesiyle yöntemi seçin; üçüncü adımda “Açı”, “Kiriş”, “Yön”, “Yarıçap” ile değer verin.', 'İlk adımda “Merkez” merkezden başlar, “Devam” son çizgi ya da yaya teğet yay çizer.'], create: (c) => new ArcTool(c) },
  { id: 'ellipse', label: 'Elips', icon: 'ellipse', group: 'draw', section: 'curve', shortcut: 'Shift+L', aliases: ['EL', 'ELLIPSE', 'ELIPS'], description: 'Elips ya da eliptik yay: eksen uçlarından ya da merkezden; diğer yarı eksen uzunlukla ya da döndürme açısıyla.', steps: ['Bir eksenin iki ucuna tıklayın (“Merkez” ile önce merkeze).', 'Fareyle diğer yarı ekseni gösterip tıklayın ya da uzunluğunu yazın; “Döndürme” ile açı yazılır.', '“Yay” açıksa başlangıç ve bitiş açısını gösterin; eliptik yay çizilir.'], create: (c) => new EllipseTool(c) },
  { id: 'spline', label: 'Eğri', icon: 'spline', group: 'draw', section: 'curve', shortcut: 'S', aliases: ['SPL', 'SPLINE', 'EGRI'], description: 'Tıklanan noktalardan geçen yumuşak eğri çizer; K ile kapatır.', steps: ['Eğrinin geçeceği noktalara sırayla tıklayın.', 'Sağ tık: bitir. “Kapat” kapalı eğri yapar.'], create: (c) => new SplineTool(c) },
  { id: 'xline', label: 'Yardımcı çizgi', icon: 'xline', group: 'draw', section: 'construction', shortcut: 'Shift+X', aliases: ['XL', 'XLINE', 'YARDIMCI'], description: 'İki yöne sonsuz yardımcı çizgi: bir noktadan, yatay, düşey, açılı ya da açıortay.', steps: ['Bir noktaya tıklayın, sonra geçeceği her noktaya tıklayın; her tık bir çizgi.', '“Yatay”, “Düşey”, “Açı” düğmeleriyle yön sabitlenir, tıklanan her noktadan geçer.', '“Açıortay”: açının köşesine, sonra iki koluna tıklayın.'], create: (c) => new XlineTool(c) },
  { id: 'ray', label: 'Işın', icon: 'ray', group: 'draw', section: 'construction', shortcut: 'Alt+X', aliases: ['RAY', 'ISIN'], description: 'Bir başlangıç noktasından tek yöne sonsuz yardımcı çizgi.', steps: ['Başlangıç noktasına tıklayın.', 'Işının geçeceği her noktaya tıklayın; sağ tık bitirir.'], create: (c) => new RayTool(c) },
  { id: 'donut', label: 'Halka', icon: 'donut', group: 'draw', section: 'curve', aliases: ['DO', 'DONUT', 'HALKA'], description: 'Dolu halka ya da (iç çap 0 ile) dolu daire koyar; her tıklama bir tane.', steps: ['“İç çap” ve “Dış çap” ile ölçüleri yazın.', 'Halkanın merkezine tıklayın; araç sonrakini bekler.'], create: (c) => new DonutTool(c) },
  { id: 'perpIn', label: 'Dik in', icon: 'perpIn', group: 'draw', section: 'construction', shortcut: 'I', aliases: ['DIKIN', 'DIK'], description: 'Gösterilen noktalardan bir hatta dik iner (hattın uzantısına da); yay ve dairede merkeze doğru.', steps: ['Referans hatta tıklayın.', 'Dik inilecek her noktaya tıklayın (kenet çalışır); dik boy ve dik ayak imleç yanında görünür.', 'Sağ tık bitirir; “Başka hat” yeni referans seçtirir.'], create: (c) => new PerpendicularInTool(c) },
  { id: 'perpOut', label: 'Dik çık', icon: 'perpOut', group: 'draw', section: 'construction', shortcut: 'O', aliases: ['DIKCIK'], description: 'Hat üzerindeki bir noktadan, verilen dik boyda dik çıkar; dik ayak tıklanan uçtan ölçülür, dik boy sağa artıdır.', steps: ['Referans hatta, başlangıç sayılacak ucuna yakın tıklayın (A).', 'Hat üzerinde dik çıkılacak yere tıklayın ya da A’dan uzaklığı yazın.', 'Dik boyu fareyle gösterip tıklayın ya da yazın (sağa artı, sola eksi).'], create: (c) => new PerpendicularOutTool(c) },
  { id: 'divide', label: 'Böl', icon: 'divide', group: 'draw', section: 'point', shortcut: 'Shift+D', aliases: ['DIV', 'DIVIDE', 'ME', 'MEASURE', 'BOL'], description: 'Nesne boyunca nokta koyar: eşit parçalara ya da A ile verilen aralıkla.', steps: ['Bölünecek çizgi, yay, daire ya da çoklu çizgiye tıklayın.', 'Parça sayısını yazıp Enter’a basın ya da sağ tıklayıp son değeri kullanın.', 'Metre cinsinden aralıkla bölmek için “Aralık” düğmesine basın.'], create: (c) => new DivideTool(c) },

  // Açıklama
  { id: 'text', label: 'Yazı', icon: 'text', group: 'annotate', shortcut: 'T', aliases: ['T', 'TEXT', 'YAZI'], description: 'Tek satır yazı: tıklanan yerde açılan kutuya yazılır. Yükseklik kâğıt mm olarak, açı derece ya da iki noktayla verilir; yazıya çift tıklayarak düzenleyin.', steps: ['Yazının başlayacağı yere tıklayın: orada bir yazı kutusu açılır.', 'Yazıyı yazıp Enter’a basın; Esc vazgeçer. Araç bir sonraki yazı için bekler.', '“Yükseklik” mm, “Açı” derece ya da bir çizgi boyunca iki tıkla verilir. Var olan yazıya çift tıklayarak düzenleyin.'], create: (c) => new TextTool(c) },
  { id: 'dimension', label: 'Ölçülendirme', icon: 'dimension', group: 'annotate', shortcut: 'D', aliases: ['DIM', 'OLCU', 'DIMLIN', 'DIMANG', 'DIMRAD', 'DIMDIA'], description: 'Ölçü ekler: hizalı, doğrusal (ΔY yatay / ΔX düşey), açı, yarıçap ve çap; değer proje birimini izler.', steps: ['Türü üstteki düğmelerden seçin (Hizalı, Doğrusal, Açı, Yarıçap, Çap).', 'Hizalı ve doğrusal: iki noktaya, sonra ölçü çizgisinin yerine tıklayın; doğrusalda yön imlecin yerinden seçilir. Açı: iki kenara (ya da “Köşeden” ile köşe ve iki kola) tıklayın, yayı yerleştirin.', 'Yarıçap ve çap: daireye ya da yaya tıklayın, doğrultuyu gösterin.'], create: (c) => new DimensionTool(c) },
  { id: 'revcloud', label: 'Revizyon bulutu', icon: 'revcloud', group: 'annotate', aliases: ['REVCLOUD', 'BULUT'], description: 'Değişen yeri çevreleyen, dışa bombeli yaylardan kapalı bulut çizer; dikdörtgen ya da çokgen.', steps: ['Dikdörtgenin iki köşesine tıklayın (ya da “Çokgen” ile köşelere tıklayıp sağ tıklayın).', '“Yay boyu” yay uzunluğunu kâğıt milimetresi olarak ayarlar.'], create: (c) => new RevCloudTool(c) },
  { id: 'hatch', label: 'Tarama', icon: 'hatch', group: 'annotate', shortcut: 'H', aliases: ['H', 'HATCH', 'TARAMA'], description: 'Tıklanan kapalı alanı desenle tarar; D ile desen değişir.', steps: ['Taranacak kapalı alanın içine tıklayın.', 'Deseni üstteki “Desen” düğmesiyle değiştirin.'], create: (c) => new HatchTool(c) },

  // Dönüştür
  { id: 'move', label: 'Taşı', icon: 'move', group: 'transform', section: 'move', shortcut: 'Shift+M', aliases: ['M', 'MOVE', 'TASI'], description: 'Seçili nesneleri temel noktadan hedefe taşır.', steps: ['Nesnelere tıklayın ya da pencereyle seçin, sonra sağ tıklayın. Önceden seçiliyse bu adım atlanır.', 'Temel noktaya tıklayın.', 'Hedef noktaya tıklayın.'], create: (c) => new MoveTool(c, { id: 'move', label: 'Taşı', copy: false }) },
  { id: 'copy', label: 'Kopyala', icon: 'copy', group: 'transform', section: 'move', shortcut: 'Shift+C', aliases: ['CO', 'COPY', 'KOPYALA'], description: 'Seçili nesnelerin bir ya da daha fazla kopyasını çıkarır.', steps: ['Nesneleri seçip sağ tıklayın.', 'Temel noktaya tıklayın.', 'Her tık bir kopya bırakır; sağ tıkla bitirin.'], create: (c) => new MoveTool(c, { id: 'copy', label: 'Kopyala', copy: true }) },
  { id: 'rotate', label: 'Döndür', icon: 'rotate', group: 'transform', section: 'move', shortcut: 'Shift+R', aliases: ['RO', 'ROTATE', 'DONDUR'], description: 'Seçili nesneleri bir nokta etrafında döndürür. Açı yazılabilir; K ile kopya.', steps: ['Nesneleri seçip sağ tıklayın.', 'Dönme merkezine tıklayın.', 'Açıyı fareyle gösterip tıklayın ya da derece yazın. “Kopya” açıkken asıl nesne yerinde kalır.'], create: (c) => new RotateTool(c) },
  { id: 'scale', label: 'Ölçekle', icon: 'scale', group: 'transform', section: 'move', shortcut: 'Shift+S', aliases: ['SC', 'SCALE', 'OLCEKLE'], description: 'Seçili nesneleri temel noktaya göre büyütür ya da küçültür: faktör ya da referans uzunluk.', steps: ['Nesneleri seçip sağ tıklayın.', 'Temel noktaya tıklayın.', 'Faktörü yazın ya da referans uzunluğun ucuna, ardından yeni uzunluğa tıklayın.'], create: (c) => new ScaleTool(c) },
  { id: 'mirror', label: 'Aynala', icon: 'mirror', group: 'transform', section: 'move', shortcut: 'Shift+I', aliases: ['MI', 'MIRROR', 'AYNALA'], description: 'Seçili nesnelerin iki noktalı eksene göre simetriğini alır; S ile kaynağı siler.', steps: ['Nesneleri seçip sağ tıklayın.', 'Simetri ekseninin iki noktasına tıklayın.', '“Kaynağı sil” açıkken asıllar yerinde çevrilir.'], create: (c) => new MirrorTool(c) },
  { id: 'stretch', label: 'Esnet', icon: 'stretch', group: 'transform', section: 'move', shortcut: 'E', aliases: ['STR', 'STRETCH', 'ESNET'], description: 'Pencerenin içinde kalan köşeleri taşır; dışındakiler yerinde kalır.', steps: ['Taşınacak köşeleri içine alan pencereyi sürükleyin ya da iki köşesine tıklayın.', 'Temel noktaya tıklayın.', 'Hedefe tıklayın: pencere içindeki köşeler taşınır, dışındakiler yerinde kalır.'], create: (c) => new StretchTool(c) },
  { id: 'array', label: 'Dizi', icon: 'array', group: 'transform', section: 'array', shortcut: 'Shift+A', aliases: ['AR', 'ARRAY', 'DIZI'], description: 'Seçili nesneleri satır ve sütun düzeninde çoğaltır.', steps: ['Nesneleri seçip sağ tıklayın.', 'Satır ve sütun sayısını yazın (ör. 2,3) ya da sağ tıklayıp son değeri kullanın.', 'Aralığı iki noktaya tıklayarak gösterin ya da dY,dX yazın.'], create: (c) => new ArrayTool(c) },

  { id: 'arrayPolar', label: 'Kutupsal dizi', icon: 'arrayPolar', group: 'transform', section: 'array', aliases: ['ARPO', 'ARRAYPOLAR', 'KDIZI', 'KUTUPSALDIZI'], description: 'Seçili nesneleri bir merkez çevresinde çoğaltır: adet, doldurma açısı, nesneler dönsün ya da dönmesin.', steps: ['Nesneleri seçip sağ tıklayın.', 'Merkeze tıklayın; kopyalar canlı görünür.', '“Adet”, “Açı” (360 tam tur, eksi saat yönünde) ve “Nesneleri döndür” ile ayarlayıp sağ tıklayın.'], create: (c) => new PolarArrayTool(c) },
  { id: 'align', label: 'Hizala', icon: 'align', group: 'transform', section: 'move', aliases: ['AL', 'ALIGN', 'HIZALA'], description: 'Seçimi iki nokta çiftiyle yerine oturtur: birinci kaynak birinci hedefe taşınır, ikinci çift yönü (isterseniz ölçeği) verir.', steps: ['Nesneleri seçip sağ tıklayın.', 'Birinci kaynak noktasına, sonra birinci hedef noktasına tıklayın (yalnız taşımak için burada sağ tıklayın).', 'İkinci kaynak ve ikinci hedef noktalarına tıklayın; “Ölçekle” açıkken boy da hedefe uyar.'], create: (c) => new AlignTool(c) },
  // Düzenle
  { id: 'offset', label: 'Ötele', icon: 'offset', group: 'modify', section: 'edge', shortcut: 'Shift+O', aliases: ['O', 'OFFSET', 'OTELE'], description: 'Çizgi, çoklu çizgi, alan, daire ya da yayın paralel kopyasını çıkarır.', steps: ['Ötelenecek nesneye tıklayın.', 'Kopyanın gideceği tarafa tıklayın.', 'Mesafe için sayı yazın; “Noktadan geç” açıkken kopya tıkladığınız noktadan geçer.'], create: (c) => new OffsetTool(c) },
  { id: 'trim', label: 'Buda', icon: 'trim', group: 'modify', section: 'edge', shortcut: 'Shift+T', aliases: ['TR', 'TRIM', 'BUDA'], description: 'Tıklanan parçayı, onu kesen en yakın iki kenar arasında siler.', steps: ['Silinecek parçanın üzerine tıklayın; kırmızı gösterilen kısım gider.', 'Görünen diğer tüm kenarlar kesici sayılır.'], create: (c) => new TrimTool(c) },
  { id: 'extend', label: 'Uzat', icon: 'extend', group: 'modify', section: 'edge', shortcut: 'Shift+E', aliases: ['EX', 'EXTEND', 'UZAT'], description: 'Çizgi ya da yay ucunu ilk rastladığı kenara kadar uzatır.', steps: ['Uzatılacak ucun yakınına tıklayın.', 'Nesne ilk rastladığı kenara kadar uzar.'], create: (c) => new ExtendTool(c) },
  { id: 'lengthen', label: 'Uzat-kısalt', icon: 'lengthen', group: 'modify', section: 'edge', shortcut: 'Shift+U', aliases: ['LEN', 'LENGTHEN', 'UZATKISALT'], description: 'Çizgi, yay ya da açık çoklu çizginin boyunu bir ucundan değiştirir: fareyle, farkla, yüzdeyle ya da toplam uzunlukla.', steps: ['Değişecek ucun yakınına tıklayın.', 'Yeni ucu fareyle gösterin (uzatmada son parça doğrultusunda ya da çemberinde devam eder) ya da toplam uzunluğu yazın.', '“Fark”, “Yüzde”, “Toplam” kiplerinde tıklanan her uç hemen değişir.'], create: (c) => new LengthenTool(c) },
  { id: 'break', label: 'Kır', icon: 'break', group: 'modify', section: 'edge', shortcut: 'B', aliases: ['BR', 'BREAK', 'KIR'], description: 'Nesnenin iki nokta arasındaki kısmını siler; Enter ile tek noktadan böler.', steps: ['Nesneye, kırılacak ilk noktadan tıklayın.', 'İkinci noktaya tıklayın: aradaki kısım silinir.', 'Tek noktadan ikiye bölmek için ikinci tık yerine sağ tıklayın.'], create: (c) => new BreakTool(c) },
  { id: 'join', label: 'Birleştir', icon: 'join', group: 'modify', section: 'object', shortcut: 'J', aliases: ['J', 'JOIN', 'BIRLESTIR'], description: 'Uç uca gelen çizgi, yay ve çoklu çizgileri tek çoklu çizgiye; kapanırsa kapalı alana çevirir.', steps: ['Uç uca gelen çizgi, yay ve çoklu çizgileri seçin (pencereyle de olur).', 'Sağ tıklayın: tek çoklu çizgi olur; kapanıyorsa kapalı alan.'], create: (c) => new JoinTool(c) },
  { id: 'explode', label: 'Patlat', icon: 'explode', group: 'modify', section: 'object', shortcut: 'X', aliases: ['X', 'EXPLODE', 'PATLAT'], description: 'Çoklu çizgi ve alanı çizgi ve yaylara, eğriyi çoklu çizgiye, ölçüyü çizgi ve yazıya ayırır.', steps: ['Patlatılacak nesneleri seçin.', 'Sağ tıklayın.'], create: (c) => new ExplodeTool(c) },
  { id: 'fillet', label: 'Köşe yuvarla', icon: 'fillet', group: 'modify', section: 'corner', shortcut: 'Shift+F', aliases: ['F', 'FILLET', 'YUVARLA'], description: 'İki çizgiyi ya da çoklu çizginin komşu iki kenarını yarıçaplı yayla (0: keskin köşe) birleştirir.', steps: ['Yuvarlanacak köşeye tıklayın: çoklu çizgi köşesi ya da iki çizginin birleştiği uç.', 'Fareyi kenar boyunca uzaklaştırın; yay canlı büyür. Tıklayınca uygulanır.', 'Tam değer için yarıçapı yazın, son değer için sağ tıklayın. Birleşmeyen iki çizgide sırayla iki çizgiye tıklayın.'], create: (c) => new FilletTool(c) },
  { id: 'chamfer', label: 'Pah', icon: 'chamfer', group: 'modify', section: 'corner', shortcut: 'Shift+P', aliases: ['CHA', 'CHAMFER', 'PAH'], description: 'Köşeyi iki mesafeyle keser: iki çizgi ya da çoklu çizginin komşu kenarları (imar köşe kesmesi).', steps: ['Kesilecek köşeye tıklayın: çoklu çizgi köşesi ya da iki çizginin birleştiği uç.', 'Fareyi kenar boyunca uzaklaştırın; kesim canlı gösterilir. Tıklayınca uygulanır.', 'Tam değer için d ya da d1,d2 yazın, son değer için sağ tıklayın.'], create: (c) => new ChamferTool(c) },
  { id: 'vertex', label: 'Köşe ekle/sil', icon: 'vertex', group: 'modify', section: 'corner', shortcut: 'V', aliases: ['KOSE', 'VERTEX'], description: 'Kenara tıklayınca köşe ekler, köşeye tıklayınca siler.', steps: ['Kenar üzerinde bir yere tıklayın: köşe eklenir.', 'Bir köşeye tıklayın: köşe silinir.', 'İmleç yanındaki + ya da × ne olacağını gösterir.'], create: (c) => new VertexTool(c) },
  { id: 'erase', label: 'Sil', icon: 'erase', group: 'modify', section: 'object', shortcut: 'Delete', aliases: ['E', 'ERASE', 'SIL'], description: 'Seçili nesneleri siler; seçim yoksa tıklanan nesneyi siler.', steps: ['Silinecek nesneye tıklayın.', 'Önceden seçim yaptıysanız Del hemen siler.'], create: (c) => new EraseTool(c) },

  // Alan işlemleri
  { id: 'boundary', label: 'İçine tıklayarak alan', icon: 'boundary', group: 'area', section: 'create', shortcut: 'Shift+B', aliases: ['BO', 'BPOLY', 'BOUNDARY', 'ALANOLUSTUR'], description: 'Çizgilerle çevrili bölgenin içine tıklayınca o bölge alan olur; içteki kapalı şekiller ada (delik) olur.', steps: ['Alanı oluşturulacak bölgenin içine tıklayın; oluşacak alan önceden boyanır ve alanı yazılır.', '“Adalar” içteki kapalı şekillerin delik olup olmayacağını seçer.', '“Sınır katmanı” ile yalnızca bir katmanın çizgileri sınır sayılır (ör. eşyükseltiler hariç tutulur).'], create: (c) => new BoundaryTool(c) },
  { id: 'toArea', label: 'Alana çevir', icon: 'toArea', group: 'area', section: 'create', shortcut: 'Alt+G', aliases: ['REG', 'REGION', 'ALANACEVIR'], description: 'Kapalı çoklu çizgi, daire, elips ve kapalı eğriyi alana çevirir; kapalı bölge oluşturan çizgilerden alan üretir.', steps: ['Nesneleri seçin (pencereyle de olur).', 'Sağ tıklayın: kapalı nesneler alana dönüşür; çizgilerin çevrelediği her bölge yeni bir alan olur, çizgiler yerinde kalır.'], create: (c) => new ToAreaTool(c) },
  { id: 'areaUnion', label: 'Alan birleştir', icon: 'areaUnion', group: 'area', section: 'boolean', shortcut: 'Alt+B', aliases: ['UNI', 'UNION', 'ALANBIRLESTIR', 'TEVHIT'], description: 'Seçili alanları tek alanda birleştirir (tevhit): ortak sınırlar kalkar, köşe koordinatları aynen korunur.', steps: ['Birleştirilecek alanları seçin; ilk seçilen alan katmanını ve özniteliklerini verir.', 'Sağ tıklayın.'], create: (c) => new AreaUnionTool(c) },
  { id: 'areaIntersect', label: 'Alan kesiştir', icon: 'areaIntersect', group: 'area', section: 'boolean', shortcut: 'Alt+K', aliases: ['INT', 'INTERSECT', 'KESISTIR'], description: 'Seçili alanların ortak parçasını yeni bir alan olarak çıkarır; kaynaklar yerinde kalır.', steps: ['Kesiştirilecek alanları seçin.', 'Sağ tıklayın: ortak parça yeni alan olur ve alanı yazılır.', '“Kaynakları sil” açıkken seçilen alanlar silinir.'], create: (c) => new AreaIntersectTool(c) },
  { id: 'areaSubtract', label: 'Alan çıkar', icon: 'areaSubtract', group: 'area', section: 'boolean', shortcut: 'Alt+C', aliases: ['SU', 'SUBTRACT', 'CIKAR'], description: 'Alanlardan başka alanları çıkarır; tamamen içte kalan alan ada (delik) olur.', steps: ['Kesilecek alanları seçip sağ tıklayın.', 'Çıkarılacak alanları seçip sağ tıklayın.', '“Çıkarılanları sil” açıkken çıkarılan alanlar da silinir.'], create: (c) => new AreaSubtractTool(c) },
  { id: 'areaSplit', label: 'Alan böl', icon: 'areaSplit', group: 'area', section: 'boolean', shortcut: 'Alt+L', aliases: ['SLICE', 'ALANBOL'], description: 'Alanı çizilen ya da gösterilen çizgi boyunca parçalara ayırır; parçalar ve alanları canlı görünür.', steps: ['Bölünecek alanları seçip sağ tıklayın.', 'Kesme çizgisinin noktalarına tıklayın; parçalar ve alanları canlı görünür. Sağ tık uygular.', '“Çizgiyle kes” ile var olan bir çizgiye tıklayarak kesin.'], create: (c) => new AreaSplitTool(c) },
  { id: 'toPolyline', label: 'Çizgiye çevir', icon: 'toPolyline', group: 'area', section: 'create', aliases: ['ALANCIZGI', 'CIZGIYECEVIR'], description: 'Alanı kapalı çoklu çizgiye çevirir; delikler ayrı çizgi olur.', steps: ['Çizgiye çevrilecek alanları seçin.', 'Sağ tıklayın.'], create: (c) => new ToPolylineTool(c) },

  // Harita
  { id: 'parcel', label: 'Parsel oluştur', icon: 'parcel', group: 'map', section: 'parcel', shortcut: 'Alt+P', aliases: ['PARSEL'], description: 'Köşe noktalarından parsel çizer, numara ve tapu alanını yazar.', steps: ['Parsel köşelerine sırayla tıklayın.', 'Sağ tıklayın: parsel numaralanır, tapu alanı yazılır.', 'Ada ve mahalleyi Öznitelikler panelinden girin.'], create: (c) => new PathTool(c, { id: 'parcel', label: 'Parsel', closed: true, parcelLayer: LAYERS.parcel }) },
  { id: 'subdivide', label: 'İfraz', icon: 'subdivide', group: 'map', section: 'parcel', shortcut: 'Alt+I', aliases: ['IFRAZ'], description: 'Parseli verilen alan ya da doğrultuya göre böler.' },
  { id: 'stakeout', label: 'Aplikasyon', icon: 'stakeout', group: 'map', section: 'field', shortcut: 'Alt+A', aliases: ['APLIKASYON', 'APL'], description: 'Seçili noktalar için istasyondan semt ve mesafe hesaplar.' },
  { id: 'spot', label: 'Kot noktası', icon: 'spot', group: 'map', section: 'field', shortcut: 'Alt+Z', aliases: ['KOT'], description: 'Kot değeri girilerek yükseklik noktası ekler.', steps: ['Kot noktasının yerine tıklayın.', 'Kot değerini yazıp Enter’a basın.'], create: (c) => new PointTool(c, { id: 'spot', label: 'Kot noktası', askZ: true, layerId: LAYERS.spot }) },
  { id: 'measure', label: 'Mesafe ölç', icon: 'measure', group: 'map', section: 'measure', shortcut: 'Alt+M', aliases: ['DI', 'DIST', 'MESAFE'], description: 'Noktalar arası kenar uzunluğu ve semt açısını ölçer.', steps: ['Ölçülecek noktalara sırayla tıklayın; uzunluk ve semt imleç yanında görünür.', 'Sağ tıklayın: toplam uzunluk mesaj satırına yazılır.'], create: (c) => new PathTool(c, { id: 'measure', label: 'Mesafe ölç', closed: false, measureOnly: true }) },
  { id: 'area', label: 'Alan hesapla', icon: 'area', group: 'map', section: 'measure', shortcut: 'Alt+H', aliases: ['AA', 'AREA', 'ALANHESAP'], description: 'Tıklanan köşelerden alan ve çevre hesaplar.', steps: ['Alanın köşelerine tıklayın.', 'Sağ tıklayın: alan ve çevre mesaj satırına yazılır.'], create: (c) => new PathTool(c, { id: 'area', label: 'Alan hesapla', closed: true, measureOnly: true }) },
];

export const TOOL_CATALOG: ToolDescriptor[] = defs.map((d) => ({
  ...d,
  ready: !!d.create,
  create: d.create ?? (() => new PendingTool(d.id, d.label)),
}));
