# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""Every wrapper by its command's id (TODOS.md PY-16)."""

from __future__ import annotations

from typing import Any

from . import arc, circle, entities, line, point, polygon, polyline, project

COMMANDS: dict[str, Any] = {
    "cad.arc.create": arc.create,
    "cad.circle.create": circle.create,
    "cad.entities.array": entities.array,
    "cad.entities.create": entities.create,
    "cad.entities.delete": entities.delete,
    "cad.entities.edit": entities.edit,
    "cad.entities.set": entities.set,
    "cad.entities.transform": entities.transform,
    "cad.line.create": line.create,
    "cad.point.create": point.create,
    "cad.polygon.create": polygon.create,
    "cad.polyline.create": polyline.create,
    "project.access.revoke": project.access.revoke,
    "project.archive": project.archive,
    "project.changes": project.changes,
    "project.checkpoint.create": project.checkpoint.create,
    "project.checkpoint.delete": project.checkpoint.delete,
    "project.checkpoint.restore": project.checkpoint.restore,
    "project.convert": project.convert,
    "project.create": project.create,
    "project.duplicate": project.duplicate,
    "project.favorite": project.favorite,
    "project.file.commit": project.file.commit,
    "project.import": project.import_,
    "project.invitation.revoke": project.invitation.revoke,
    "project.invite": project.invite,
    "project.metadata.update": project.metadata.update,
    "project.purge": project.purge,
    "project.rename": project.rename,
    "project.restore": project.restore,
    "project.share": project.share,
    "project.trash": project.trash,
    "project.unarchive": project.unarchive,
}
"""The command id → its wrapper (``kentos.cad.polygon.create`` …)."""

NAMESPACES = ("arc", "circle", "entities", "line", "point", "polygon", "polyline", "project",)
