# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.arc``: ``cad.arc.create``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from ._runtime import CommandNote, LocalCommand, UNSET, Unset, _opt  # noqa: F401
from .types import (  # noqa: F401
    ArcCreate,
    ArcCreated,
    ArcPlan,
    Vec2,
    Vec2Like,
)

if TYPE_CHECKING:
    from .document import Document


class _ArcCreate(LocalCommand[ArcCreate, ArcCreated, ArcPlan]):
    """``cad.arc.create`` v1. Yay oluştur: Açık çizimde verilen katmana merkezi, yarıçapı
    ve saat yönünün tersine başlangıç ile bitiş açısıyla (radyan) bir yay ekler; tek
    geri alma adımıdır. Yay aracı yöntemlerinin (üç nokta; başlangıç, merkez ve bitiş,
    açı ya da kiriş; başlangıç, bitiş ve merkez, açı, yön ya da yarıçap; önce merkez;
    son nesneye teğet devam) yayını ortak geometri çekirdeğiyle bulur ve bu komutla
    yazar. Yarıçap sıfırdan büyük olmalıdır; açılar verildiği gibi saklanır, eşit açılar
    tam turdur. Katman girdide açıkça verilir: kilitli katmana yazılmaz, gizli katmana
    uyarıyla yazılır. expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey
    yazılmaz, sonuç conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik
    project.changes ile gider.
    """
    __slots__ = ()
    id = "cad.arc.create"
    version = 1
    title = "Yay oluştur"
    scope = "document"
    input_type = ArcCreate
    output_type = ArcCreated
    plan_type = ArcPlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        c: Vec2Like,
        r: float,
        a0: float,
        a1: float,
        attrs: Mapping[str, str] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
    ) -> ArcCreated:
        """Yay oluştur: Açık çizimde verilen katmana merkezi, yarıçapı ve saat yönünün tersine
        başlangıç ile bitiş açısıyla (radyan) bir yay ekler; tek geri alma adımıdır. Yay
        aracı yöntemlerinin (üç nokta; başlangıç, merkez ve bitiş, açı ya da kiriş;
        başlangıç, bitiş ve merkez, açı, yön ya da yarıçap; önce merkez; son nesneye teğet
        devam) yayını ortak geometri çekirdeğiyle bulur ve bu komutla yazar. Yarıçap
        sıfırdan büyük olmalıdır; açılar verildiği gibi saklanır, eşit açılar tam turdur.
        Katman girdide açıkça verilir: kilitli katmana yazılmaz, gizli katmana uyarıyla
        yazılır. expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz,
        sonuç conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik
        project.changes ile gider.

        Args:
            doc: The drawing it works on.
            layer_id: The layer it goes on: a layer's id (`LayerNode.id`), not a group's.
            c: Its centre: x east (Y), y north (X), in the project's units (m), float64.
            r: Its radius, in the project's units; above zero.
            a0: Where it starts: radians, counter-clockwise from east (a geometry
                angle, not a surveying bearing).
            a1: Where it ends: the arc runs counter-clockwise from `a0` to `a1`.
            attrs: GIS attributes, text in v1. Absent: none.
            color: Colour override (`EntityBase.color`). Absent: the layer's colour (katmana göre).
            expected_revision: The document revision the input was prepared against, as decimal text
                (from a plan, or the document). When given and the document is no
                longer at it, nothing is written and the answer is `conflict`.

        Returns:
            ArcCreated

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, ArcCreate(
            layer_id=layer_id,
            c=Vec2.of(c),
            r=r,
            a0=a0,
            a1=a1,
            attrs=_opt(attrs, lambda x: dict(x)),
            color=color,
            expected_revision=expected_revision,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        c: Vec2Like,
        r: float,
        a0: float,
        a1: float,
        attrs: Mapping[str, str] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
    ) -> ArcPlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, ArcCreate(
            layer_id=layer_id,
            c=Vec2.of(c),
            r=r,
            a0=a0,
            a1=a1,
            attrs=_opt(attrs, lambda x: dict(x)),
            color=color,
            expected_revision=expected_revision,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        c: Vec2Like,
        r: float,
        a0: float,
        a1: float,
        attrs: Mapping[str, str] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, ArcCreate(
            layer_id=layer_id,
            c=Vec2.of(c),
            r=r,
            a0=a0,
            a1=a1,
            attrs=_opt(attrs, lambda x: dict(x)),
            color=color,
            expected_revision=expected_revision,
        ))


create = _ArcCreate()
"""Yay oluştur (``cad.arc.create``)."""


__all__ = ["create"]
