# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.blocks``: ``cad.blocks.define``, ``cad.blocks.edit``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from ._runtime import CommandNote, LocalCommand, UNSET, Unset, _opt  # noqa: F401
from .types import (  # noqa: F401
    BlockDefined,
    BlockEditOperation,
    BlockEditOperationName,
    BlocksDefine,
    BlocksDefinePlan,
    BlocksEdit,
    BlocksEditPlan,
    BlocksEdited,
    Vec2,
    Vec2Like,
)

if TYPE_CHECKING:
    from .document import Document


class _BlocksDefine(LocalCommand[BlocksDefine, BlockDefined, BlocksDefinePlan]):
    """``cad.blocks.define`` v1. Blok tanımla: Kalıcı kimlikleriyle verilen nesnelerden,
    verilen adla ve taban noktasıyla yeni bir blok tanımı yapar; tek geri alma adımı,
    adı Blok tanımla. Nesneler olduğu gibi, koordinatları, katmanları, renkleri ve
    verileriyle kopyalanır; blok iç içe olabilir, en çok 16 düzey. Ad boş olamaz ve
    çizimde bir kez bulunur (büyük küçük harf Türkçe kurallarıyla ayırt edilmez).
    replace ile nesneler silinir, yerine yeni bloğun taban noktasına, layerId katmanına
    bir yerleştirmesi konur (ölçek 1, dönüş yok); kilitli katmandaki nesne tanıma girer
    ama silinmez, böyle bir nesne varsa replace reddedilir. Blok oluştur aracı bu
    komutla yazar; blok cad.entities.create'in insert geometrisiyle yerleştirilir,
    Patlat onu cad.entities.edit ile açar. expectedRevision verilmişse ve çizim o
    sürümde değilse hiçbir şey yazılmaz, sonuç conflict olur. Yerel çizim izin istemez;
    bulut projesine değişiklik project.changes ile gider.
    """
    __slots__ = ()
    id = "cad.blocks.define"
    version = 1
    title = "Blok tanımla"
    scope = "document"
    input_type = BlocksDefine
    output_type = BlockDefined
    plan_type = BlocksDefinePlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        name: str,
        base: Vec2Like,
        uids: Sequence[str],
        description: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        layer_id: str | None | Unset = UNSET,
        replace: bool | None | Unset = UNSET,
    ) -> BlockDefined:
        """Blok tanımla: Kalıcı kimlikleriyle verilen nesnelerden, verilen adla ve taban
        noktasıyla yeni bir blok tanımı yapar; tek geri alma adımı, adı Blok tanımla.
        Nesneler olduğu gibi, koordinatları, katmanları, renkleri ve verileriyle kopyalanır;
        blok iç içe olabilir, en çok 16 düzey. Ad boş olamaz ve çizimde bir kez bulunur
        (büyük küçük harf Türkçe kurallarıyla ayırt edilmez). replace ile nesneler silinir,
        yerine yeni bloğun taban noktasına, layerId katmanına bir yerleştirmesi konur (ölçek
        1, dönüş yok); kilitli katmandaki nesne tanıma girer ama silinmez, böyle bir nesne
        varsa replace reddedilir. Blok oluştur aracı bu komutla yazar; blok
        cad.entities.create'in insert geometrisiyle yerleştirilir, Patlat onu
        cad.entities.edit ile açar. expectedRevision verilmişse ve çizim o sürümde değilse
        hiçbir şey yazılmaz, sonuç conflict olur. Yerel çizim izin istemez; bulut projesine
        değişiklik project.changes ile gider.

        Args:
            doc: The drawing it works on.
            name: The block's name, unique in the drawing (Turkish case folded).
            base: The point an insert places, in the drawing's coordinates.
            uids: The objects it is made of, at least one, by persistent id.
            description: What the block is.
            expected_revision: The document revision the input was prepared against, as decimal text
                (from a plan, or the document). When given and the document is no
                longer at it, nothing is written and the answer is `conflict`.
            layer_id: With `replace`: the layer the insert goes on, a layer's id.
            replace: True: the objects are replaced by an insert of the new block.

        Returns:
            BlockDefined

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, BlocksDefine(
            name=name,
            base=Vec2.of(base),
            uids=list(uids),
            description=description,
            expected_revision=expected_revision,
            layer_id=layer_id,
            replace=replace,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        name: str,
        base: Vec2Like,
        uids: Sequence[str],
        description: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        layer_id: str | None | Unset = UNSET,
        replace: bool | None | Unset = UNSET,
    ) -> BlocksDefinePlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, BlocksDefine(
            name=name,
            base=Vec2.of(base),
            uids=list(uids),
            description=description,
            expected_revision=expected_revision,
            layer_id=layer_id,
            replace=replace,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        name: str,
        base: Vec2Like,
        uids: Sequence[str],
        description: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        layer_id: str | None | Unset = UNSET,
        replace: bool | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, BlocksDefine(
            name=name,
            base=Vec2.of(base),
            uids=list(uids),
            description=description,
            expected_revision=expected_revision,
            layer_id=layer_id,
            replace=replace,
        ))


define = _BlocksDefine()
"""Blok tanımla (``cad.blocks.define``)."""


class _BlocksEdit(LocalCommand[BlocksEdit, BlocksEdited, BlocksEditPlan]):
    """``cad.blocks.edit`` v1. Blok tanımını değiştir: Bir blok tanımını kimliğiyle
    değiştirir; tek geri alma adımı, adı işlemin: rename yeni ad (Blok değiştir),
    redefine içindekileri kalıcı kimlikleriyle verilen nesnelerden yeniden kurar (Blok
    değiştir), rebase taban noktasını taşır (Blok değiştir), remove kullanılmayan tanımı
    siler (Blok sil), purge kullanılmayan bütün tanımları siler (Blokları temizle).
    Tanım değişince bütün yerleştirmeleri yenisini gösterir. Çizimde ya da başka bir
    tanımda yerleştirmesi olan tanım silinmez; tanım kendini içeremez, en çok 16 düzey
    iç içe olabilir. redefine'da replace ile nesneler silinir, yerine tanımın bir
    yerleştirmesi konur. Bir şey değiştirmeyen istek hiçbir şey yazmaz. Bloklar paneli
    bu komutla yazar. expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey
    yazılmaz, sonuç conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik
    project.changes ile gider.
    """
    __slots__ = ()
    id = "cad.blocks.edit"
    version = 1
    title = "Blok tanımını değiştir"
    scope = "document"
    input_type = BlocksEdit
    output_type = BlocksEdited
    plan_type = BlocksEditPlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        operation: BlockEditOperation | BlockEditOperationName,
        base: Vec2Like | None | Unset = UNSET,
        block: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        layer_id: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        replace: bool | None | Unset = UNSET,
        uids: Sequence[str] | None | Unset = UNSET,
    ) -> BlocksEdited:
        """Blok tanımını değiştir: Bir blok tanımını kimliğiyle değiştirir; tek geri alma
        adımı, adı işlemin: rename yeni ad (Blok değiştir), redefine içindekileri kalıcı
        kimlikleriyle verilen nesnelerden yeniden kurar (Blok değiştir), rebase taban
        noktasını taşır (Blok değiştir), remove kullanılmayan tanımı siler (Blok sil), purge
        kullanılmayan bütün tanımları siler (Blokları temizle). Tanım değişince bütün
        yerleştirmeleri yenisini gösterir. Çizimde ya da başka bir tanımda yerleştirmesi
        olan tanım silinmez; tanım kendini içeremez, en çok 16 düzey iç içe olabilir.
        redefine'da replace ile nesneler silinir, yerine tanımın bir yerleştirmesi konur.
        Bir şey değiştirmeyen istek hiçbir şey yazmaz. Bloklar paneli bu komutla yazar.
        expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç
        conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik project.changes
        ile gider.

        Args:
            doc: The drawing it works on.
            operation:
            base: `rebase`: the new base point; `redefine`: the base point (absent: kept).
            block: The definition; every operation but `purge`.
            expected_revision: The document revision the input was prepared against, as decimal text.
            layer_id: `redefine` with `replace`: the layer the insert goes on.
            name: `rename`: the new name.
            replace: `redefine`: true, the objects are replaced by an insert of the block.
            uids: `redefine`: the objects it is made of now, by persistent id.

        Returns:
            BlocksEdited

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, BlocksEdit(
            operation=operation,
            base=_opt(base, lambda x: Vec2.of(x)),
            block=block,
            expected_revision=expected_revision,
            layer_id=layer_id,
            name=name,
            replace=replace,
            uids=_opt(uids, lambda x: list(x)),
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        operation: BlockEditOperation | BlockEditOperationName,
        base: Vec2Like | None | Unset = UNSET,
        block: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        layer_id: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        replace: bool | None | Unset = UNSET,
        uids: Sequence[str] | None | Unset = UNSET,
    ) -> BlocksEditPlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, BlocksEdit(
            operation=operation,
            base=_opt(base, lambda x: Vec2.of(x)),
            block=block,
            expected_revision=expected_revision,
            layer_id=layer_id,
            name=name,
            replace=replace,
            uids=_opt(uids, lambda x: list(x)),
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        operation: BlockEditOperation | BlockEditOperationName,
        base: Vec2Like | None | Unset = UNSET,
        block: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        layer_id: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        replace: bool | None | Unset = UNSET,
        uids: Sequence[str] | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, BlocksEdit(
            operation=operation,
            base=_opt(base, lambda x: Vec2.of(x)),
            block=block,
            expected_revision=expected_revision,
            layer_id=layer_id,
            name=name,
            replace=replace,
            uids=_opt(uids, lambda x: list(x)),
        ))


edit = _BlocksEdit()
"""Blok tanımını değiştir (``cad.blocks.edit``)."""


__all__ = ["define", "edit"]
