# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.circle``: ``cad.circle.create``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from ._runtime import CommandNote, LocalCommand, UNSET, Unset, _opt  # noqa: F401
from .types import (  # noqa: F401
    CircleCreate,
    CircleCreated,
    CirclePlan,
    Vec2,
    Vec2Like,
)

if TYPE_CHECKING:
    from .document import Document


class _CircleCreate(LocalCommand[CircleCreate, CircleCreated, CirclePlan]):
    """``cad.circle.create`` v1. Daire oluştur: Açık çizimde verilen katmana merkezi ve
    yarıçapıyla bir daire ekler; tek geri alma adımıdır. Daire aracı yöntemlerinin
    (merkez ve yarıçap ya da çap, iki nokta, üç nokta, iki nesneye teğet ve yarıçap, üç
    nesneye teğet) dairesini ortak geometri çekirdeğiyle bulur ve bu komutla yazar.
    Yarıçap sıfırdan büyük olmalıdır. Katman girdide açıkça verilir: kilitli katmana
    yazılmaz, gizli katmana uyarıyla yazılır. expectedRevision verilmişse ve çizim o
    sürümde değilse hiçbir şey yazılmaz, sonuç conflict olur. Yerel çizim izin istemez;
    bulut projesine değişiklik project.changes ile gider.
    """
    __slots__ = ()
    id = "cad.circle.create"
    version = 1
    title = "Daire oluştur"
    scope = "document"
    input_type = CircleCreate
    output_type = CircleCreated
    plan_type = CirclePlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        c: Vec2Like,
        r: float,
        attrs: Mapping[str, str] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        line_weight: float | None | Unset = UNSET,
    ) -> CircleCreated:
        """Daire oluştur: Açık çizimde verilen katmana merkezi ve yarıçapıyla bir daire ekler;
        tek geri alma adımıdır. Daire aracı yöntemlerinin (merkez ve yarıçap ya da çap, iki
        nokta, üç nokta, iki nesneye teğet ve yarıçap, üç nesneye teğet) dairesini ortak
        geometri çekirdeğiyle bulur ve bu komutla yazar. Yarıçap sıfırdan büyük olmalıdır.
        Katman girdide açıkça verilir: kilitli katmana yazılmaz, gizli katmana uyarıyla
        yazılır. expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz,
        sonuç conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik
        project.changes ile gider.

        Args:
            doc: The drawing it works on.
            layer_id: The layer it goes on: a layer's id (`LayerNode.id`), not a group's.
            c: Its centre: x east (Y), y north (X), in the project's units (m), float64.
            r: Its radius, in the project's units; above zero.
            attrs: GIS attributes, text in v1. Absent: none.
            color: Colour override (`EntityBase.color`). Absent: the layer's colour (katmana göre).
            expected_revision: The document revision the input was prepared against, as decimal text
                (from a plan, or the document). When given and the document is no
                longer at it, nothing is written and the answer is `conflict`.
            line_weight: Its own line weight, paper mm (`EntityBase.line_weight`, 0 the
                thinnest, at most 100; docs/adr/0139): what the tools give a new
                object from the current weight. Absent: the layer's (katmana göre).

        Returns:
            CircleCreated

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, CircleCreate(
            layer_id=layer_id,
            c=Vec2.of(c),
            r=r,
            attrs=_opt(attrs, lambda x: dict(x)),
            color=color,
            expected_revision=expected_revision,
            line_weight=line_weight,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        c: Vec2Like,
        r: float,
        attrs: Mapping[str, str] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        line_weight: float | None | Unset = UNSET,
    ) -> CirclePlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, CircleCreate(
            layer_id=layer_id,
            c=Vec2.of(c),
            r=r,
            attrs=_opt(attrs, lambda x: dict(x)),
            color=color,
            expected_revision=expected_revision,
            line_weight=line_weight,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        c: Vec2Like,
        r: float,
        attrs: Mapping[str, str] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        line_weight: float | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, CircleCreate(
            layer_id=layer_id,
            c=Vec2.of(c),
            r=r,
            attrs=_opt(attrs, lambda x: dict(x)),
            color=color,
            expected_revision=expected_revision,
            line_weight=line_weight,
        ))


create = _CircleCreate()
"""Daire oluştur (``cad.circle.create``)."""


__all__ = ["create"]
