# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.entities``: ``cad.entities.array``, ``cad.entities.create``, ``cad.entities.delete``, ``cad.entities.edit``, ``cad.entities.set``, ``cad.entities.transform``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from ._runtime import CommandNote, LocalCommand, UNSET, Unset, _opt  # noqa: F401
from .types import (  # noqa: F401
    ArrayLayout,
    CreateOperation,
    CreateOperationName,
    EditOperation,
    EditOperationName,
    EntitiesArray,
    EntitiesArrayPlan,
    EntitiesArrayed,
    EntitiesCreate,
    EntitiesCreatePlan,
    EntitiesCreated,
    EntitiesDelete,
    EntitiesDeletePlan,
    EntitiesDeleted,
    EntitiesEdit,
    EntitiesEditPlan,
    EntitiesEdited,
    EntitiesPropertiesSet,
    EntitiesSetProperties,
    EntitiesSetPropertiesPlan,
    EntitiesTransform,
    EntitiesTransformPlan,
    EntitiesTransformed,
    EntityEdit,
    NewObject,
    PropertiesOperation,
    PropertiesOperationName,
    Transform,
)

if TYPE_CHECKING:
    from .document import Document


class _EntitiesArray(LocalCommand[EntitiesArray, EntitiesArrayed, EntitiesArrayPlan]):
    """``cad.entities.array`` v1. Nesneleri diziye kopyala: Kalıcı kimlikleriyle verilen
    nesnelerin kopyalarını satır ve sütunlara ya da bir merkezin çevresine dizer; bütün
    kopyalar tek geri alma adımındadır. Dizi: satır × sütun yer (2 ile 10 000 arası),
    sütunlar dx, satırlar dy aralıkla; birden çok yeri olan yönün aralığı sıfır olamaz.
    Kutupsal dizi: merkezin çevresinde adet kadar öğe (2 ile 1000 arası, asıllar dahil),
    fill derecelik açıya; 360 tam turu eşit böler, eksi saat yönündedir. rotate ile
    kopyalar merkez etrafında döner, yoksa yönünü koruyup kopyalanan nesnelerin
    kutusunun ortasıyla yer değiştirir. Yol boyunca dizi: kalıcı kimliğiyle verilen yol
    (çizgi, yay, daire ya da çoklu çizgi) boyunca adet kadar yer (2 ile 10 000 arası,
    asıllar yolun başında); spacing verilirse yerler yolun başından o aralıkla,
    verilmezse yolun başından sonuna (kapalı yolda çevresine) eşit dağılır; align ile
    kopyalar yolun doğrultusuyla döner. Yol okunur, değişmez. Dizi, Kutupsal dizi ve Yol
    boyunca dizi araçları seçimi kimlik listesi olarak verip bu komutla yazar; adım
    aracın adını taşır. Yerleşim geometri çekirdeğindedir: her nesne türü aynı kuralla
    kopyalanır. Kopya aslının bütün alanlarını ve yeni bir kalıcı kimlik alır. Kilitli
    katmandaki nesnenin kopyası yapılmaz: öbürleri uyarıyla yazılır, hepsi kilitliyse
    hiçbir şey yazılmaz. expectedRevision verilmişse ve çizim o sürümde değilse hiçbir
    şey yazılmaz, sonuç conflict olur. Yerel çizim izin istemez; bulut projesine
    değişiklik project.changes ile gider.
    """
    __slots__ = ()
    id = "cad.entities.array"
    version = 1
    title = "Nesneleri diziye kopyala"
    scope = "document"
    input_type = EntitiesArray
    output_type = EntitiesArrayed
    plan_type = EntitiesArrayPlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        uids: Sequence[str],
        layout: ArrayLayout,
        expected_revision: str | None | Unset = UNSET,
    ) -> EntitiesArrayed:
        """Nesneleri diziye kopyala: Kalıcı kimlikleriyle verilen nesnelerin kopyalarını satır
        ve sütunlara ya da bir merkezin çevresine dizer; bütün kopyalar tek geri alma
        adımındadır. Dizi: satır × sütun yer (2 ile 10 000 arası), sütunlar dx, satırlar dy
        aralıkla; birden çok yeri olan yönün aralığı sıfır olamaz. Kutupsal dizi: merkezin
        çevresinde adet kadar öğe (2 ile 1000 arası, asıllar dahil), fill derecelik açıya;
        360 tam turu eşit böler, eksi saat yönündedir. rotate ile kopyalar merkez etrafında
        döner, yoksa yönünü koruyup kopyalanan nesnelerin kutusunun ortasıyla yer
        değiştirir. Yol boyunca dizi: kalıcı kimliğiyle verilen yol (çizgi, yay, daire ya da
        çoklu çizgi) boyunca adet kadar yer (2 ile 10 000 arası, asıllar yolun başında);
        spacing verilirse yerler yolun başından o aralıkla, verilmezse yolun başından sonuna
        (kapalı yolda çevresine) eşit dağılır; align ile kopyalar yolun doğrultusuyla döner.
        Yol okunur, değişmez. Dizi, Kutupsal dizi ve Yol boyunca dizi araçları seçimi kimlik
        listesi olarak verip bu komutla yazar; adım aracın adını taşır. Yerleşim geometri
        çekirdeğindedir: her nesne türü aynı kuralla kopyalanır. Kopya aslının bütün
        alanlarını ve yeni bir kalıcı kimlik alır. Kilitli katmandaki nesnenin kopyası
        yapılmaz: öbürleri uyarıyla yazılır, hepsi kilitliyse hiçbir şey yazılmaz.
        expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç
        conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik project.changes
        ile gider.

        Args:
            doc: The drawing it works on.
            uids: The objects' persistent ids (lowercase UUID text with hyphens), at least one.
            layout: Where the copies go.
            expected_revision: The document revision the input was prepared against, as decimal text
                (from a plan, or the document). When given and the document is no
                longer at it, nothing is written and the answer is `conflict`.

        Returns:
            EntitiesArrayed

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, EntitiesArray(
            uids=list(uids),
            layout=layout,
            expected_revision=expected_revision,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        uids: Sequence[str],
        layout: ArrayLayout,
        expected_revision: str | None | Unset = UNSET,
    ) -> EntitiesArrayPlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, EntitiesArray(
            uids=list(uids),
            layout=layout,
            expected_revision=expected_revision,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        uids: Sequence[str],
        layout: ArrayLayout,
        expected_revision: str | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, EntitiesArray(
            uids=list(uids),
            layout=layout,
            expected_revision=expected_revision,
        ))


array = _EntitiesArray()
"""Nesneleri diziye kopyala (``cad.entities.array``)."""


class _EntitiesCreate(LocalCommand[EntitiesCreate, EntitiesCreated, EntitiesCreatePlan]):
    """``cad.entities.create`` v1. Nesneleri ekle: Verilen nesneleri bir katmana yazar;
    hepsi tek geri alma adımındadır, adı “Ekle” ya da aracın ya da hesabın adı (Paralel
    çizgi, Dik in, Dik çık, Böl, Tarama, Alan oluştur, Poligon hesabı, Kutupsal alım,
    Önden kestirme, Geriden kestirme). Her nesne geometrisiyle verilir,
    cad.entities.edit'teki gibi: nokta, çizgi, çoklu çizgi, kapalı alan, daire, yay,
    elips, eğri, yardımcı çizgi, ışın, yazı, ölçü, tarama, blok yerleştirmesi (çizimde
    tanımlı bir blok, ölçeği pozitif); renk, öznitelik ve etiket isteğe bağlıdır. Elips,
    Eğri, Yardımcı çizgi, Işın, Halka, Paralel çizgi, Dik in, Dik çık ve Böl araçları
    geometriyi ortak geometri çekirdeğiyle bulur, önizlemede gösterdiklerini bu komutla
    yazar; Yazı, Ölçülendirme, Tarama, Parsel oluştur ve İçine tıklayarak alan da. Hesap
    menüsünün pencereleri (Poligon hesabı, Kutupsal alım, Önden ve Geriden kestirme)
    bulduğu noktaları adları, etiketleri ve öznitelikleriyle bu komutla çizime ekler.
    Kilitli katmana hiçbir şey yazılmaz; gizli katmana uyarıyla yazılır.
    expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç
    conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik project.changes
    ile gider.
    """
    __slots__ = ()
    id = "cad.entities.create"
    version = 1
    title = "Nesneleri ekle"
    scope = "document"
    input_type = EntitiesCreate
    output_type = EntitiesCreated
    plan_type = EntitiesCreatePlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        objects: Sequence[NewObject],
        expected_revision: str | None | Unset = UNSET,
        operation: CreateOperation | CreateOperationName | None | Unset = UNSET,
    ) -> EntitiesCreated:
        """Nesneleri ekle: Verilen nesneleri bir katmana yazar; hepsi tek geri alma
        adımındadır, adı “Ekle” ya da aracın ya da hesabın adı (Paralel çizgi, Dik in, Dik
        çık, Böl, Tarama, Alan oluştur, Poligon hesabı, Kutupsal alım, Önden kestirme,
        Geriden kestirme). Her nesne geometrisiyle verilir, cad.entities.edit'teki gibi:
        nokta, çizgi, çoklu çizgi, kapalı alan, daire, yay, elips, eğri, yardımcı çizgi,
        ışın, yazı, ölçü, tarama, blok yerleştirmesi (çizimde tanımlı bir blok, ölçeği
        pozitif); renk, öznitelik ve etiket isteğe bağlıdır. Elips, Eğri, Yardımcı çizgi,
        Işın, Halka, Paralel çizgi, Dik in, Dik çık ve Böl araçları geometriyi ortak
        geometri çekirdeğiyle bulur, önizlemede gösterdiklerini bu komutla yazar; Yazı,
        Ölçülendirme, Tarama, Parsel oluştur ve İçine tıklayarak alan da. Hesap menüsünün
        pencereleri (Poligon hesabı, Kutupsal alım, Önden ve Geriden kestirme) bulduğu
        noktaları adları, etiketleri ve öznitelikleriyle bu komutla çizime ekler. Kilitli
        katmana hiçbir şey yazılmaz; gizli katmana uyarıyla yazılır. expectedRevision
        verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç conflict olur.
        Yerel çizim izin istemez; bulut projesine değişiklik project.changes ile gider.

        Args:
            doc: The drawing it works on.
            layer_id: The layer they go on: a layer's id (`LayerNode.id`), not a group's.
            objects: What is written, at least one, in this order.
            expected_revision: The document revision the input was prepared against, as decimal text
                (from a plan, or the document). When given and the document is no
                longer at it, nothing is written and the answer is `conflict`.
            operation: The drawing tool or Hesap window the objects come from, when its step
                has its own name: Paralel çizgi, Dik in, Dik çık, Böl, Tarama, Alan
                oluştur, Poligon hesabı, Kutupsal alım, Önden kestirme, Geriden
                kestirme, Toplu alan, Köşelere nokta, Bitişik alan, Etiketleri yazıya
                çevir. Absent: “Ekle”.

        Returns:
            EntitiesCreated

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, EntitiesCreate(
            layer_id=layer_id,
            objects=list(objects),
            expected_revision=expected_revision,
            operation=operation,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        objects: Sequence[NewObject],
        expected_revision: str | None | Unset = UNSET,
        operation: CreateOperation | CreateOperationName | None | Unset = UNSET,
    ) -> EntitiesCreatePlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, EntitiesCreate(
            layer_id=layer_id,
            objects=list(objects),
            expected_revision=expected_revision,
            operation=operation,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        objects: Sequence[NewObject],
        expected_revision: str | None | Unset = UNSET,
        operation: CreateOperation | CreateOperationName | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, EntitiesCreate(
            layer_id=layer_id,
            objects=list(objects),
            expected_revision=expected_revision,
            operation=operation,
        ))


create = _EntitiesCreate()
"""Nesneleri ekle (``cad.entities.create``)."""


class _EntitiesDelete(LocalCommand[EntitiesDelete, EntitiesDeleted, EntitiesDeletePlan]):
    """``cad.entities.delete`` v1. Nesneleri sil: Açık çizimden kalıcı kimlikleriyle
    verilen nesneleri siler; tek geri alma adımıdır, geri alma onları aynı kimlikleriyle
    yerlerine getirir. Silinecekler girdide açıkça verilir, seçim okunmaz: Sil aracı ve
    Delete tuşu seçimi ya da tıklanan nesneyi buraya yazar. Kilitli katmandaki nesneler
    silinmez: başkaları varsa uyarıyla yerinde kalır, hepsi kilitliyse hiçbir şey
    silinmez. expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey
    silinmez, sonuç conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik
    project.changes ile gider.
    """
    __slots__ = ()
    id = "cad.entities.delete"
    version = 1
    title = "Nesneleri sil"
    scope = "document"
    input_type = EntitiesDelete
    output_type = EntitiesDeleted
    plan_type = EntitiesDeletePlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        uids: Sequence[str],
        expected_revision: str | None | Unset = UNSET,
    ) -> EntitiesDeleted:
        """Nesneleri sil: Açık çizimden kalıcı kimlikleriyle verilen nesneleri siler; tek geri
        alma adımıdır, geri alma onları aynı kimlikleriyle yerlerine getirir. Silinecekler
        girdide açıkça verilir, seçim okunmaz: Sil aracı ve Delete tuşu seçimi ya da
        tıklanan nesneyi buraya yazar. Kilitli katmandaki nesneler silinmez: başkaları varsa
        uyarıyla yerinde kalır, hepsi kilitliyse hiçbir şey silinmez. expectedRevision
        verilmişse ve çizim o sürümde değilse hiçbir şey silinmez, sonuç conflict olur.
        Yerel çizim izin istemez; bulut projesine değişiklik project.changes ile gider.

        Args:
            doc: The drawing it works on.
            uids: The objects' persistent ids (lowercase UUID text with hyphens), at least one.
            expected_revision: The document revision the input was prepared against, as decimal text
                (from a plan, or the document). When given and the document is no
                longer at it, nothing is deleted and the answer is `conflict`.

        Returns:
            EntitiesDeleted

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, EntitiesDelete(
            uids=list(uids),
            expected_revision=expected_revision,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        uids: Sequence[str],
        expected_revision: str | None | Unset = UNSET,
    ) -> EntitiesDeletePlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, EntitiesDelete(
            uids=list(uids),
            expected_revision=expected_revision,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        uids: Sequence[str],
        expected_revision: str | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, EntitiesDelete(
            uids=list(uids),
            expected_revision=expected_revision,
        ))


delete = _EntitiesDelete()
"""Nesneleri sil (``cad.entities.delete``)."""


class _EntitiesEdit(LocalCommand[EntitiesEdit, EntitiesEdited, EntitiesEditPlan]):
    """``cad.entities.edit`` v1. Nesneleri düzenle: Kalıcı kimlikleriyle verilen nesnelere
    yeni geometri verir, onları parçalarla değiştirir, onlardan yeni nesneler yapar ya
    da onları siler; hepsi tek geri alma adımında, işlemin adıyla. Ötele, Buda, Uzat,
    Köşe yuvarla, Pah, Kır, Birleştir, Patlat, Uzat-kısalt, Köşe ekle/sil ve Esnet
    araçları geometriyi ortak geometri çekirdeğiyle bulur, önizlemede gösterdiklerini bu
    komutla yazar; Öznitelikler panelinin geometri satırları ve yerinde yazı
    düzenleyicisi de properties işlemiyle (adımı Değiştir), alan araçları da (Alan
    birleştir, kesiştir, çıkar, böl, Alana çevir, Çizgiye çevir) kendi adlarıyla bu
    komutla yazar. Seçili nesnenin tutamacı sürüklenince grip işlemiyle (adımı Tutamaçla
    düzenle), tutamacın menüsü Ortasına köşe ekle ve Köşeyi sil için vertexAdd ve
    vertexRemove, Düz kenar yap ve Yaya dönüştür için straightEdge ve arcEdge
    işlemleriyle yazar. Parçala, Yönü çevir, Sadeleştir ve Çizimi temizle split,
    reverse, simplify ve cleanup işlemleriyle, Tüm köşeleri yuvarla ve Tüm köşelere pah
    fillet ve chamfer işlemleriyle yazar. update nesnenin geometrisini değiştirir, öbür
    alanları kalır; replace nesneyi yerinde ve kimliğiyle başka bir nesne yapar, katmanı
    ve rengi kalır, öznitelikleri ve etiketi keepData ile kalır; add bir nesneden yeni
    nesne yapar, katmanını, rengini ve kalınlığını alır; add'e verilen katman, renk,
    kalınlık, öznitelik ve etiket yeni nesnenin kendisinindir (Patlat bir bloğun
    nesnelerini kendi katman, renk ve verileriyle böyle çıkarır); remove nesneyi siler.
    Bir nesne tek bir değişiklikle değişir. Yazının metni boş olamaz; kapalı alanın
    halkası en az 3 köşelidir, kenarlarından biri yaysa 2. Kilitli katmandaki nesne
    değişmez, ondan nesne yapılmaz: böyle bir nesne verilirse hiçbir şey yazılmaz.
    expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç
    conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik project.changes
    ile gider.
    """
    __slots__ = ()
    id = "cad.entities.edit"
    version = 1
    title = "Nesneleri düzenle"
    scope = "document"
    input_type = EntitiesEdit
    output_type = EntitiesEdited
    plan_type = EntitiesEditPlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        operation: EditOperation | EditOperationName,
        changes: Sequence[EntityEdit],
        expected_revision: str | None | Unset = UNSET,
    ) -> EntitiesEdited:
        """Nesneleri düzenle: Kalıcı kimlikleriyle verilen nesnelere yeni geometri verir,
        onları parçalarla değiştirir, onlardan yeni nesneler yapar ya da onları siler; hepsi
        tek geri alma adımında, işlemin adıyla. Ötele, Buda, Uzat, Köşe yuvarla, Pah, Kır,
        Birleştir, Patlat, Uzat-kısalt, Köşe ekle/sil ve Esnet araçları geometriyi ortak
        geometri çekirdeğiyle bulur, önizlemede gösterdiklerini bu komutla yazar;
        Öznitelikler panelinin geometri satırları ve yerinde yazı düzenleyicisi de
        properties işlemiyle (adımı Değiştir), alan araçları da (Alan birleştir, kesiştir,
        çıkar, böl, Alana çevir, Çizgiye çevir) kendi adlarıyla bu komutla yazar. Seçili
        nesnenin tutamacı sürüklenince grip işlemiyle (adımı Tutamaçla düzenle), tutamacın
        menüsü Ortasına köşe ekle ve Köşeyi sil için vertexAdd ve vertexRemove, Düz kenar
        yap ve Yaya dönüştür için straightEdge ve arcEdge işlemleriyle yazar. Parçala, Yönü
        çevir, Sadeleştir ve Çizimi temizle split, reverse, simplify ve cleanup
        işlemleriyle, Tüm köşeleri yuvarla ve Tüm köşelere pah fillet ve chamfer
        işlemleriyle yazar. update nesnenin geometrisini değiştirir, öbür alanları kalır;
        replace nesneyi yerinde ve kimliğiyle başka bir nesne yapar, katmanı ve rengi kalır,
        öznitelikleri ve etiketi keepData ile kalır; add bir nesneden yeni nesne yapar,
        katmanını, rengini ve kalınlığını alır; add'e verilen katman, renk, kalınlık,
        öznitelik ve etiket yeni nesnenin kendisinindir (Patlat bir bloğun nesnelerini kendi
        katman, renk ve verileriyle böyle çıkarır); remove nesneyi siler. Bir nesne tek bir
        değişiklikle değişir. Yazının metni boş olamaz; kapalı alanın halkası en az 3
        köşelidir, kenarlarından biri yaysa 2. Kilitli katmandaki nesne değişmez, ondan
        nesne yapılmaz: böyle bir nesne verilirse hiçbir şey yazılmaz. expectedRevision
        verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç conflict olur.
        Yerel çizim izin istemez; bulut projesine değişiklik project.changes ile gider.

        Args:
            doc: The drawing it works on.
            operation: The modify tool the edit comes from; it names the undo step: Ötele,
                Buda, Uzat, Köşe yuvarla, Pah, Kır, Birleştir, Patlat, Uzat-kısalt,
                Köşe ekle, Köşe sil, Esnet; Değiştir for Öznitelikler; Alan birleştir,
                Alan kesiştir, Alan çıkar, Alan böl, Alana çevir, Çizgiye çevir,
                Parçaları birleştir, Parçalara ayır; Tutamaçla düzenle, Düz kenar
                yap, Yaya dönüştür for the grips.
            changes: What changes, at least one.
            expected_revision: The document revision the input was prepared against, as decimal text
                (from a plan, or the document). When given and the document is no
                longer at it, nothing is written and the answer is `conflict`.

        Returns:
            EntitiesEdited

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, EntitiesEdit(
            operation=operation,
            changes=list(changes),
            expected_revision=expected_revision,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        operation: EditOperation | EditOperationName,
        changes: Sequence[EntityEdit],
        expected_revision: str | None | Unset = UNSET,
    ) -> EntitiesEditPlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, EntitiesEdit(
            operation=operation,
            changes=list(changes),
            expected_revision=expected_revision,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        operation: EditOperation | EditOperationName,
        changes: Sequence[EntityEdit],
        expected_revision: str | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, EntitiesEdit(
            operation=operation,
            changes=list(changes),
            expected_revision=expected_revision,
        ))


edit = _EntitiesEdit()
"""Nesneleri düzenle (``cad.entities.edit``)."""


class _EntitiesSet(LocalCommand[EntitiesSetProperties, EntitiesPropertiesSet, EntitiesSetPropertiesPlan]):
    """``cad.entities.set`` v1. Nesnelerin özelliklerini değiştir: Kalıcı kimlikleriyle
    verilen nesnelerin katmanını, rengini, sembolünü, özniteliklerini ya da etiketini
    değiştirir; hepsi tek geri alma adımında, adı işlemin: Katman değiştir, Renk
    değiştir, Sembol ata (null ile Sembolü kaldır), Değiştir (öznitelik), Etiket
    değiştir. Verilmeyen özellik değişmez. Renk, sembol ve etiket null ile kaldırılır:
    nesne katmanının rengiyle ve stiliyle çizilir. Öznitelik adıyla verilir ya da null
    ile silinir; adı geçmeyenler kalır. Öznitelikler panelinin katman, renk, sembol ve
    öznitelik satırları, Sembol ver ve Sembolü kaldır bu komutla yazar. Kilitli
    katmandaki nesne değişmez, kilitli katmana nesne taşınmaz: böyle bir nesne ya da
    katman verilirse hiçbir şey yazılmaz. Gizli katmana uyarıyla taşınır. Zaten
    istendiği gibi olan nesne değişmez; hiçbiri değişmiyorsa hiçbir şey yazılmaz.
    expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç
    conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik project.changes
    ile gider.
    """
    __slots__ = ()
    id = "cad.entities.set"
    version = 1
    title = "Nesnelerin özelliklerini değiştir"
    scope = "document"
    input_type = EntitiesSetProperties
    output_type = EntitiesPropertiesSet
    plan_type = EntitiesSetPropertiesPlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        uids: Sequence[str],
        operation: PropertiesOperation | PropertiesOperationName,
        attrs: Mapping[str, str | None] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        label: str | None | Unset = UNSET,
        layer_id: str | None | Unset = UNSET,
        line_weight: float | None | Unset = UNSET,
        symbol: str | None | Unset = UNSET,
    ) -> EntitiesPropertiesSet:
        """Nesnelerin özelliklerini değiştir: Kalıcı kimlikleriyle verilen nesnelerin
        katmanını, rengini, sembolünü, özniteliklerini ya da etiketini değiştirir; hepsi tek
        geri alma adımında, adı işlemin: Katman değiştir, Renk değiştir, Sembol ata (null
        ile Sembolü kaldır), Değiştir (öznitelik), Etiket değiştir. Verilmeyen özellik
        değişmez. Renk, sembol ve etiket null ile kaldırılır: nesne katmanının rengiyle ve
        stiliyle çizilir. Öznitelik adıyla verilir ya da null ile silinir; adı geçmeyenler
        kalır. Öznitelikler panelinin katman, renk, sembol ve öznitelik satırları, Sembol
        ver ve Sembolü kaldır bu komutla yazar. Kilitli katmandaki nesne değişmez, kilitli
        katmana nesne taşınmaz: böyle bir nesne ya da katman verilirse hiçbir şey yazılmaz.
        Gizli katmana uyarıyla taşınır. Zaten istendiği gibi olan nesne değişmez; hiçbiri
        değişmiyorsa hiçbir şey yazılmaz. expectedRevision verilmişse ve çizim o sürümde
        değilse hiçbir şey yazılmaz, sonuç conflict olur. Yerel çizim izin istemez; bulut
        projesine değişiklik project.changes ile gider.

        Args:
            doc: The drawing it works on.
            uids: The objects' persistent ids (lowercase UUID text with hyphens), at
                least one; a repeated one counts once.
            operation: What the change is; it names the undo step.
            attrs: Attributes by name, text in v1: a text sets the attribute (added when
                an object lacks it), null removes it. Absent or empty: none change.
            color: Their own colour (`EntityBase.color`, as `#E5484D`); null: their
                layer's (katmana göre). Absent: unchanged.
            expected_revision: The document revision the input was prepared against, as decimal text
                (from a plan, or the document). When given and the document is no
                longer at it, nothing is written and the answer is `conflict`.
            label: The text shown beside them (`EntityBase.label`); null: none. Absent:
                unchanged.
            layer_id: The layer they move to: a layer's id (`LayerNode.id`), not a group's.
                Absent: they stay on theirs.
            line_weight: Their own line weight, paper mm (`EntityBase.line_weight`, 0 the
                thinnest, at most 100); null: their layer's (katmana göre). Absent:
                unchanged.
            symbol: Their own symbol, a library item's id (`EntityBase.symbol`), drawn
                instead of their layer's style; null: the layer's style. The id is
                not looked up: the libraries are the host's. Absent: unchanged.

        Returns:
            EntitiesPropertiesSet

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, EntitiesSetProperties(
            uids=list(uids),
            operation=operation,
            attrs=_opt(attrs, lambda x: dict(x)),
            color=color,
            expected_revision=expected_revision,
            label=label,
            layer_id=layer_id,
            line_weight=line_weight,
            symbol=symbol,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        uids: Sequence[str],
        operation: PropertiesOperation | PropertiesOperationName,
        attrs: Mapping[str, str | None] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        label: str | None | Unset = UNSET,
        layer_id: str | None | Unset = UNSET,
        line_weight: float | None | Unset = UNSET,
        symbol: str | None | Unset = UNSET,
    ) -> EntitiesSetPropertiesPlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, EntitiesSetProperties(
            uids=list(uids),
            operation=operation,
            attrs=_opt(attrs, lambda x: dict(x)),
            color=color,
            expected_revision=expected_revision,
            label=label,
            layer_id=layer_id,
            line_weight=line_weight,
            symbol=symbol,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        uids: Sequence[str],
        operation: PropertiesOperation | PropertiesOperationName,
        attrs: Mapping[str, str | None] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        label: str | None | Unset = UNSET,
        layer_id: str | None | Unset = UNSET,
        line_weight: float | None | Unset = UNSET,
        symbol: str | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, EntitiesSetProperties(
            uids=list(uids),
            operation=operation,
            attrs=_opt(attrs, lambda x: dict(x)),
            color=color,
            expected_revision=expected_revision,
            label=label,
            layer_id=layer_id,
            line_weight=line_weight,
            symbol=symbol,
        ))


set = _EntitiesSet()
"""Nesnelerin özelliklerini değiştir (``cad.entities.set``)."""


class _EntitiesTransform(LocalCommand[EntitiesTransform, EntitiesTransformed, EntitiesTransformPlan]):
    """``cad.entities.transform`` v1. Nesneleri dönüştür: Kalıcı kimlikleriyle verilen
    nesneleri taşır, bir merkez etrafında döndürür, bir merkeze göre ölçekler, iki
    noktalı bir eksene göre aynalar ya da kaynak noktalarını hedef noktalarına hizalar;
    yerinde ya da kopya olarak, tek geri alma adımında. Hizalamada birinci kaynak
    noktası birinci hedefe gider; ikinci çift verilirse nesneler kaynak doğrultusu hedef
    doğrultusuna oturacak kadar döner, scale ile boyları da eşitlenir. Taşı, Kopyala,
    Döndür, Ölçekle, Aynala ve Hizala araçları seçimi kimlik listesi olarak verip bu
    komutla yazar; adım aracın adını taşır. Dönüşüm geometri çekirdeğindedir: her nesne
    türü (yay, daire, elips, eğri, yazı, ölçü, tarama) aynı kuralla döner; yaylar saat
    yönünün tersine kalır, aynalanan yazı okunur kalır. Yerinde değişen nesne yuvasını,
    kalıcı kimliğini ve öbür alanlarını korur; kopya bütün alanları alır, yeni bir
    kalıcı kimlik alır. Kilitli katmandaki nesne ne değişir ne kopyalanır: öbürleri
    uyarıyla yazılır, hepsi kilitliyse hiçbir şey yazılmaz. expectedRevision verilmişse
    ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç conflict olur. Yerel çizim
    izin istemez; bulut projesine değişiklik project.changes ile gider.
    """
    __slots__ = ()
    id = "cad.entities.transform"
    version = 1
    title = "Nesneleri dönüştür"
    scope = "document"
    input_type = EntitiesTransform
    output_type = EntitiesTransformed
    plan_type = EntitiesTransformPlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        uids: Sequence[str],
        transform: Transform,
        copy: bool | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
    ) -> EntitiesTransformed:
        """Nesneleri dönüştür: Kalıcı kimlikleriyle verilen nesneleri taşır, bir merkez
        etrafında döndürür, bir merkeze göre ölçekler, iki noktalı bir eksene göre aynalar
        ya da kaynak noktalarını hedef noktalarına hizalar; yerinde ya da kopya olarak, tek
        geri alma adımında. Hizalamada birinci kaynak noktası birinci hedefe gider; ikinci
        çift verilirse nesneler kaynak doğrultusu hedef doğrultusuna oturacak kadar döner,
        scale ile boyları da eşitlenir. Taşı, Kopyala, Döndür, Ölçekle, Aynala ve Hizala
        araçları seçimi kimlik listesi olarak verip bu komutla yazar; adım aracın adını
        taşır. Dönüşüm geometri çekirdeğindedir: her nesne türü (yay, daire, elips, eğri,
        yazı, ölçü, tarama) aynı kuralla döner; yaylar saat yönünün tersine kalır, aynalanan
        yazı okunur kalır. Yerinde değişen nesne yuvasını, kalıcı kimliğini ve öbür
        alanlarını korur; kopya bütün alanları alır, yeni bir kalıcı kimlik alır. Kilitli
        katmandaki nesne ne değişir ne kopyalanır: öbürleri uyarıyla yazılır, hepsi
        kilitliyse hiçbir şey yazılmaz. expectedRevision verilmişse ve çizim o sürümde
        değilse hiçbir şey yazılmaz, sonuç conflict olur. Yerel çizim izin istemez; bulut
        projesine değişiklik project.changes ile gider.

        Args:
            doc: The drawing it works on.
            uids: The objects' persistent ids (lowercase UUID text with hyphens), at least one.
            transform: What happens to them.
            copy: True: copies are made and the originals stay (Kopyala, Kopya (K),
                Aynala keeping its source). Absent or false: the objects themselves change.
            expected_revision: The document revision the input was prepared against, as decimal text
                (from a plan, or the document). When given and the document is no
                longer at it, nothing is written and the answer is `conflict`.

        Returns:
            EntitiesTransformed

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, EntitiesTransform(
            uids=list(uids),
            transform=transform,
            copy=copy,
            expected_revision=expected_revision,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        uids: Sequence[str],
        transform: Transform,
        copy: bool | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
    ) -> EntitiesTransformPlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, EntitiesTransform(
            uids=list(uids),
            transform=transform,
            copy=copy,
            expected_revision=expected_revision,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        uids: Sequence[str],
        transform: Transform,
        copy: bool | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, EntitiesTransform(
            uids=list(uids),
            transform=transform,
            copy=copy,
            expected_revision=expected_revision,
        ))


transform = _EntitiesTransform()
"""Nesneleri dönüştür (``cad.entities.transform``)."""


__all__ = ["array", "create", "delete", "edit", "set", "transform"]
