# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.labels``: ``cad.labels.pin``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from ._runtime import CommandNote, LocalCommand, UNSET, Unset, _opt  # noqa: F401
from .types import (  # noqa: F401
    LabelPinChange,
    LabelsPin,
    LabelsPinPlan,
    LabelsPinned,
)

if TYPE_CHECKING:
    from .document import Document


class _LabelsPin(LocalCommand[LabelsPin, LabelsPinned, LabelsPinPlan]):
    """``cad.labels.pin`` v1. Etiketi sabitle: Nesnelerin etiketlerini elle sabitler,
    döndürür, gizler ya da serbest bırakır: her değişiklik bir nesnenin bir etiketidir
    (class: kurallı katmanın sınıfının adı; yoksa nesnenin ilk etiketi), pin etiketin
    ortasının nesnenin çapasından uzaklığı (at, metre), açısı (rotation, derece, saat
    yönünün tersine) ya da gizliliğidir (hidden: true); pin null etiketi serbest
    bırakır, motor yeniden yerleştirir. Sabit etiket her zaman yerinde çizilir, öbür
    etiketler ondan kaçar; nesne taşınınca, kopyalanınca etiket onunla gider. Tek geri
    alma adımı “Etiket”; hiçbir iğne değişmiyorsa hiçbir şey yazılmaz. Kilitli
    katmandaki nesnenin etiketi değişmez. expectedRevision verilmişse ve çizim o sürümde
    değilse hiçbir şey yazılmaz, sonuç conflict olur.
    """
    __slots__ = ()
    id = "cad.labels.pin"
    version = 1
    title = "Etiketi sabitle"
    scope = "document"
    input_type = LabelsPin
    output_type = LabelsPinned
    plan_type = LabelsPinPlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        pins: Sequence[LabelPinChange],
        expected_revision: str | None | Unset = UNSET,
    ) -> LabelsPinned:
        """Etiketi sabitle: Nesnelerin etiketlerini elle sabitler, döndürür, gizler ya da
        serbest bırakır: her değişiklik bir nesnenin bir etiketidir (class: kurallı katmanın
        sınıfının adı; yoksa nesnenin ilk etiketi), pin etiketin ortasının nesnenin
        çapasından uzaklığı (at, metre), açısı (rotation, derece, saat yönünün tersine) ya
        da gizliliğidir (hidden: true); pin null etiketi serbest bırakır, motor yeniden
        yerleştirir. Sabit etiket her zaman yerinde çizilir, öbür etiketler ondan kaçar;
        nesne taşınınca, kopyalanınca etiket onunla gider. Tek geri alma adımı “Etiket”;
        hiçbir iğne değişmiyorsa hiçbir şey yazılmaz. Kilitli katmandaki nesnenin etiketi
        değişmez. expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey
        yazılmaz, sonuç conflict olur.

        Args:
            doc: The drawing it works on.
            pins: The changes, at least one.
            expected_revision: The document revision the input was prepared against, as decimal text.

        Returns:
            LabelsPinned

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, LabelsPin(
            pins=list(pins),
            expected_revision=expected_revision,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        pins: Sequence[LabelPinChange],
        expected_revision: str | None | Unset = UNSET,
    ) -> LabelsPinPlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, LabelsPin(
            pins=list(pins),
            expected_revision=expected_revision,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        pins: Sequence[LabelPinChange],
        expected_revision: str | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, LabelsPin(
            pins=list(pins),
            expected_revision=expected_revision,
        ))


pin = _LabelsPin()
"""Etiketi sabitle (``cad.labels.pin``)."""


__all__ = ["pin"]
