# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.layers``: ``cad.layers.service``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from ._runtime import CommandNote, LocalCommand, UNSET, Unset, _opt  # noqa: F401
from .types import (  # noqa: F401
    FeatureFeed,
    LayerField,
    LayerServiceOperation,
    LayerServiceOperationName,
    LayersService,
    LayersServicePlan,
    LayersServiced,
    ServiceConnection,
    ServiceLayer,
)

if TYPE_CHECKING:
    from .document import Document


class _LayersService(LocalCommand[LayersService, LayersServiced, LayersServicePlan]):
    """``cad.layers.service`` v1. Servis katmanı: Katman ağacına bir harita servisinden
    çizilen katman ekler (add: XYZ ve TMS, WMTS, WMS, OGC API Tiles, ArcGIS REST,
    Google'ın 2B karoları, vektör karolar), nesneleri bir servisten alınan katman ekler
    (addFeed: WFS, OGC API Features, ArcGIS katmanı, GeoJSON adresi; alanlarıyla),
    birini değiştirir (update: ad, servis ya da kaynak) ya da bir servis katmanını siler
    (remove); tek geri alma adımı, adı işlemin. parent katmanın gireceği grup (ya da
    yanına gireceği katman), index gruptaki yeri: ilki en üstte çizilir, verilmezse en
    sona, her şeyin altına girer. connections projenin bağlantılarına eklenir ya da aynı
    kimliklisinin yerini alır; bağlantı yalnız doğrulamanın türünü ve gizli olmayan
    adları taşır, gizli değerler çizime yazılmaz. Servis katmanı nesne tutmaz; servis ya
    da kaynak projenin bağlantılarından birini adlandırır. Nesneler servisten alındıktan
    sonra cad.entities.create ile yazılır; aynı işlem grubunda tek adım olur.
    expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç
    conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik project.changes
    ile gider.
    """
    __slots__ = ()
    id = "cad.layers.service"
    version = 1
    title = "Servis katmanı"
    scope = "document"
    input_type = LayersService
    output_type = LayersServiced
    plan_type = LayersServicePlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        operation: LayerServiceOperation | LayerServiceOperationName,
        connections: Sequence[ServiceConnection] | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        feed: FeatureFeed | None | Unset = UNSET,
        fields: Sequence[LayerField] | None | Unset = UNSET,
        index: int | None | Unset = UNSET,
        layer: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        parent: str | None | Unset = UNSET,
        service: ServiceLayer | None | Unset = UNSET,
    ) -> LayersServiced:
        """Servis katmanı: Katman ağacına bir harita servisinden çizilen katman ekler (add: XYZ
        ve TMS, WMTS, WMS, OGC API Tiles, ArcGIS REST, Google'ın 2B karoları, vektör
        karolar), nesneleri bir servisten alınan katman ekler (addFeed: WFS, OGC API
        Features, ArcGIS katmanı, GeoJSON adresi; alanlarıyla), birini değiştirir (update:
        ad, servis ya da kaynak) ya da bir servis katmanını siler (remove); tek geri alma
        adımı, adı işlemin. parent katmanın gireceği grup (ya da yanına gireceği katman),
        index gruptaki yeri: ilki en üstte çizilir, verilmezse en sona, her şeyin altına
        girer. connections projenin bağlantılarına eklenir ya da aynı kimliklisinin yerini
        alır; bağlantı yalnız doğrulamanın türünü ve gizli olmayan adları taşır, gizli
        değerler çizime yazılmaz. Servis katmanı nesne tutmaz; servis ya da kaynak projenin
        bağlantılarından birini adlandırır. Nesneler servisten alındıktan sonra
        cad.entities.create ile yazılır; aynı işlem grubunda tek adım olur. expectedRevision
        verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç conflict olur.
        Yerel çizim izin istemez; bulut projesine değişiklik project.changes ile gider.

        Args:
            doc: The drawing it works on.
            operation:
            connections: Connections added to the project, or replacing its own of the same id.
            expected_revision: The document revision the input was prepared against, as decimal text.
            feed:
            fields: `addFeed`: the layer's fields (docs/adr/0199 §1).
            index:
            layer: `update`, `remove`: the layer's id.
            name: `add`, `addFeed`: the new layer's name; `update`: a new name.
            parent:
            service:

        Returns:
            LayersServiced

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, LayersService(
            operation=operation,
            connections=_opt(connections, lambda x: list(x)),
            expected_revision=expected_revision,
            feed=feed,
            fields=_opt(fields, lambda x: list(x)),
            index=index,
            layer=layer,
            name=name,
            parent=parent,
            service=service,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        operation: LayerServiceOperation | LayerServiceOperationName,
        connections: Sequence[ServiceConnection] | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        feed: FeatureFeed | None | Unset = UNSET,
        fields: Sequence[LayerField] | None | Unset = UNSET,
        index: int | None | Unset = UNSET,
        layer: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        parent: str | None | Unset = UNSET,
        service: ServiceLayer | None | Unset = UNSET,
    ) -> LayersServicePlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, LayersService(
            operation=operation,
            connections=_opt(connections, lambda x: list(x)),
            expected_revision=expected_revision,
            feed=feed,
            fields=_opt(fields, lambda x: list(x)),
            index=index,
            layer=layer,
            name=name,
            parent=parent,
            service=service,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        operation: LayerServiceOperation | LayerServiceOperationName,
        connections: Sequence[ServiceConnection] | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        feed: FeatureFeed | None | Unset = UNSET,
        fields: Sequence[LayerField] | None | Unset = UNSET,
        index: int | None | Unset = UNSET,
        layer: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        parent: str | None | Unset = UNSET,
        service: ServiceLayer | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, LayersService(
            operation=operation,
            connections=_opt(connections, lambda x: list(x)),
            expected_revision=expected_revision,
            feed=feed,
            fields=_opt(fields, lambda x: list(x)),
            index=index,
            layer=layer,
            name=name,
            parent=parent,
            service=service,
        ))


service = _LayersService()
"""Servis katmanı (``cad.layers.service``)."""


__all__ = ["service"]
