# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.layers``: ``cad.layers.filter``, ``cad.layers.labels``, ``cad.layers.renderer``, ``cad.layers.service``, ``cad.layers.time``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from ._runtime import CommandNote, LocalCommand, UNSET, Unset, _opt  # noqa: F401
from .types import (  # noqa: F401
    FeatureFeed,
    LabelStyle,
    LayerField,
    LayerFilter,
    LayerLabels,
    LayerServiceOperation,
    LayerServiceOperationName,
    LayerTime,
    LayersFilter,
    LayersFilterPlan,
    LayersFiltered,
    LayersLabelled,
    LayersLabels,
    LayersLabelsPlan,
    LayersRendered,
    LayersRenderer,
    LayersRendererPlan,
    LayersService,
    LayersServicePlan,
    LayersServiced,
    LayersTime,
    LayersTimePlan,
    LayersTimed,
    ServiceConnection,
    ServiceLayer,
)

if TYPE_CHECKING:
    from .document import Document


class _LayersFilter(LocalCommand[LayersFilter, LayersFiltered, LayersFilterPlan]):
    """``cad.layers.filter`` v1. Katman süzgeci: Katmanın süzgecini yazar ya da kaldırır
    (filter verilmezse ya da null ise): yalnız süzgeçten geçen nesneler çizilir,
    seçilir, kenetlenir, Öznitelik tablosunda, İşlemler'de ve Veride ara'da görünür.
    Süzgeç bir ifadedir (İfadeyle seç'in dili: Nitelik = 'Arsa' ve $alan > 500; doğru
    olan geçer, yanlış, boş ya da hatalı olan geçmez; $sıra ve $ölçek kullanılamaz) ya
    da nesnelerin kalıcı kimlik listesidir (Seçimden süzgeç) ya da ikisi birden
    (ikisinden de geçmeli). Süzgeç görünümdür: nesneler silinmez, dosya alışverişi ve
    komutlar bütün nesnelerle çalışır. Sonuç süzgeçten geçen ve katmanın bütün nesne
    sayısıdır. Katman ağacının değişikliğidir: tek geri alma adımı “Katman süzgeci”;
    süzgeç aynıysa hiçbir şey yazılmaz. expectedRevision verilmişse ve çizim o sürümde
    değilse hiçbir şey yazılmaz, sonuç conflict olur.
    """
    __slots__ = ()
    id = "cad.layers.filter"
    version = 1
    title = "Katman süzgeci"
    scope = "document"
    input_type = LayersFilter
    output_type = LayersFiltered
    plan_type = LayersFilterPlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        layer: str,
        expected_revision: str | None | Unset = UNSET,
        filter: LayerFilter | None | Unset = UNSET,
    ) -> LayersFiltered:
        """Katman süzgeci: Katmanın süzgecini yazar ya da kaldırır (filter verilmezse ya da
        null ise): yalnız süzgeçten geçen nesneler çizilir, seçilir, kenetlenir, Öznitelik
        tablosunda, İşlemler'de ve Veride ara'da görünür. Süzgeç bir ifadedir (İfadeyle
        seç'in dili: Nitelik = 'Arsa' ve $alan > 500; doğru olan geçer, yanlış, boş ya da
        hatalı olan geçmez; $sıra ve $ölçek kullanılamaz) ya da nesnelerin kalıcı kimlik
        listesidir (Seçimden süzgeç) ya da ikisi birden (ikisinden de geçmeli). Süzgeç
        görünümdür: nesneler silinmez, dosya alışverişi ve komutlar bütün nesnelerle
        çalışır. Sonuç süzgeçten geçen ve katmanın bütün nesne sayısıdır. Katman ağacının
        değişikliğidir: tek geri alma adımı “Katman süzgeci”; süzgeç aynıysa hiçbir şey
        yazılmaz. expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey
        yazılmaz, sonuç conflict olur.

        Args:
            doc: The drawing it works on.
            layer: The layer's id.
            expected_revision: The document revision the input was prepared against, as decimal text.
            filter: Its new filter; absent or null takes it away.

        Returns:
            LayersFiltered

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, LayersFilter(
            layer=layer,
            expected_revision=expected_revision,
            filter=filter,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        layer: str,
        expected_revision: str | None | Unset = UNSET,
        filter: LayerFilter | None | Unset = UNSET,
    ) -> LayersFilterPlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, LayersFilter(
            layer=layer,
            expected_revision=expected_revision,
            filter=filter,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        layer: str,
        expected_revision: str | None | Unset = UNSET,
        filter: LayerFilter | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, LayersFilter(
            layer=layer,
            expected_revision=expected_revision,
            filter=filter,
        ))


filter = _LayersFilter()
"""Katman süzgeci (``cad.layers.filter``)."""


class _LayersLabels(LocalCommand[LayersLabels, LayersLabelled, LayersLabelsPlan]):
    """``cad.layers.labels`` v1. Etiketler: Katmanın etiketlemesini yazar: label tek
    etiketin stilidir (metin şablonu ya da ifadesi, boy, renk, hale, zemin, gölge, çağrı
    çizgisi; noktada çevresinde ya da üstünde, çizgide paralel, kıvrık, yatay ya da eş
    yükselti, alanda yatay, eğik, çevre boyunca, sınır, parsel ya da köşe; yığma,
    kısaltma sözlüğü, küçültme, dışarıda; öncelik 0–10, çakışma, yinelenenler), labels
    katmanın nasıl etiketlendiğidir: single (tek etiket), rules (sıralı sınıflar: adı,
    koşulu ve kendi stili; koşulu tutan her sınıf nesneyi etiketler) ya da off
    (etiketsiz), ve obstacle ile nesneleri öbür etiketlere engeldir (ağırlık 1–10;
    interior ya da boundary). Verilmeyen değişmez, null kaldırır (label null: türün
    varsayılan etiketi; labels null: tek etiket). İfadeler İfadeyle seç'in dilidir;
    $sıra ve $ölçek kullanılamaz. Katman ağacının değişikliğidir: tek geri alma adımı
    “Etiketler”; hepsi aynıysa hiçbir şey yazılmaz. expectedRevision verilmişse ve çizim
    o sürümde değilse hiçbir şey yazılmaz, sonuç conflict olur.
    """
    __slots__ = ()
    id = "cad.layers.labels"
    version = 1
    title = "Etiketler"
    scope = "document"
    input_type = LayersLabels
    output_type = LayersLabelled
    plan_type = LayersLabelsPlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        layer: str,
        expected_revision: str | None | Unset = UNSET,
        label: LabelStyle | None | Unset = UNSET,
        labels: LayerLabels | None | Unset = UNSET,
    ) -> LayersLabelled:
        """Etiketler: Katmanın etiketlemesini yazar: label tek etiketin stilidir (metin şablonu
        ya da ifadesi, boy, renk, hale, zemin, gölge, çağrı çizgisi; noktada çevresinde ya
        da üstünde, çizgide paralel, kıvrık, yatay ya da eş yükselti, alanda yatay, eğik,
        çevre boyunca, sınır, parsel ya da köşe; yığma, kısaltma sözlüğü, küçültme,
        dışarıda; öncelik 0–10, çakışma, yinelenenler), labels katmanın nasıl
        etiketlendiğidir: single (tek etiket), rules (sıralı sınıflar: adı, koşulu ve kendi
        stili; koşulu tutan her sınıf nesneyi etiketler) ya da off (etiketsiz), ve obstacle
        ile nesneleri öbür etiketlere engeldir (ağırlık 1–10; interior ya da boundary).
        Verilmeyen değişmez, null kaldırır (label null: türün varsayılan etiketi; labels
        null: tek etiket). İfadeler İfadeyle seç'in dilidir; $sıra ve $ölçek kullanılamaz.
        Katman ağacının değişikliğidir: tek geri alma adımı “Etiketler”; hepsi aynıysa
        hiçbir şey yazılmaz. expectedRevision verilmişse ve çizim o sürümde değilse hiçbir
        şey yazılmaz, sonuç conflict olur.

        Args:
            doc: The drawing it works on.
            layer: The layer's id.
            expected_revision: The document revision the input was prepared against, as decimal text.
            label: Its single label's style; null: the kinds' default labels. Absent: unchanged.
            labels: How it is labelled; null: a single label. Absent: unchanged.

        Returns:
            LayersLabelled

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, LayersLabels(
            layer=layer,
            expected_revision=expected_revision,
            label=label,
            labels=labels,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        layer: str,
        expected_revision: str | None | Unset = UNSET,
        label: LabelStyle | None | Unset = UNSET,
        labels: LayerLabels | None | Unset = UNSET,
    ) -> LayersLabelsPlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, LayersLabels(
            layer=layer,
            expected_revision=expected_revision,
            label=label,
            labels=labels,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        layer: str,
        expected_revision: str | None | Unset = UNSET,
        label: LabelStyle | None | Unset = UNSET,
        labels: LayerLabels | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, LayersLabels(
            layer=layer,
            expected_revision=expected_revision,
            label=label,
            labels=labels,
        ))


labels = _LayersLabels()
"""Etiketler (``cad.layers.labels``)."""


class _LayersRenderer(LocalCommand[LayersRenderer, LayersRendered, LayersRendererPlan]):
    """``cad.layers.renderer`` v1. Katman stili: Katmanın işleyicisini yazar ya da kaldırır
    (renderer verilmezse ya da null ise katmanın basit görünüşü): single (tek sembol),
    categorized, graduated, rules ve tematik işleyiciler: unclassed (sürekli renk:
    değerin [min, max]'taki payı rampada bir renk, sembolün ana rengi), proportional
    (orantılı sembol: değer sembolün boyu; Alan, Yarıçap ya da Flannery), bivariate (iki
    değişkenli renk: iki değerin sınıfları n × n ızgarada bir renk), dotDensity (nokta
    yoğunluğu: alanın içinde değer / dotValue kadar nokta), chart (pasta, çubuk ya da
    yığılmış çubuk), heatmap (ısı haritası: noktaların dördüncü dereceden (quartic)
    çekirdekle yoğunluğu, rampa; en büyük değer sabit ya da dinamik), cluster (kümeleme:
    yakın noktalar tek işaret ve sayısı), displacement (yayma: üst üste binen noktalar
    halka, iç içe halkalar ya da ızgarada) ve inverted (ters alan: alanların dışı
    boyanır). Semboller kitaplıktan { ref } ya da yerinde yazılır; ifadeler İfadeyle
    seç'in dilidir. Katmanın görünüşüdür: kilitli katman da alır; tek geri alma adımı
    “Katman stili”; aynıysa hiçbir şey yazılmaz. expectedRevision verilmişse ve çizim o
    sürümde değilse hiçbir şey yazılmaz, sonuç conflict olur.
    """
    __slots__ = ()
    id = "cad.layers.renderer"
    version = 1
    title = "Katman stili"
    scope = "document"
    input_type = LayersRenderer
    output_type = LayersRendered
    plan_type = LayersRendererPlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        layer: str,
        expected_revision: str | None | Unset = UNSET,
        renderer: Any | Unset = UNSET,
    ) -> LayersRendered:
        """Katman stili: Katmanın işleyicisini yazar ya da kaldırır (renderer verilmezse ya da
        null ise katmanın basit görünüşü): single (tek sembol), categorized, graduated,
        rules ve tematik işleyiciler: unclassed (sürekli renk: değerin [min, max]'taki payı
        rampada bir renk, sembolün ana rengi), proportional (orantılı sembol: değer sembolün
        boyu; Alan, Yarıçap ya da Flannery), bivariate (iki değişkenli renk: iki değerin
        sınıfları n × n ızgarada bir renk), dotDensity (nokta yoğunluğu: alanın içinde değer
        / dotValue kadar nokta), chart (pasta, çubuk ya da yığılmış çubuk), heatmap (ısı
        haritası: noktaların dördüncü dereceden (quartic) çekirdekle yoğunluğu, rampa; en
        büyük değer sabit ya da dinamik), cluster (kümeleme: yakın noktalar tek işaret ve
        sayısı), displacement (yayma: üst üste binen noktalar halka, iç içe halkalar ya da
        ızgarada) ve inverted (ters alan: alanların dışı boyanır). Semboller kitaplıktan {
        ref } ya da yerinde yazılır; ifadeler İfadeyle seç'in dilidir. Katmanın görünüşüdür:
        kilitli katman da alır; tek geri alma adımı “Katman stili”; aynıysa hiçbir şey
        yazılmaz. expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey
        yazılmaz, sonuç conflict olur.

        Args:
            doc: The drawing it works on.
            layer: The layer's id.
            expected_revision: The document revision the input was prepared against, as decimal text.
            renderer: Its new renderer; absent or null takes it away.

        Returns:
            LayersRendered

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, LayersRenderer(
            layer=layer,
            expected_revision=expected_revision,
            renderer=renderer,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        layer: str,
        expected_revision: str | None | Unset = UNSET,
        renderer: Any | Unset = UNSET,
    ) -> LayersRendererPlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, LayersRenderer(
            layer=layer,
            expected_revision=expected_revision,
            renderer=renderer,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        layer: str,
        expected_revision: str | None | Unset = UNSET,
        renderer: Any | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, LayersRenderer(
            layer=layer,
            expected_revision=expected_revision,
            renderer=renderer,
        ))


renderer = _LayersRenderer()
"""Katman stili (``cad.layers.renderer``)."""


class _LayersService(LocalCommand[LayersService, LayersServiced, LayersServicePlan]):
    """``cad.layers.service`` v1. Servis katmanı: Katman ağacına bir harita servisinden
    çizilen katman ekler (add: XYZ ve TMS, WMTS, WMS, OGC API Tiles, ArcGIS REST,
    Google'ın 2B karoları, vektör karolar), nesneleri bir servisten alınan katman ekler
    (addFeed: WFS, OGC API Features, ArcGIS katmanı, GeoJSON adresi; alanlarıyla),
    birini değiştirir (update: ad, servis ya da kaynak) ya da bir servis katmanını siler
    (remove); tek geri alma adımı, adı işlemin. parent katmanın gireceği grup (ya da
    yanına gireceği katman), index gruptaki yeri: ilki en üstte çizilir, verilmezse en
    sona, her şeyin altına girer. connections projenin bağlantılarına eklenir ya da aynı
    kimliklisinin yerini alır; bağlantı yalnız doğrulamanın türünü ve gizli olmayan
    adları taşır, gizli değerler çizime yazılmaz. Servis katmanı nesne tutmaz; servis ya
    da kaynak projenin bağlantılarından birini adlandırır. Nesneler servisten alındıktan
    sonra cad.entities.create ile yazılır; aynı işlem grubunda tek adım olur.
    expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç
    conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik project.changes
    ile gider.
    """
    __slots__ = ()
    id = "cad.layers.service"
    version = 1
    title = "Servis katmanı"
    scope = "document"
    input_type = LayersService
    output_type = LayersServiced
    plan_type = LayersServicePlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        operation: LayerServiceOperation | LayerServiceOperationName,
        connections: Sequence[ServiceConnection] | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        feed: FeatureFeed | None | Unset = UNSET,
        fields: Sequence[LayerField] | None | Unset = UNSET,
        index: int | None | Unset = UNSET,
        layer: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        parent: str | None | Unset = UNSET,
        service: ServiceLayer | None | Unset = UNSET,
    ) -> LayersServiced:
        """Servis katmanı: Katman ağacına bir harita servisinden çizilen katman ekler (add: XYZ
        ve TMS, WMTS, WMS, OGC API Tiles, ArcGIS REST, Google'ın 2B karoları, vektör
        karolar), nesneleri bir servisten alınan katman ekler (addFeed: WFS, OGC API
        Features, ArcGIS katmanı, GeoJSON adresi; alanlarıyla), birini değiştirir (update:
        ad, servis ya da kaynak) ya da bir servis katmanını siler (remove); tek geri alma
        adımı, adı işlemin. parent katmanın gireceği grup (ya da yanına gireceği katman),
        index gruptaki yeri: ilki en üstte çizilir, verilmezse en sona, her şeyin altına
        girer. connections projenin bağlantılarına eklenir ya da aynı kimliklisinin yerini
        alır; bağlantı yalnız doğrulamanın türünü ve gizli olmayan adları taşır, gizli
        değerler çizime yazılmaz. Servis katmanı nesne tutmaz; servis ya da kaynak projenin
        bağlantılarından birini adlandırır. Nesneler servisten alındıktan sonra
        cad.entities.create ile yazılır; aynı işlem grubunda tek adım olur. expectedRevision
        verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç conflict olur.
        Yerel çizim izin istemez; bulut projesine değişiklik project.changes ile gider.

        Args:
            doc: The drawing it works on.
            operation:
            connections: Connections added to the project, or replacing its own of the same id.
            expected_revision: The document revision the input was prepared against, as decimal text.
            feed:
            fields: `addFeed`: the layer's fields (docs/adr/0199 §1).
            index:
            layer: `update`, `remove`: the layer's id.
            name: `add`, `addFeed`: the new layer's name; `update`: a new name.
            parent:
            service:

        Returns:
            LayersServiced

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, LayersService(
            operation=operation,
            connections=_opt(connections, lambda x: list(x)),
            expected_revision=expected_revision,
            feed=feed,
            fields=_opt(fields, lambda x: list(x)),
            index=index,
            layer=layer,
            name=name,
            parent=parent,
            service=service,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        operation: LayerServiceOperation | LayerServiceOperationName,
        connections: Sequence[ServiceConnection] | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        feed: FeatureFeed | None | Unset = UNSET,
        fields: Sequence[LayerField] | None | Unset = UNSET,
        index: int | None | Unset = UNSET,
        layer: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        parent: str | None | Unset = UNSET,
        service: ServiceLayer | None | Unset = UNSET,
    ) -> LayersServicePlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, LayersService(
            operation=operation,
            connections=_opt(connections, lambda x: list(x)),
            expected_revision=expected_revision,
            feed=feed,
            fields=_opt(fields, lambda x: list(x)),
            index=index,
            layer=layer,
            name=name,
            parent=parent,
            service=service,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        operation: LayerServiceOperation | LayerServiceOperationName,
        connections: Sequence[ServiceConnection] | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        feed: FeatureFeed | None | Unset = UNSET,
        fields: Sequence[LayerField] | None | Unset = UNSET,
        index: int | None | Unset = UNSET,
        layer: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        parent: str | None | Unset = UNSET,
        service: ServiceLayer | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, LayersService(
            operation=operation,
            connections=_opt(connections, lambda x: list(x)),
            expected_revision=expected_revision,
            feed=feed,
            fields=_opt(fields, lambda x: list(x)),
            index=index,
            layer=layer,
            name=name,
            parent=parent,
            service=service,
        ))


service = _LayersService()
"""Servis katmanı (``cad.layers.service``)."""


class _LayersTime(LocalCommand[LayersTime, LayersTimed, LayersTimePlan]):
    """``cad.layers.time`` v1. Katmanın zamanı: Katmanın zaman ayarını yazar ya da kaldırır
    (time verilmezse ya da null ise): nesnelerin başlangıcı (anlık katmanda anı) ve
    bitişi hangi özniteliklerdedir, kimlik alanı (iki zamanı karşılaştırmanın anahtarı)
    ve Birikimli (nesne başlangıcından sonra hep görünür). Değerler öznitelik metnidir:
    YYYY-AA-GG ya da GG.AA.YYYY, isteğe bağlı saat (T ya da boşlukla SS:DD[:ss[.kesir]])
    ve saat dilimi (Z, +SS:DD …); boş başlangıç ya da bitiş açık uçtur. Zaman sürgüsü,
    Yeni sürüm oluştur ve Sona erdir bu ayarı kullanır; sürgü bir görünümdür, çizimi
    değiştirmez. Katman ağacının değişikliğidir: tek geri alma adımı “Zaman ayarları”;
    ayar aynıysa hiçbir şey yazılmaz. expectedRevision verilmişse ve çizim o sürümde
    değilse hiçbir şey yazılmaz, sonuç conflict olur.
    """
    __slots__ = ()
    id = "cad.layers.time"
    version = 1
    title = "Katmanın zamanı"
    scope = "document"
    input_type = LayersTime
    output_type = LayersTimed
    plan_type = LayersTimePlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        layer: str,
        expected_revision: str | None | Unset = UNSET,
        time: LayerTime | None | Unset = UNSET,
    ) -> LayersTimed:
        """Katmanın zamanı: Katmanın zaman ayarını yazar ya da kaldırır (time verilmezse ya da
        null ise): nesnelerin başlangıcı (anlık katmanda anı) ve bitişi hangi
        özniteliklerdedir, kimlik alanı (iki zamanı karşılaştırmanın anahtarı) ve Birikimli
        (nesne başlangıcından sonra hep görünür). Değerler öznitelik metnidir: YYYY-AA-GG ya
        da GG.AA.YYYY, isteğe bağlı saat (T ya da boşlukla SS:DD[:ss[.kesir]]) ve saat
        dilimi (Z, +SS:DD …); boş başlangıç ya da bitiş açık uçtur. Zaman sürgüsü, Yeni
        sürüm oluştur ve Sona erdir bu ayarı kullanır; sürgü bir görünümdür, çizimi
        değiştirmez. Katman ağacının değişikliğidir: tek geri alma adımı “Zaman ayarları”;
        ayar aynıysa hiçbir şey yazılmaz. expectedRevision verilmişse ve çizim o sürümde
        değilse hiçbir şey yazılmaz, sonuç conflict olur.

        Args:
            doc: The drawing it works on.
            layer: The layer's id.
            expected_revision: The document revision the input was prepared against, as decimal text.
            time: Its new time setting; absent or null takes it away.

        Returns:
            LayersTimed

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, LayersTime(
            layer=layer,
            expected_revision=expected_revision,
            time=time,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        layer: str,
        expected_revision: str | None | Unset = UNSET,
        time: LayerTime | None | Unset = UNSET,
    ) -> LayersTimePlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, LayersTime(
            layer=layer,
            expected_revision=expected_revision,
            time=time,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        layer: str,
        expected_revision: str | None | Unset = UNSET,
        time: LayerTime | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, LayersTime(
            layer=layer,
            expected_revision=expected_revision,
            time=time,
        ))


time = _LayersTime()
"""Katmanın zamanı (``cad.layers.time``)."""


__all__ = ["filter", "labels", "renderer", "service", "time"]
