# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.network``: ``cad.network.define``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from ._runtime import CommandNote, LocalCommand, UNSET, Unset, _opt  # noqa: F401
from .types import (  # noqa: F401
    NetworkDef,
    NetworkDefine,
    NetworkDefineOperation,
    NetworkDefineOperationName,
    NetworkDefined,
)

if TYPE_CHECKING:
    from .document import Document


class _NetworkDefine(LocalCommand[NetworkDefine, NetworkDefined, NetworkDefined]):
    """``cad.network.define`` v1. Ağ tanımı: Projenin ağlarına bir ağ tanımı yazar (set:
    aynı kimlikli ağın yerini alır, yoksa sona eklenir) ya da birini siler (remove). Ağ,
    katmanlardan her analizde kurulan grafın tanımıdır: kenar katmanları (çizgi, çoklu
    çizgi ve yaylar; isteğe bağlı süzgeç ifadesi), düğüm katmanları (bağlantı, kaynak ya
    da vana; süzgeç ve kapalı ifadesi), bağlanma (ends: uçlarda, bir uç başka kenara
    değiyorsa orada; vertices: bütün köşelerde de) ve tolerans (m), yön (both, digitized
    ya da field: alanın ileri, geri ve kapalı değerleri), uzunluktan başka maliyetler
    (speed: hız alanından dakika, varsayılan hızla; field: kenarın bütününün maliyeti)
    ve kapalı kenarların ifadesi. Ağ proje ayarıdır: yazmak çizimi kirli yapar, geri
    alma adımı değildir. Çizimde olmayan katmanı adlandıran ağ yazılır, unknown_layer
    uyarısıyla. Analizler (en kısa yol, hizmet alanı, en yakın tesis, maliyet matrisi,
    şebeke izleme) çizimi değiştirmez; sonuçları cad.entities.create ile yazılır.
    expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç
    conflict olur.
    """
    __slots__ = ()
    id = "cad.network.define"
    version = 1
    title = "Ağ tanımı"
    scope = "document"
    input_type = NetworkDefine
    output_type = NetworkDefined
    plan_type = NetworkDefined

    def __call__(
        self,
        doc: Document,
        /,
        *,
        operation: NetworkDefineOperation | NetworkDefineOperationName,
        expected_revision: str | None | Unset = UNSET,
        id: str | None | Unset = UNSET,
        network: NetworkDef | None | Unset = UNSET,
    ) -> NetworkDefined:
        """Ağ tanımı: Projenin ağlarına bir ağ tanımı yazar (set: aynı kimlikli ağın yerini
        alır, yoksa sona eklenir) ya da birini siler (remove). Ağ, katmanlardan her analizde
        kurulan grafın tanımıdır: kenar katmanları (çizgi, çoklu çizgi ve yaylar; isteğe
        bağlı süzgeç ifadesi), düğüm katmanları (bağlantı, kaynak ya da vana; süzgeç ve
        kapalı ifadesi), bağlanma (ends: uçlarda, bir uç başka kenara değiyorsa orada;
        vertices: bütün köşelerde de) ve tolerans (m), yön (both, digitized ya da field:
        alanın ileri, geri ve kapalı değerleri), uzunluktan başka maliyetler (speed: hız
        alanından dakika, varsayılan hızla; field: kenarın bütününün maliyeti) ve kapalı
        kenarların ifadesi. Ağ proje ayarıdır: yazmak çizimi kirli yapar, geri alma adımı
        değildir. Çizimde olmayan katmanı adlandıran ağ yazılır, unknown_layer uyarısıyla.
        Analizler (en kısa yol, hizmet alanı, en yakın tesis, maliyet matrisi, şebeke
        izleme) çizimi değiştirmez; sonuçları cad.entities.create ile yazılır.
        expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç
        conflict olur.

        Args:
            doc: The drawing it works on.
            operation:
            expected_revision: The document revision the input was prepared against, as decimal text.
            id:
            network:

        Returns:
            NetworkDefined

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, NetworkDefine(
            operation=operation,
            expected_revision=expected_revision,
            id=id,
            network=network,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        operation: NetworkDefineOperation | NetworkDefineOperationName,
        expected_revision: str | None | Unset = UNSET,
        id: str | None | Unset = UNSET,
        network: NetworkDef | None | Unset = UNSET,
    ) -> NetworkDefined:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, NetworkDefine(
            operation=operation,
            expected_revision=expected_revision,
            id=id,
            network=network,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        operation: NetworkDefineOperation | NetworkDefineOperationName,
        expected_revision: str | None | Unset = UNSET,
        id: str | None | Unset = UNSET,
        network: NetworkDef | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, NetworkDefine(
            operation=operation,
            expected_revision=expected_revision,
            id=id,
            network=network,
        ))


define = _NetworkDefine()
"""Ağ tanımı (``cad.network.define``)."""


__all__ = ["define"]
