# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.point``: ``cad.point.create``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from ._runtime import CommandNote, LocalCommand, UNSET, Unset, _opt  # noqa: F401
from .types import (  # noqa: F401
    PointCreate,
    PointCreated,
    PointPlan,
    Vec2,
    Vec2Like,
)

if TYPE_CHECKING:
    from .document import Document


class _PointCreate(LocalCommand[PointCreate, PointCreated, PointPlan]):
    """``cad.point.create`` v1. Nokta oluştur: Açık çizimde verilen katmana bir nokta
    nesnesi ekler; isteğe bağlı kotu ve yanında görünen yazısıyla. Tek geri alma
    adımıdır. Nokta aracı her nokta için bu komutu bir kez çalıştırır. Katman girdide
    açıkça verilir: kilitli katmana yazılmaz, gizli katmana uyarıyla yazılır.
    expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç
    conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik project.changes
    ile gider.
    """
    __slots__ = ()
    id = "cad.point.create"
    version = 1
    title = "Nokta oluştur"
    scope = "document"
    input_type = PointCreate
    output_type = PointCreated
    plan_type = PointPlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        p: Vec2Like,
        attrs: Mapping[str, str] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        label: str | None | Unset = UNSET,
        symbol: str | None | Unset = UNSET,
        z: float | None | Unset = UNSET,
    ) -> PointCreated:
        """Nokta oluştur: Açık çizimde verilen katmana bir nokta nesnesi ekler; isteğe bağlı
        kotu ve yanında görünen yazısıyla. Tek geri alma adımıdır. Nokta aracı her nokta
        için bu komutu bir kez çalıştırır. Katman girdide açıkça verilir: kilitli katmana
        yazılmaz, gizli katmana uyarıyla yazılır. expectedRevision verilmişse ve çizim o
        sürümde değilse hiçbir şey yazılmaz, sonuç conflict olur. Yerel çizim izin istemez;
        bulut projesine değişiklik project.changes ile gider.

        Args:
            doc: The drawing it works on.
            layer_id: The layer it goes on: a layer's id (`LayerNode.id`), not a group's.
            p: Where it is: x east (Y), y north (X), in the project's units (m), float64.
            attrs: GIS attributes, text in v1. Absent: none.
            color: Colour override (`EntityBase.color`). Absent: the layer's colour (katmana göre).
            expected_revision: The document revision the input was prepared against, as decimal text
                (from a plan, or the document). When given and the document is no
                longer at it, nothing is written and the answer is `conflict`.
            label: The text shown beside it (`EntityBase.label`): a point's name, a spot
                elevation. Absent: none.
            symbol: Its own symbol, a library item's id (`EntityBase.symbol`), drawn
                instead of its layer's style: an object template's (docs/adr/0176).
                The id is not looked up: the libraries are the host's. Absent: the
                layer's style.
            z: Its elevation (kot), in metres. Absent: none.

        Returns:
            PointCreated

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, PointCreate(
            layer_id=layer_id,
            p=Vec2.of(p),
            attrs=_opt(attrs, lambda x: dict(x)),
            color=color,
            expected_revision=expected_revision,
            label=label,
            symbol=symbol,
            z=z,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        p: Vec2Like,
        attrs: Mapping[str, str] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        label: str | None | Unset = UNSET,
        symbol: str | None | Unset = UNSET,
        z: float | None | Unset = UNSET,
    ) -> PointPlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, PointCreate(
            layer_id=layer_id,
            p=Vec2.of(p),
            attrs=_opt(attrs, lambda x: dict(x)),
            color=color,
            expected_revision=expected_revision,
            label=label,
            symbol=symbol,
            z=z,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        p: Vec2Like,
        attrs: Mapping[str, str] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        label: str | None | Unset = UNSET,
        symbol: str | None | Unset = UNSET,
        z: float | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, PointCreate(
            layer_id=layer_id,
            p=Vec2.of(p),
            attrs=_opt(attrs, lambda x: dict(x)),
            color=color,
            expected_revision=expected_revision,
            label=label,
            symbol=symbol,
            z=z,
        ))


create = _PointCreate()
"""Nokta oluştur (``cad.point.create``)."""


__all__ = ["create"]
