# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.polygon``: ``cad.polygon.create``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from ._runtime import CommandNote, LocalCommand, UNSET, Unset, _opt  # noqa: F401
from .types import (  # noqa: F401
    PolygonCreate,
    PolygonCreated,
    PolygonPlan,
    RingGeometry,
    Vec2,
    Vec2Like,
)

if TYPE_CHECKING:
    from .document import Document


class _PolygonCreate(LocalCommand[PolygonCreate, PolygonCreated, PolygonPlan]):
    """``cad.polygon.create`` v1. Kapalı alan oluştur: Açık çizimde verilen katmana
    köşeleri, isteğe bağlı yay değerleri ve delikleriyle bir kapalı alan ekler; tek geri
    alma adımıdır. Katman girdide açıkça verilir: kilitli katmana yazılmaz, gizli
    katmana uyarıyla yazılır. expectedRevision verilmişse ve çizim o sürümde değilse
    hiçbir şey yazılmaz, sonuç conflict olur. Yerel çizim izin istemez; bulut projesine
    değişiklik project.changes ile gider.
    """
    __slots__ = ()
    id = "cad.polygon.create"
    version = 1
    title = "Kapalı alan oluştur"
    scope = "document"
    input_type = PolygonCreate
    output_type = PolygonCreated
    plan_type = PolygonPlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        pts: Sequence[Vec2Like],
        attrs: Mapping[str, str] | None | Unset = UNSET,
        bulges: Sequence[float] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        holes: Sequence[RingGeometry] | None | Unset = UNSET,
    ) -> PolygonCreated:
        """Kapalı alan oluştur: Açık çizimde verilen katmana köşeleri, isteğe bağlı yay
        değerleri ve delikleriyle bir kapalı alan ekler; tek geri alma adımıdır. Katman
        girdide açıkça verilir: kilitli katmana yazılmaz, gizli katmana uyarıyla yazılır.
        expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç
        conflict olur. Yerel çizim izin istemez; bulut projesine değişiklik project.changes
        ile gider.

        Args:
            doc: The drawing it works on.
            layer_id: The layer it goes on: a layer's id (`LayerNode.id`), not a group's.
            pts: Corners of the outer ring in order: x east (Y), y north (X), in the
                project's units (m), float64. At least 3; the first is not repeated.
            attrs: GIS attributes, text in v1. Absent: none.
            bulges: One bulge per edge, the closing edge (last corner → first) last:
                tan(θ/4) of the edge's included angle, positive counter-clockwise, 0
                straight. Absent: every edge is straight.
            color: Colour override (`EntityBase.color`). Absent: the layer's colour (katmana göre).
            expected_revision: The document revision the input was prepared against, as decimal text
                (from a plan, or the document). When given and the document is no
                longer at it, nothing is written and the answer is `conflict`.
            holes: Holes: closed rings of at least 3 corners, each with one bulge per edge when it has bulges.

        Returns:
            PolygonCreated

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, PolygonCreate(
            layer_id=layer_id,
            pts=[Vec2.of(p) for p in pts],
            attrs=_opt(attrs, lambda x: dict(x)),
            bulges=_opt(bulges, lambda x: list(x)),
            color=color,
            expected_revision=expected_revision,
            holes=_opt(holes, lambda x: list(x)),
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        pts: Sequence[Vec2Like],
        attrs: Mapping[str, str] | None | Unset = UNSET,
        bulges: Sequence[float] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        holes: Sequence[RingGeometry] | None | Unset = UNSET,
    ) -> PolygonPlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, PolygonCreate(
            layer_id=layer_id,
            pts=[Vec2.of(p) for p in pts],
            attrs=_opt(attrs, lambda x: dict(x)),
            bulges=_opt(bulges, lambda x: list(x)),
            color=color,
            expected_revision=expected_revision,
            holes=_opt(holes, lambda x: list(x)),
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        layer_id: str,
        pts: Sequence[Vec2Like],
        attrs: Mapping[str, str] | None | Unset = UNSET,
        bulges: Sequence[float] | None | Unset = UNSET,
        color: str | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        holes: Sequence[RingGeometry] | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, PolygonCreate(
            layer_id=layer_id,
            pts=[Vec2.of(p) for p in pts],
            attrs=_opt(attrs, lambda x: dict(x)),
            bulges=_opt(bulges, lambda x: list(x)),
            color=color,
            expected_revision=expected_revision,
            holes=_opt(holes, lambda x: list(x)),
        ))


create = _PolygonCreate()
"""Kapalı alan oluştur (``cad.polygon.create``)."""


__all__ = ["create"]
