# Generated by scripts/python/sdk.py from the command catalog
# (apps/web/src/contracts/generated/commandCatalog.json). Do not edit: run
# `python3 scripts/python/sdk.py` after the catalog changes.
"""``kentos.cad.scenarios``: ``cad.scenarios.edit``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

from ._runtime import CommandNote, LocalCommand, UNSET, Unset, _opt  # noqa: F401
from .types import (  # noqa: F401
    ScenarioOperation,
    ScenarioOperationName,
    ScenariosEdit,
    ScenariosEditPlan,
    ScenariosEdited,
)

if TYPE_CHECKING:
    from .document import Document


class _ScenariosEdit(LocalCommand[ScenariosEdit, ScenariosEdited, ScenariosEditPlan]):
    """``cad.scenarios.edit`` v1. Senaryo: Bir senaryo oluşturur (create) ya da birini
    mevcut duruma uygular (apply); tek geri alma adımı, adı işlemin. Senaryo ağacın en
    üstünde, senaryo olarak işaretli bir gruptur: verilen ana katmanların (senaryo
    dışındaki katmanların) her biri için aynı adlı, aynı stil, alanlar, zaman ayarı ve
    kenetle bir katman açılır, kaynağının yerine geçer (replaces); copyObjects açıksa
    (varsayılan) nesneleri yeni kimliklerle kopyalanır. Kilitli kaynağın nesneleri
    kopyalanmaz (layer_locked). apply: senaryonun bir ana katmanın yerine geçen her
    katmanı, o katmanın nesnelerini kendi nesneleriyle değiştirir (nesneler kimliklerini
    korur) ve silinir; grup senaryo olmaktan çıkar, öbür katmanlarıyla sıradan bir grup
    olarak kalır (katmanı kalmazsa silinir). Bir senaryoyu göstermek (grubunu görünür,
    yerine geçtiği ana katmanları gizli yapmak) bir görünümdür, komut değildir.
    expectedRevision verilmişse ve çizim o sürümde değilse hiçbir şey yazılmaz, sonuç
    conflict olur.
    """
    __slots__ = ()
    id = "cad.scenarios.edit"
    version = 1
    title = "Senaryo"
    scope = "document"
    input_type = ScenariosEdit
    output_type = ScenariosEdited
    plan_type = ScenariosEditPlan

    def __call__(
        self,
        doc: Document,
        /,
        *,
        operation: ScenarioOperation | ScenarioOperationName,
        copy_objects: bool | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        layers: Sequence[str] | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        note: str | None | Unset = UNSET,
        scenario: str | None | Unset = UNSET,
    ) -> ScenariosEdited:
        """Senaryo: Bir senaryo oluşturur (create) ya da birini mevcut duruma uygular (apply);
        tek geri alma adımı, adı işlemin. Senaryo ağacın en üstünde, senaryo olarak işaretli
        bir gruptur: verilen ana katmanların (senaryo dışındaki katmanların) her biri için
        aynı adlı, aynı stil, alanlar, zaman ayarı ve kenetle bir katman açılır, kaynağının
        yerine geçer (replaces); copyObjects açıksa (varsayılan) nesneleri yeni kimliklerle
        kopyalanır. Kilitli kaynağın nesneleri kopyalanmaz (layer_locked). apply: senaryonun
        bir ana katmanın yerine geçen her katmanı, o katmanın nesnelerini kendi nesneleriyle
        değiştirir (nesneler kimliklerini korur) ve silinir; grup senaryo olmaktan çıkar,
        öbür katmanlarıyla sıradan bir grup olarak kalır (katmanı kalmazsa silinir). Bir
        senaryoyu göstermek (grubunu görünür, yerine geçtiği ana katmanları gizli yapmak)
        bir görünümdür, komut değildir. expectedRevision verilmişse ve çizim o sürümde
        değilse hiçbir şey yazılmaz, sonuç conflict olur.

        Args:
            doc: The drawing it works on.
            operation:
            copy_objects: `create`: whether their objects are copied (absent: true).
            expected_revision: The document revision the input was prepared against, as decimal text.
            layers: `create`: the base layers it copies, in order.
            name: `create`: the scenario's name (trimmed).
            note: `create`: the scenario's note.
            scenario: `apply`: the scenario group's id.

        Returns:
            ScenariosEdited

        Raises:
            CommandFailed, NeedsInput, RevisionConflict: the command's refusal;
                nothing was written. Warnings go to :mod:`warnings` as CommandWarning.
        """
        return self.execute_input(doc, ScenariosEdit(
            operation=operation,
            copy_objects=copy_objects,
            expected_revision=expected_revision,
            layers=_opt(layers, lambda x: list(x)),
            name=name,
            note=note,
            scenario=scenario,
        ))

    def plan(
        self,
        doc: Document,
        /,
        *,
        operation: ScenarioOperation | ScenarioOperationName,
        copy_objects: bool | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        layers: Sequence[str] | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        note: str | None | Unset = UNSET,
        scenario: str | None | Unset = UNSET,
    ) -> ScenariosEditPlan:
        """What it would write, with nothing written; the plan's ``revision``, given as
        ``expected_revision``, writes exactly this plan or nothing.
        """
        return self.plan_input(doc, ScenariosEdit(
            operation=operation,
            copy_objects=copy_objects,
            expected_revision=expected_revision,
            layers=_opt(layers, lambda x: list(x)),
            name=name,
            note=note,
            scenario=scenario,
        ))

    def validate(
        self,
        doc: Document,
        /,
        *,
        operation: ScenarioOperation | ScenarioOperationName,
        copy_objects: bool | None | Unset = UNSET,
        expected_revision: str | None | Unset = UNSET,
        layers: Sequence[str] | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        note: str | None | Unset = UNSET,
        scenario: str | None | Unset = UNSET,
    ) -> list[CommandNote]:
        """Checks the input against the drawing, writing nothing; its warnings.
        A refusal raises as for the call.
        """
        return self.validate_input(doc, ScenariosEdit(
            operation=operation,
            copy_objects=copy_objects,
            expected_revision=expected_revision,
            layers=_opt(layers, lambda x: list(x)),
            name=name,
            note=note,
            scenario=scenario,
        ))


edit = _ScenariosEdit()
"""Senaryo (``cad.scenarios.edit``)."""


__all__ = ["edit"]
