# The native module's surface (crates/native/python/src/lib.rs); kentos.cad wraps it.
from os import PathLike

__version__: str

class HostError(Exception):
    """args: (code, message)."""

class Session:
    @staticmethod
    def new_project(name: str, srid: int, plot_scale: float, workspace: str, drawing_font: str) -> Session: ...
    @staticmethod
    def open(path: str | PathLike[str]) -> Session: ...
    @staticmethod
    def from_bytes(data: bytes) -> Session: ...
    def run(self, command: str, op: str, input: str, version: int | None = None) -> str: ...
    def save(self, path: str | PathLike[str] | None = None) -> str: ...
    def to_bytes(self) -> bytes: ...
    def summary(self) -> str: ...
    def layers(self) -> str: ...
    def blocks(self) -> str: ...
    def entities(
        self,
        layer: str | None = None,
        kinds: list[str] | None = None,
        bbox: tuple[float, float, float, float] | None = None,
        after: str | None = None,
        limit: int | None = None,
    ) -> str: ...
    def entity(self, uid: str) -> str: ...
    def measure(self, uid: str) -> str: ...
    def undo(self) -> str | None: ...
    def redo(self) -> str | None: ...
    def begin_group(self, label: str) -> None: ...
    def end_group(self) -> bool: ...
    def cancel_group(self) -> bool: ...

def catalog() -> str: ...
def local_commands() -> list[tuple[str, int]]: ...
