# The native module's surface (crates/native/python/src/lib.rs); kentos.cad wraps it.
from os import PathLike

__version__: str

class HostError(Exception):
    """args: (code, message)."""

class Session:
    @staticmethod
    def new_project(name: str, srid: int, plot_scale: float, workspace: str, drawing_font: str) -> Session: ...
    @staticmethod
    def open(path: str | PathLike[str]) -> Session: ...
    @staticmethod
    def from_bytes(data: bytes) -> Session: ...
    def run(self, command: str, op: str, input: str, version: int | None = None) -> str: ...
    def save(self, path: str | PathLike[str] | None = None) -> str: ...
    def to_bytes(self) -> bytes: ...
    def summary(self) -> str: ...
    def layers(self) -> str: ...
    def blocks(self) -> str: ...
    def entities(
        self,
        layer: str | None = None,
        kinds: list[str] | None = None,
        bbox: tuple[float, float, float, float] | None = None,
        after: str | None = None,
        limit: int | None = None,
    ) -> str: ...
    def entity(self, uid: str) -> str: ...
    def measure(self, uid: str) -> str: ...
    def undo(self) -> str | None: ...
    def redo(self) -> str | None: ...
    def begin_group(self, label: str) -> None: ...
    def end_group(self) -> bool: ...
    def cancel_group(self) -> bool: ...

def catalog() -> str: ...
def local_commands() -> list[tuple[str, int]]: ...

# kentos.services (crates/native/python/src/services.rs, docs/adr/0208 §15): JSON text in the contract's shapes.
def services_presets() -> str: ...
def services_preset_layer(id: str) -> tuple[str, str | None] | None: ...
def services_auth_missing(connection: str, secret: str | None = None) -> str | None: ...
def services_auth_apply(connection: str, secret: str, request: str, token: str | None = None) -> str: ...
def services_token_request(connection: str, secret: str, referer: str) -> str | None: ...
def services_read_token(connection: str, body: str, now_ms: float) -> str: ...
def services_taken_words(taken: int, matched: int | None, skipped: str, dropped: int, capped: bool, srid: int) -> str: ...
def services_layer_colors(layers: int) -> tuple[str, str]: ...
def services_same_system(settings: str, srid: int) -> bool: ...
def services_to_project(result: str, settings: str, srid: int) -> str: ...
def services_box_in(
    bbox: tuple[float, float, float, float], settings: str, srid: int
) -> tuple[float, float, float, float] | None: ...
def services_new_objects(entities: str) -> str: ...
def services_infer_fields(rows: str) -> str: ...

class ServiceReading:
    def __init__(self, kind: str, url: str) -> None: ...
    def first(self) -> str | None: ...
    def answer(self, body: str) -> str | None: ...
    def offer(self) -> str | None: ...
    def layer(self, choice: str, project: int) -> str: ...

class FeedReading:
    def __init__(self, kind: str, url: str) -> None: ...
    def first(self) -> str | None: ...
    def answer(self, body: str) -> str | None: ...
    def offer(self) -> str | None: ...
    def geojson(self) -> bool: ...
    def systems(self, id: str, project: int) -> list[int]: ...
    def asked_srid(self, id: str, project: int, choice: int | None = None) -> int | None: ...
    def feed(self, choice: str, project: int) -> str: ...

class FeedTaking:
    def __init__(
        self, feed: str, most: int, geojson: bool, area: tuple[float, float, float, float] | None = None
    ) -> None: ...
    def first(self) -> str: ...
    def answer(self, body: str) -> str: ...
    @property
    def srid(self) -> int: ...
    @property
    def taken(self) -> int: ...
    @property
    def matched(self) -> int | None: ...
    def skipped(self) -> str: ...

# kentos.network (docs/adr/0209 §11).
class Network:
    @staticmethod
    def build(session: Session, id: str) -> Network: ...
    def summary(self) -> str: ...
    def locate(self, x: float, y: float, reach: float) -> str: ...
    def route(self, stops: str, barriers: str, reach: float, cost: int, reorder: str) -> str: ...
    def service_area(
        self,
        facilities: str,
        breaks: list[float],
        reach: float,
        cost: int,
        toward: bool,
        separate: bool,
        barriers: str,
        trim: float,
        rings: bool,
        areas: bool,
    ) -> str: ...
    def nearest(
        self,
        origins: str,
        targets: str,
        reach: float,
        cost: int,
        reverse: bool,
        barriers: str,
        paths: bool,
        k: int | None = None,
        cutoff: float | None = None,
    ) -> str: ...
    def trace(self, starts: str, barriers: str, reach: float, kind: str) -> str: ...
    def check(self) -> str: ...

# kentos.temporal (docs/adr/0210 §11). Moments are milliseconds since 1970, open ends ±inf.
_Crossed = tuple[float, float, str] | None
_Summary = tuple[tuple[int, int, int], tuple[float, float] | None]

def time_read(text: str) -> tuple[int, float]: ...
def time_write(t: float, date_only: bool) -> str: ...
def time_show(t: float, unit_name: str) -> str: ...
def time_floor(t: float, unit_name: str) -> float: ...
def time_auto_step(start: float, end: float) -> tuple[int, str]: ...
def time_positions(start: float, end: float, n: int, unit_name: str) -> tuple[float, int] | None: ...
def time_position(anchor: float, n: int, unit_name: str, k: int) -> float: ...
def time_of(ranged: bool, cumulative: bool, start: str | None = None, end: str | None = None) -> _Crossed: ...
def time_shows(s: float, e: float, mode: str, a: float, b: float | None = None) -> bool: ...
def time_values(
    ranged: bool, cumulative: bool, values: list[tuple[str | None, str | None]]
) -> tuple[list[_Crossed], _Summary]: ...
def temporal_layer(session: Session, layer: str) -> tuple[list[str], list[_Crossed], _Summary]: ...
def temporal_layers(session: Session) -> list[str]: ...
def temporal_shown(session: Session, a: float, b: float | None = None, layers: list[str] | None = None) -> list[str]: ...
